### ISSUE TITLE
Unexpected colored leading spaces

### ISSUE THREAD

**Issue by neilsustc** [fabiospampinato/vscode-todo-plus#1]
If I have this setting `"editor.renderWhitespace": "boundary"`, the spaces are also colored.

![image](https://user-images.githubusercontent.com/7588612/29491936-d9ba2bca-859d-11e7-8279-89e689f557de.png)

**Comment by fabiospampinato** [comment]
Fixed via b61c541, an update has been pushed to the registry.

Thanks for reporting the problem.
