### ISSUE TITLE
Refresh button not working in Embedded section in version 4.1.1 

### ISSUE THREAD

**Issue by EvgeniyMakhmudov** [fabiospampinato/vscode-todo-plus#101]
OS: MacOsX / Linux
Versions: latests (vscode 1.26)

Steps to reproduce
1) Open Embedded sections in project
2) See items like
```
file1
dir1/file2
```
3) Extend config option `todo.embedded.exclude`  with element `**/file2`
4) Click on `Refresh` button to refresh items in Embedded section
5) expected values like
```
file1
```
but no change occured.

**Comment by pzmarzly** [comment]
The button works, but does not check for changes in exclusion list.

**Comment by fabiospampinato** [comment]
> The button works, but does not check for changes in exclusion list.

Precisely.

I'll try to lift some of these restrictions, it shouldn't really be a problem to get rid of them entirely.

**Comment by fabiospampinato** [comment]
This should be fixed in v4.2.1.

Some things still require a reload of VSC, but this one no longer does.
