### ISSUE TITLE
Avoid applying colors to (visible) whitespace

### ISSUE THREAD

**Issue by dakotahawkins** [fabiospampinato/vscode-todo-plus#103]
TODO+ file:
![image](https://user-images.githubusercontent.com/638578/44130231-795fed3a-a01a-11e8-8944-ea5914ccf992.png)

As a python docstring (just to show text coloring not applied to whitespace):
![image](https://user-images.githubusercontent.com/638578/44130281-b1885d00-a01a-11e8-9ab4-66e00d3e9452.png)

**Comment by fabiospampinato** [comment]
Duplicate of https://github.com/fabiospampinato/vscode-todo-plus/issues/67.
