### ISSUE TITLE
Embedded view inside the explorer (just like native outline window)

### ISSUE THREAD

**Issue by bryantebeek** [fabiospampinato/vscode-todo-plus#106]
First, thanks for this extension, it's amazing!

My question is related to the fact that the todos are currently visible through a dedicated side menu icon, which is nice, but it would be really great if there is a setting to also show them under the file explorer so I can see them easily while coding :)

Thanks again @fabiospampinato

**Comment by fabiospampinato** [comment]
It might make sense to add optional support for this, maybe we could use regexes for avoiding cluttering the `package.json` file https://github.com/Microsoft/vscode/issues/33547 🤔

**Comment by fabiospampinato** [comment]
On a second thought you should just follow this hint:

> Activity Bar: you can switch the focus to the Todo activity bar view by assigning a shortcut to the `workbench.view.extension.todo` command.

We shouldn't clutter the explorer view.

**Comment by bryantebeek** [comment]
If anyone happens to be interested, I ended up using these keybindings:

```
{
    "key": "ctrl+t",
    "command": "workbench.view.extension.todo",
    "when": "explorerViewletVisible"
},
{
    "key": "ctrl+t",
    "command": "workbench.view.explorer",
    "when": "!explorerViewletVisible"
},
```
