### ISSUE TITLE
 The latest 4.2.0 version does not work

### ISSUE THREAD

**Issue by tiansin** [fabiospampinato/vscode-todo-plus#108]
OS: Win10
VSCODE: 1.2.6.1

`Activating extension `fabiospampinato.vscode-todo-plus` failed:  ENOENT: no such file or directory, access 'd:\Soft\VSCode\resources\app\node_modules\vscode-ripgrep\bin\rg.exe'`

I found rg.exe in the following two places after searching, but the extension indicates that there is no such program.

1.D:\Soft\VSCode\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe
2.D:\Soft\VSCode\resources\app\extensions\search-rg\node_modules\vscode-ripgrep\bin\rg.exe

**Comment by fabiospampinato** [comment]
Maybe bad! Should be fixed in v4.2.1.
