### ISSUE TITLE
[BUG] Time format of tag @done doesn't respect config todo.timekeeping.finished.format

### ISSUE THREAD

**Issue by WilliamStone** [fabiospampinato/vscode-todo-plus#109]
Hi, 
    I configured:
        _// Format used for displaying time inside @done/cancelled
        "todo.timekeeping.finished.format": "**YYYY-MM-DD** HH:mm",_
    when I press Alt+C on a task item, it will be tagged by:
        _@cancelled(**2018-08-19** 01:44)_
    which respects the config.
    But when I press Alt+D on a task item, it will be tagged by:
        _@done (**8/19/2018**, 1:51:30 AM)_
    which does not respect the config.

**Comment by fabiospampinato** [comment]
This is a weird one, I don't think the code for producing those tags can lead to this bug:

https://github.com/fabiospampinato/vscode-todo-plus/blob/master/src/todo/items/todo.ts/#L221-L225

What version of the extension are you on? And what OS?

Maybe there's a conflict with another extension.
