### ISSUE TITLE
todo file color option may be good

### ISSUE THREAD

**Issue by hujianxin** [fabiospampinato/vscode-todo-plus#11]
If the color of todo file is light or other color which is different with our source code files, that will be good.

Will this be hard to achieve it?

**Comment by hujianxin** [comment]
Like this: ![](https://ws3.sinaimg.cn/large/006tKfTcly1fkqd0qese9j31kw0ykaf4.jpg)

**Comment by fabiospampinato** [comment]
I'd love to add support for this, but it's just not possible at the moment with the available APIs.

I've opened an [upstream issue](https://github.com/Microsoft/vscode/issues/35379) about this, give it a thumbs up.
