### ISSUE TITLE
Add option to always show word based suggestions

### ISSUE THREAD

**Issue by tk7728** [fabiospampinato/vscode-todo-plus#110]
Hi, 
first of all i had to apologise for my bad english.
This is my first post ever on github (i have registered few minutes ago). 
Also this is not a bug, it is more a feature request. 

it is possible, that the normal "word based suggestions" works in todo-files?
i am not a developer, but i could imagine that the method "provideCompletionItems" should be modified and should return "null", if tags not fit: https://github.com/Microsoft/vscode/issues/21611#issuecomment-368455296

thanks a lot

**Comment by tk7728** [comment]
but also in markdown files the "word based suggestion" from vscode works

![grafik](https://user-images.githubusercontent.com/42512227/44308967-246cef00-a3bf-11e8-99cb-399ed11d1ccc.png)

**Comment by fabiospampinato** [comment]
You're right, it wasn't showing for me automatically, I had to trigger the autocomplete manually.

Then I guess we should also support it in the same way 🤔

**Comment by fabiospampinato** [comment]
Implemented in v4.4.0, it was surprisingly tricky to add support for this.

Thanks for the suggestion.

**Comment by tk7728** [comment]
thanks a lot!
