### ISSUE TITLE
todo.embedded.provider = 'rg' does not work

### ISSUE THREAD

**Issue by tiansin** [fabiospampinato/vscode-todo-plus#111]
OS: Win10 
VSCode: 1.26.1
Todo+: 4.3.2

`"todo.embedded.provider": "javascript",`

Now I can only be set to the javascript model, is set to the rg will not search out anything.

**Comment by fabiospampinato** [comment]
Is `ag` not working also for you? (You'll have to install it)

Are you seeing any errors in the debug console?

<img width="505" alt="screen shot 2018-08-20 at 21 32 54" src="https://user-images.githubusercontent.com/1812093/44362223-9ed16800-a4c0-11e8-8f63-0d096b382a04.png">

**Comment by tiansin** [comment]
https://github.com/k-takata/the_silver_searcher-win32/releases
I downloaded the 64-bit platform ag.exe copy to widnows directory, the configuration file modified the provider ag, and then restart the vscode.
Still nothing happens, and the console looks fine, there is no output for the plugin.

**Comment by fabiospampinato** [comment]
> I downloaded the 64-bit platform ag.exe copy to widnows directory, the configuration file modified the provider ag, and then restart the vscode.

I don't know if that's the correct way of installing it. Can you execute the `ag` command from the command prompt after doing this? 

I had tried installing it with Chocolatey and it worked fine for me under Windows.

> PS: I removed ag.exe from the windows directory and found that the extension function is normal.

Does it work even with the `rg` provider set? Or with `"todo.embedded.provider": ""`?

>  Is it because the 'ag.exe' can't be found using the default 'javascript'?

If you set the provider to be `javascript` the extension won't even check if you have `ag` installed.

**Comment by tiansin** [comment]
I have debugged the extension.

1.
https://github.com/fabiospampinato/vscode-todo-plus/blob/82940ab52ce092d0e4c3a9fb7406cb7d74c64848/src/utils/embedded/providers/ag.ts#L97

`this.filterAckmate`
The data has been returned, and the code is executed to filter the returned data.

2.
https://github.com/fabiospampinato/vscode-todo-plus/blob/82940ab52ce092d0e4c3a9fb7406cb7d74c64848/src/utils/embedded/providers/ag.ts#L107

When I click the refresh button, it detects that the 'filePaths' variable is an empty array, so the refresh function cannot be used.

@fabiospampinato 
I hope to fix it as soon as possible.Thanks.

**Comment by fabiospampinato** [comment]
It looks like yet another bug related to Windows using backslashes instead of forward slashes in file paths 😩

**Comment by fabiospampinato** [comment]
Should be fixed in v4.4.1, thanks for reporting the issue.
