### ISSUE TITLE
ag and rg do not honor the todo.embedded.exclude setting properly

### ISSUE THREAD

**Issue by nilsml** [fabiospampinato/vscode-todo-plus#112]
When using either ag or rg for searching, it seems like some of the folders that are excluded are included.
Not the same folders though...
While rg includes anything under the 3party-folder, ag includes anything under the dist-folder.
Both are excluded in the config.

**Comment by fabiospampinato** [comment]
>  it seems like some of the folders that are excluded are included

It's a bug then.

Can you share your settings and a screenshot of what you're actually seeing?

**Comment by nilsml** [comment]
Here are some screenshots:

![ag-settings](https://user-images.githubusercontent.com/1836295/44505759-650c8700-a6a3-11e8-9113-2b70e1d14cb1.PNG)
![search-result-ag](https://user-images.githubusercontent.com/1836295/44505756-6473f080-a6a3-11e8-9b48-7783904d2028.PNG)
![rg-settings](https://user-images.githubusercontent.com/1836295/44505760-650c8700-a6a3-11e8-846f-2a007c6ae2b6.PNG)
![search-result-rg](https://user-images.githubusercontent.com/1836295/44505758-6473f080-a6a3-11e8-8ef2-a57e45ad7b29.PNG)

The thing with Ag is that none of my own files are being searched through. Only the ones in the dist-folder which I don't want. Right now only javascript search works as expected.

**Comment by fabiospampinato** [comment]
One problem is that weirdly enough a glob like `**/foo` is supposed to match `/path/to/foo` but not `/path/to/foo/bar`, so you might also want to exclude `**/3party/**` along with `**/3party`.

Other than that I can't see any other issue. 

> The thing with Ag is that none of my own files are being searched through.

Where are your own files actually located? 

Are you seeing any errors in the debug console?

**Comment by nilsml** [comment]
So, **/3party/** did the trick with rg.
ag on the other hand is still acting weirdly, showing only todos from files in the dist-folder.
Since all my files are in the React-folder, I tried using `"todo.embedded.inculde": ["React/**"]` but then ag does not find any embedded todos at all. rg works fine.

**Comment by nilsml** [comment]
No errors in the debug console btw.

**Comment by fabiospampinato** [comment]
I'm not sure `React/**` is the glob you want, maybe it should be `**/React/**`.

Can you paste here your settings (not a screenshot) and a sample directory that reproduces the problem?

What OS are you using? 
And what version of the extension?

**Comment by nilsml** [comment]
I think I know what is causing the problem now.
When creating new files with only one comment in it, ag picks it up.
However, if I create a new line in the file, it is not detected anymore.
So probably some kind of cr/lf issue..

I am on Windows 10 running version 4.4.1 of the extension.

**Comment by fabiospampinato** [comment]
It might be Yet Another Windows-related Bug 😩 

I'll look into that, thanks for the info 👍

**Comment by fabiospampinato** [comment]
Weirdly enough I can still find those embedded todos even when using CRLF instead of LF, but not on Windows 😕Good news is that I can reproduce the problem.

**Comment by fabiospampinato** [comment]
And I can only reproduce when using `ag` 🤨

**Comment by fabiospampinato** [comment]
Fixed in v4.4.2.
