### ISSUE TITLE
Feature request: New Setting "hours per day"

### ISSUE THREAD

**Issue by konrup** [fabiospampinato/vscode-todo-plus#115]
Default: 24
Change to something like 8 to get a better overview of how many working days are needed to complete this task.

For example: 

hoursPerDay: 24
```
Group: (2) 8h
  ☐ Task 1 @4h
  ☐ Task 2 @4h

Group 2: (2) 1d6h
  ☐ Task 3 @10h
  ☐ Task 4 @20h
```

hoursPerDay: 8
```
Group: (2) 1d
  ☐ Task 1 @4h
  ☐ Task 2 @4h

Group 2: (2) 3d6h
  ☐ Task 3 @10h
  ☐ Task 4 @20h
```

**Comment by fabiospampinato** [comment]
Thanks for the suggestion but I'm skeptical about redefining what a day is.

For your particular use case you should just multiply the number of weeks/days by 3 in your head. 🤔 

If you really need this you can patch the extension yourself, we are calculating those estimates [here](https://github.com/fabiospampinato/vscode-todo-plus/blob/master/src/utils/time.ts).
