### ISSUE TITLE
Tutorial/how to use?

### ISSUE THREAD

**Issue by lucamanga** [fabiospampinato/vscode-todo-plus#116]
It seems that a tutorial or how to use this extension is missing...

for i.e., I cannot see how to move a done task from a "New:" to "Done:" list...

**Comment by fabiospampinato** [comment]
[This](https://github.com/fabiospampinato/vscode-todo-plus/blob/master/resources/readme.todo) and [this](https://github.com/fabiospampinato/vscode-todo-plus/blob/master/resources/demo/syntax.png) are our tutorial, there isn't really much more to learn, just read the readme.

> for i.e., I cannot see how to move a done task from a "New:" to "Done:" list...

Manually. Unless you archive them and change the archive name to "Done" via `"todo.archive.name": "Done"`.

**Comment by nealot** [comment]
@fabiospampinato Maybe the demo section could be moved before the features or usage? Being greeted by a wall of settings isn't very friendly to newcomers and might be the cause of confusion.

**Comment by fabiospampinato** [comment]
@nealot it's true that as the extension's capabilities grew the settings section became a "wall". However I think it would also not be optimal for not-newcomers to have the demo section moved before the settings, maybe I should just put a link to the demo section early on, I'll think about it 🤔

**Comment by nealot** [comment]
@fabiospampinato I don't think there is any benefit to adding a section for settings; vscode already has a contribution area that displays all the features. 
![screenshot from 2018-09-03 13-55-54](https://user-images.githubusercontent.com/36805289/44998120-199a8880-af81-11e8-91a1-39d69027f372.png)

**Comment by fabiospampinato** [comment]
@nealot but you want to see what settings are supported even before installing the extension, or if you're viewing it's repository or it's page on the marketplace, right? Besides that table is [broken](https://github.com/Microsoft/vscode/issues/45987).

**Comment by raulrfa** [comment]
I am a newbie.  But really I do not undestand how to use the ToDo+ in python, I read the Readme.md and I don't know how to made the embedded todo to use the file in Python source  (#TODO ?). And I don't understand how to make the file customized to Python.
I work with VS Code 1.32.

**Comment by fabiospampinato** [comment]
@raulrfa This extension defines the "todo" language, you can't use it with any other kind of files.

**Comment by fabiospampinato** [comment]
> I do not undestand how to use the ToDo+ in python

Todo+ defines the `todo` language, so most of the things it provides you can only do within those kind of files.

> I don't know how to made the embedded todo to use the file in Python source (#TODO ?)

The syntax we support for todo files is defined under the `todo.embedded.regex` setting. If you want to add a todo to some other file add something like this `#TODO: Foo` and you're set. Now that todo should be displayed in the activity bar and you can retrieve all your embedded todos via the `Todo: Open Embedded` command.

> And I don't understand how to make the file customized to Python.

I'm not exactly sure what that means 🤔
