### ISSUE TITLE
Insert ☐ in newlines

### ISSUE THREAD

**Issue by NavyAdmiral** [fabiospampinato/vscode-todo-plus#117]
Hi. Thanks for the great extension. One feature I'd be willing to see is auto-inserting  ☐ on Enter.

Demo:
```
 ☐ When I'm on this line|
```
and I click Enter
```
 ☐ When I'm on this line
 ☐ // should auto-write ☐  
```

tl\dr: replicate Markdown's behavior for `-` https://i.imgur.com/I0IDbWQ.gifv

**Comment by fabiospampinato** [comment]
Our syntax is more complicated than Markdown's, with regard to tasks.

When ones goes to a new line it might want to insert a project or a comment instead, not always a task. So having this feature could be counterproductive.

Assigning this action to `shift+cmd+enter` might make more sense, but then it's not really that beneficial, one has to remember another shortcut just for not wanting to press the enter key earlier.

I think you should be able to get something you'd like using the [macros](https://marketplace.visualstudio.com/items?itemName=geddski.macros) extension.
