### ISSUE TITLE
More/custom tree icons

### ISSUE THREAD

**Issue by nealot** [fabiospampinato/vscode-todo-plus#118]
Hey, just wanted to ask if more icon options could be supported? Being able to customize the color of the icon is nice but a plain circle isn't very intuitive. The picture [here](https://github.com/Gruntfuggly/todo-tree/issues/51#issuecomment-417955716) shows how icon diversity can improve accessibility. Even if it's just 4-5 icon options, it would become much more easier to differentiate between certain keywords.

**Comment by fabiospampinato** [comment]
Like this?

![](https://user-images.githubusercontent.com/6636980/44960135-79305f80-aebf-11e8-81ca-7252ff513098.png)

I'm not convinced this is more intuitive, at the end of the day the more you see those icons the more you'll be distinguishing them by color.

I personally also think the tree looks uglier in that particular screenshot.

Last but not least where should those icons come from? I would expect only a very few number of people would design their own icons, if there was the possibility. Using [octicons](https://octicons.github.com) might be an option but those icons aren't particularly fitting for our use case I think.

**Comment by nealot** [comment]
Yeah, I agree that the octicons look pretty weird in the screenshot so I was thinking we have 5 icon selections based on something similar to this:
![image](https://user-images.githubusercontent.com/36805289/44997017-464aa200-af79-11e8-87fa-52400d902d83.png)
Most of the keywords can be sorted under one of those categories so there's no need to maintain a bunch of fancy icons. As for where to find them, there's always the builtin icons
![screenshot from 2018-08-21 13-03-48](https://user-images.githubusercontent.com/36805289/44997664-01753a00-af7e-11e8-897b-7f61f9d13ee7.png)
or [material design icons](https://material.io/tools/icons/?style=baseline)
![round_warning_black_18dp](https://user-images.githubusercontent.com/36805289/44997786-de975580-af7e-11e8-9894-e34407cd7465.png) ![round_info_black_18dp](https://user-images.githubusercontent.com/36805289/44997790-e7882700-af7e-11e8-895f-b521849b9712.png) ![round_error_black_18dp](https://user-images.githubusercontent.com/36805289/44997793-eb1bae00-af7e-11e8-8f8c-fa84366da4bf.png) ![round_check_circle_black_18dp](https://user-images.githubusercontent.com/36805289/44997797-ef47cb80-af7e-11e8-9fc8-0f3b74f16c06.png) ![round_cancel_black_18dp](https://user-images.githubusercontent.com/36805289/44997843-3766ee00-af7f-11e8-8eb1-fc5c0c6c02c6.png)

**Comment by fabiospampinato** [comment]
I don't think those icons are well suited for our purposes.

Perhaps a setting for providing a path to a custom icon for each todo type would be enough? I'm not sure how many people will use it though.

**Comment by nealot** [comment]
Yeah, this request seems pretty niche atm and not worth the effort; I'll close it for now.
