### ISSUE TITLE
Sorting archive by 'done' date

### ISSUE THREAD

**Issue by eapyl** [fabiospampinato/vscode-todo-plus#119]
Thank you for great extension.
It will be great to automatically sort archive items by 'done' date. Is it possible to add? Thanks.

**Comment by fabiospampinato** [comment]
This has actually been a long-time [todo](https://github.com/fabiospampinato/vscode-todo-plus/blob/96398f8b1973ce846439d5fae9a63905438245fa/.todo#L3). 

I currently don't have to time for implementing this, so if anybody wants to submit a PR I'll be happy to consider it.

**Comment by fabiospampinato** [comment]
Implemented in v4.5.1 via the `todo.archive.sortByDate` option, which is disabled by default.
