### ISSUE TITLE
Multicursor support

### ISSUE THREAD

**Issue by henricryden** [fabiospampinato/vscode-todo-plus#12]
Would it be possible to add multicursor support? An example of current behavior is shown below:

![todoplus_multicursor](https://user-images.githubusercontent.com/26415523/31891730-8dd3dbba-b807-11e7-9c55-278aefd7b4d2.gif)

**Comment by fabiospampinato** [comment]
Thanks for the suggestion, I'll add support for this.

**Comment by fabiospampinato** [comment]
I've just published v1.5.3 that should fix this.
