### ISSUE TITLE
Add "lib" exlcusion

### ISSUE THREAD

**Issue by yanikore** [fabiospampinato/vscode-todo-plus#120]
It would be nice if "/lib/" folders are also exlcluded by default. The `todo.embedded.exclude` and `todo.file.exclude` take up a lot of space in the settings.json file.

**Comment by fabiospampinato** [comment]
I don't think `/lib` is an obvious exclusion, therefore it shouldn't be excluded by default. If you have a compelling argument on why this is actually the case I'll be happy to hear it.

There isn't lack of space in `settings.json` after all.

**Comment by yanikore** [comment]
There isn't much lack, true. But when adding it I found it weird that all of the other directories came with it. I also thought it was a very common library directory name, I've been using it a lot for libraries that do not come from a package manager.

**Comment by fabiospampinato** [comment]
> But when adding it I found it weird that all of the other directories came with it.

I found it weird to the first time it happened, but this is controlled by VSC, I can't fix that.

>  I've been using it a lot for libraries that do not come from a package manager.

I usually put those into a `vendor` directory, maybe you should use that too.

**Comment by yanikore** [comment]
> I usually put those into a vendor directory, maybe you should use that too.

Hence why I mentioned the package manager, I use the vendor folder as well.
