### ISSUE TITLE
Refresh Embedded in the Activity Bar Not Working

### ISSUE THREAD

**Issue by carolitascl** [fabiospampinato/vscode-todo-plus#123]
The refresh of the embedded TODOS in the activity bar is not working ok.

It works ok after the first TODO is put in a file and do a restart of vscode. After the restart the followings TODOS refresh ok.

When there is no TODOS in a file, or you delete the last one, the file is deleted from the activity bar, and when you put again the first TODO in the file, the refresh does not work till you restart vscode.

**Comment by fabiospampinato** [comment]
It should be fixed in v4.4.5 👍
