### ISSUE TITLE
Embedded todos only found in newly created files

### ISSUE THREAD

**Issue by ko-dever** [fabiospampinato/vscode-todo-plus#124]
It seems your extension is only working for newly created files, at least in my case.

I created a basic React app using [create-react-app](https://github.com/facebook/create-react-app/). I kept the same folders structure, I just added another one "components/" inside "src/", with some JS files, and then I installed your extension.

I did not understand why my `// TODO: (...)`, `// NOTE: (...)` were not recognized, then I noticed I had to install a provider, so I installed **rg** using **brew**, edited my VSC settings by including `"todo.embedded.provider": "rg",`, and restarted VSC (to be sure).
Many times I tried to select `Todo: Open Embedded` in the Command Palette, with different files, but each time I got no results (even the panel "Embedded" is not working) except the notification :
> No embedded todos found

I decided to do exactly the same thing you show in your [GIF "Embedded todos"](https://github.com/fabiospampinato/vscode-todo-plus#embedded-todos), so I created a file `src/index.ts` with some `// TODO: (...)` and `// NOTE: (...)`, and now the command `Todo: Open Embedded` and the panel work correctly.
In fact, if I recreate all my existing files just by duplicating them, the extension works and inline comments are correctly found.

- My OS : macOS High Sierra 10.13.6.
- My VS Code : 1.27.2.

PS: Off-topic but it took me a bit of time to clearly understand how to start using your extension. I saw [this comment](https://github.com/fabiospampinato/vscode-todo-plus/issues/116#issuecomment-418025816) and I think it is a good idea to see what your extension allow us to create first, before all the shortcuts, the commands and the settings.

Thank you 🙂 .

**Comment by bcroq** [comment]
I get this bug too.

VS Code: 1.27.2
Todo+: 4.4.4

**Comment by fabiospampinato** [comment]
@ko-dever Thanks for reporting the problem 👍 I'm working on it right now.

> then I noticed I had to install a provider

Actually you don't have to, if you don't explicitly set one it will use the first one available, that is, `ag` if you have it intalled or `rg` if your VSC installation is new enough or it will fallback to plain `javascript`.

> Many times I tried to select Todo: Open Embedded in the Command Palette, **with different files**

The file you are currently viewing doesn't matter.

> PS: Off-topic but it took me a bit of time to clearly understand how to start using your extension. I saw this comment and I think it is a good idea to see what your extension allow us to create first, before all the shortcuts, the commands and the settings.

You're probably right, those sections were much shorter in the initial release, but grew longer with every feature I've added. Maybe a link to the "demo" section of the readme would be enough? Those gifs also take up a lot of space, I'm not sure if they should be place at the very top 🤔

**Comment by fabiospampinato** [comment]
It should be fixed in v4.4.5 👍

**Comment by ko-dever** [comment]
Everything seems to work correctly 🙂 .

I noticed some other small problems when modifying some parameters related to regexp. I will post a feedback about this later.

**Comment by ko-dever** [comment]
Everything seems to work correctly 🙂 .

I noticed some other small problems when modifying some parameters related to Regexp. I will post a feedback about this later.
