### ISSUE TITLE
Project Text is not showing when all Tasks are done

### ISSUE THREAD

**Issue by henrikcomes** [fabiospampinato/vscode-todo-plus#129]
As the title already says, when all tasks in a project are @done the project text is no longer visible.
If this is the right behavior, could there be an option to always show the text?

Some screenshots to provide visual context.
![image](https://user-images.githubusercontent.com/33446962/45952717-2eaa8a80-c008-11e8-8279-5f918006f259.png)

![image](https://user-images.githubusercontent.com/33446962/45952692-1a668d80-c008-11e8-9d59-5edda761cc36.png)

**Comment by fabiospampinato** [comment]
This is controlled by the following setting:

```js
// Show statistics next to a project, boolean or JS expression
"todo.statistics.project.enabled": "global.projects < 100 && project.pending > 0"
```

You can read more about it in the readme. Basically by default we want `project.pending > 0`, so if there are no pending todos it won't be enabled for that project.

Maybe this shouldn't be the default behavior 🤔 I'll think about changing this, thanks.
