### ISSUE TITLE
Work with todo in JSDoc format

### ISSUE THREAD

**Issue by leandrocunha** [fabiospampinato/vscode-todo-plus#130]
I really could like to use this extension together with JSDoc format. For example, the extension should be able to parse snippets like:

``` 
/**
  * @function foo - A simple description.
  * @param {string} bar - Any string parameter
  * @returns {string} The function should return another string
  * @todo  Implemente it to works fine
  * @example
  */
```

**Comment by fabiospampinato** [comment]
You can already, if you update the regexes used by this extension. There are a few settings for it.

I'm keeping this open for considering supporting this by default.

**Comment by leandrocunha** [comment]
I could not do it, can you explain how? I think it can be at README file to.

**Comment by leandrocunha** [comment]
Yes, I found this settings and did some unsuccessful attempts. I'm not familiarized with complex regex, so I decided to open this issue.

It can be very useful.

**Comment by fabiospampinato** [comment]
I've added support for this in v4.6.1 👍 

Thanks for the suggestion.
