### ISSUE TITLE
Archive function removing unattached notes or empty sections?

### ISSUE THREAD

**Issue by NealWH** [fabiospampinato/vscode-todo-plus#133]
Apologies if i'm missing something explaining the intention here, but having just started using this I've noticed it seems to be a little too efficient in cleaning up using the archive function and not explaining what it has done.

Perhaps my use case is a little strange but I'd like it to be a scratch pad where I can put in some hierarchical notes related to projects without any immediate todo items to place.  When I go to archive though I seem to lose that data completely which makes me wary of using the archive option at all.

(to mention here otherwise though I'm really liking the plugin as a simple way to work through lists and hide details as necessary.  I only wish it was possible to use in regular visual studio!)

**Comment by fabiospampinato** [comment]
The "Archive" function is meant to archive completed todos in a special "Archive" project located at the bottom of the page.

As part of it's "clean up" work it removes empty projects, the idea behind this is that such projects no longer have any todos (most probably they are all completed) and there's no longer a need to that project.

I think you should write your notes as todos, and not as projects.
