### ISSUE TITLE
Very slow extension activation time, causes ExtensionHost to hang

### ISSUE THREAD

**Issue by carlocardella** [fabiospampinato/vscode-todo-plus#134]
- Extension Name: vscode-todo-plus
- Extension Version: 4.7.0
- OS Version: Windows_NT x64 10.0.17763
- VSCode version: 1.28.0-insider

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 13119,
		"activateCallTime": 22,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	}
}
```

The extension is loaded at startup and it takes multiple seconds (it varies across my machines, from 3-4 seconds to 13 seconds as shown above): this makes VSCode startup very slow and the messages below popup every time.
For test I have disabled the todo+ extension and the problem no longer reproduces

![image](https://user-images.githubusercontent.com/5784415/46620659-29564100-cada-11e8-9a02-e54787af9f1e.png)
![image](https://user-images.githubusercontent.com/5784415/46620677-35420300-cada-11e8-896d-65d8fe5f31f2.png)

**Comment by fabiospampinato** [comment]
Thanks for opening this issue!

I'm seeing startup times of about 600ms on my machine (mid-2014 MBP), which still seems excessive, I'll investigate this further.

**Comment by fabiospampinato** [comment]
I've find a little room for improvement, v4.8.1 should startup a bit quicker.

But I couldn't understand why VSC is still reporting such high numbers, at one point the extension looked like this:

```ts
import Utils from './utils';
function activate () {
  Utils; // Commenting this out "fixes" the problem
}
```

and all `export default new Whatever ()` where replaced with `export default {}`.

There's barely anything going on, from what I can measure they should all take less 10ms, but I'm seeing reported times of about 1s.

I don't know what the problem could be, maybe VSC is taking forever to load the files and parsing them? I have no idea.

Can you check if the situation is improved in v.4.8.1?

Are you seeing multi-second startup times only for Todo+?

**Comment by carlocardella** [comment]
This particular laptop is about 6 years old so it's not the best performing I have (details below); startup time on this machine is not the best and it varies a bit, even though it is generally fairly high (at least 4-5 seconds). I have just updated to the latest version (4.8.1) the load time is 1556ms, still slow but it's a big improvement on this old hardware (and by the way, this time I did not get the _extension host unresponsive_ popup). 

```
CPUs	Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz (8 x 2694)
GPU Status	2d_canvas: enabled
checker_imaging: disabled_off
flash_3d: enabled
flash_stage3d: enabled
flash_stage3d_baseline: enabled
gpu_compositing: enabled
multiple_raster_threads: enabled_on
native_gpu_memory_buffers: disabled_software
rasterization: enabled
video_decode: enabled
video_encode: enabled
webgl: enabled
webgl2: enabled
Memory (System)	15.93GB (4.88GB free)
Process Argv	
Screen Reader	no
VM	0%
```


On my 2016 MBP load time is ~600ms, while on a newer Windows laptop the load time is ~980ms
```
CPUs	Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)
GPU Status	2d_canvas: enabled
checker_imaging: disabled_off
flash_3d: enabled
flash_stage3d: enabled
flash_stage3d_baseline: enabled
gpu_compositing: enabled
multiple_raster_threads: enabled_on
native_gpu_memory_buffers: disabled_software
rasterization: enabled
video_decode: enabled
video_encode: enabled
webgl: enabled
webgl2: enabled
Memory (System)	31.86GB (13.79GB free)
Process Argv	
Screen Reader	no
VM	0%
```

**Comment by fabiospampinato** [comment]
> I can do some more testing trying to disable and gradually enable my extensions (I have quite a few installed, but only a handful load at startup) to see if there is any incompatibility/conflict, unless you know a more effective way to test it?

I don't know a more effecting way of testing this. But I've disabled all my extensions, enabled only Todo+ and the reported startup times are still the same, so I guess there shouldn't be any conflicts with other extensions.

Unfortunately it looks like VSC doesn't provide the right tools for profiling an extension startup phase, unless I overlooked something and there's actually an expensive bit of code in there I'm not sure what the cause of the slowness is.

**Comment by carlocardella** [comment]
Ok, I'll see if I can do some more testing and report back. 
Also, for the sake of accuracy I have to amend my statement from last night: startup time on the newer Windows laptop (Dell XPS 9560) is ~9,000ms, not 900ms:

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 8794,
		"activateCallTime": 15,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	}
}
```

```
OS Name	Microsoft Windows 10 Pro
Version	10.0.17763 Build 17763
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Manufacturer	Dell Inc.
System Model	XPS 15 9560
System Type	x64-based PC
System SKU	07BE
Processor	Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz, 2801 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Dell Inc. 1.9.4, 4/23/2018
SMBIOS Version	3.0
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Dell Inc.
BaseBoard Product	05FFDN
BaseBoard Version	A00
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.17763.1"
Time Zone	Pacific Daylight Time
Installed Physical Memory (RAM)	32.0 GB
Total Physical Memory	31.9 GB
Available Physical Memory	14.2 GB
Total Virtual Memory	36.9 GB
Available Virtual Memory	9.28 GB
Page File Space	5.00 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Not Available
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, Secure Boot, DMA Protection, UEFI Code Readonly, Mode Based Execution Control
Virtualization-based security Services Configured	
Virtualization-based security Services Running	
A hypervisor has been detected. Features required for Hyper-V will not be displayed.	
```

**Comment by fabiospampinato** [comment]
9s is just unacceptable.

Do you maybe have a very large file highlighted by Todo+ when VSC starts up?

**Comment by carlocardella** [comment]
It is a possibility, my workspace has a number of Git repos in with a total of ~40,000 files (the vast majority fairly small), I can get more details on it if needed.

I just tried to open an empty VSCode window (no workspaces open, no files or folders) and Todo+ startup time is ~1.1 seconds (no hanging extension host message this time), it still seems high since there are no files to process but this looks more in line to other reports you mentioned 

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 1121,
		"activateCallTime": 14,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	}
}
```

**Comment by fabiospampinato** [comment]
> Do you maybe have a very large file highlighted by Todo+ open when VSC starts up?

@fuzetsu do you? 

@fuzetsu @carlocardella was the "Todo" activity bar view active when VSC started up?

**Comment by carlocardella** [comment]
No, for me the Activity Bar was not active, in fact with my large workspace open if I select the Todo Activity Bar the I definitely see Todo scanning happening: 

![image](https://user-images.githubusercontent.com/5784415/46680836-cd092500-cb9e-11e8-95b0-9f85352b234b.png)

I have also set the Files and Embedded views to not be expanded hoping to alleviate some of the pressure on the extension

```json
"todo.embedded.view.expanded": false,
"todo.file.view.expanded": false
```

**Comment by fabiospampinato** [comment]
@carlocardella that's pretty weird, are you sure everything else is the same? e.g. same activity views visible, same folders in the workspace, same files open.

**Comment by fabiospampinato** [comment]
> The first ~1s seems to be spent just importing stuff, the following extension takes about 260ms to execute:

For future reference, most of that time is spent loading these extensions: `chokidar`, `globby`, `micromatch`, `sugarDate`.

They should at the very least only be imported when needed.

**Comment by fabiospampinato** [comment]
Good news, just compiling the extension with webpack reduces the startup time by about 80%. I would say that's good enough.

I'm going to compile all my extensions with webpack in the following days. 👍

**Comment by fuzetsu** [comment]
Good news 👍 

For the record I only had one small (~200 lines) todo file open in another window. I had just opened a new folder with vscode.

**Comment by carlocardella** [comment]
> @carlocardella that's pretty weird, are you sure everything else is the same? e.g. same activity views visible, same folders in the workspace, same files open.

Yes, everything was the same, I was also surprised to see such massive difference. I actually still have the old folder (I just renamed it, not really deleted) so I could try to compare the files, maybe there are temp files or other garbage causing the problem. 
Anyway great news about the reduced startup time, I still have the problem on my old laptop, I'll test the new build there

**Comment by carlocardella** [comment]
I couldn't resist the temptation and I clean up the local extension folder on my old laptop (I can still get it back to run more tests though), I reopened the same large workspace and the Todo+ load time went from 13 seconds to ~2 seconds. Clearly that local extension folder was part of the problem. 
By the way, I used this workaround on 4 different machines, I've seem improved startup times on all of them

**Comment by fabiospampinato** [comment]
> I couldn't resist the temptation and I clean up the local extension folder on my old laptop (I can still get it back to run more tests though), I reopened the same large workspace and the Todo+ load time went from 13 seconds to ~2 seconds.

Great, I think you should open an issue in vsc's repo about this.

**Comment by fabiospampinato** [comment]
As of v4.8.2 the extension is now bundled with webpack.

Are you guys still having very slow startup times?

**Comment by carlocardella** [comment]
Load time is down to ~300ms now, big improvement from ~2 seconds on this laptop (everything else being the same), thanks! 👍

**Comment by fuzetsu** [comment]
Right before updating I was getting 9-10 seconds consistently, right after updating I got 300ms. 👍

**Comment by fabiospampinato** [comment]
> Was the massive difference in load time caused only by webpack?

Yes and no, the startup performance has been reduced dramatically thanks to webpack:

- There are less files to open since we are exporting a single file
- There's less code to parse since it's now minified

But it shouldn't have taken multiple seconds to startup in the first place, that was something I couldn't reproduce.

> Load time is down to ~300ms now
>  right after updating I got 300ms

I'm seeing about 300ms too. I think this could actually be reduced further, probably by half or more, I'll probably do it in the future.

Let me know if you encounter any other slowness. 👍

**Comment by fabiospampinato** [comment]
>  I think this could actually be reduced further, probably by half or more, I'll probably do it in the future.

Actually I did it right now in v4.8.4, the startup time should be about half of it was in v4.8.3.
