### ISSUE TITLE
Slow-loading compared to bigger plugins

### ISSUE THREAD

**Issue by ShinobiWPS** [fabiospampinato/vscode-todo-plus#135]
- Extension Name: vscode-todo-plus
- Extension Version: 4.8.1
- OS Version: Darwin x64 16.7.0
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 2934,
		"activateCallTime": 11,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	}
}
```

I think it takes really too much to load, compared to bigger extensions

**Comment by fabiospampinato** [comment]
Duplicate of  https://github.com/fabiospampinato/vscode-todo-plus/issues/134.

Did you see an improvement in v4.8.1 from versions < 4.8.0?

**Comment by ShinobiWPS** [comment]
Can't tell it, VS Code just released the Extensions Process host analyser with 1.28

I just saw that yesterday, but never realised it was so slow
