### ISSUE TITLE
Exclude folder

### ISSUE THREAD

**Issue by Gettyk** [fabiospampinato/vscode-todo-plus#136]
I have seen the file exclude option but that would be nice if we could exclude specified folders so that todo+ doesn't parse them.

**Comment by fabiospampinato** [comment]
You can also exclude folders with those options that accept a glob.

**Comment by Osmiogrzesznik** [comment]
not helpful, i am still trying to decide upon todo extension and while this one seems attractive, it's hard to find beginner friendly guide
