### ISSUE TITLE
custom color

### ISSUE THREAD

**Issue by PentiumRabbit** [fabiospampinato/vscode-todo-plus#139]
![1539863793125-image](https://user-images.githubusercontent.com/5358013/47152704-03b60c80-d310-11e8-8225-7ab2bf5d051d.png)

I want to change these colors.

**Comment by fabiospampinato** [comment]
What's "normal" supposed to mean here? A todo that's not done nor cancelled?

**Comment by fabiospampinato** [comment]
- I'm not sure why you're pointing only at the "X"s and not the whole line, but you can already replace that color with `todo.colors.cancelled`

- The "base" color comes from your theme, so you can change it by changing theme. I don't think there should be a specific setting for this provided by the extension, ti would slow down things.

**Comment by PentiumRabbit** [comment]
Not everyone likes it, just providing a choice.

**Comment by fabiospampinato** [comment]
Are you referring to the red "X" or the white todos?

**Comment by PentiumRabbit** [comment]
Not everyone likes it, just providing a choice.

**Comment by PentiumRabbit** [comment]
"X"

**Comment by PentiumRabbit** [comment]
symbols

**Comment by PentiumRabbit** [comment]
![1539868751990-image](https://user-images.githubusercontent.com/5358013/47157306-9c05be80-d31b-11e8-9168-02e0d3054c07.png)
I like this style, but I can't do it.
