### ISSUE TITLE
Format code sections with backticks (`)

### ISSUE THREAD

**Issue by yamnikov-oleg** [fabiospampinato/vscode-todo-plus#14]
Proposal to implement code sections formatting in the todo text with backticks (as in markdown).

These sections could be displayed with slightly different background color. Any other formatting features (bold and italics) inside code sections are disabled.

**Suggested use case:**

To reference or to sample source code.

```
Fix crashing on invalid user input:
  ☐ Find the reason of crashing
    Check `FormValidator`
    Line 32 `str.toLower()` does not expect null
```

**Comment by fabiospampinato** [comment]
Supported in v1.6.0.

Code blocks can be embedded pretty much anywhere. Even multi-line code blocks are supported.

Other decorators inside them are disabled, this was tricky.
