### ISSUE TITLE
Sorting by Tag

### ISSUE THREAD

**Issue by mumeiyamibito** [fabiospampinato/vscode-todo-plus#141]
I'd like to sort tasks by tag including priority such as @today and @critical.
But I cannot find the function and shortcut key.

Could you add this function?

**Comment by fabiospampinato** [comment]
It would be interesting to have a `Sort by Priority` and/or a `Sort by Due` command 🤔 

How would this work for todos nested into other todos/projects though?

**Comment by mumeiyamibito** [comment]
@fabiospampinato 

My desired way is to sort tasks tagged in projects and nests in order of priority.
The parent nest also moves according to the priority of the child task.

If possible, it would be useful to have a sorting function for only the selected area.

**Comment by marco-m** [comment]
Related: #18

**Comment by fabiospampinato** [comment]
Closing in favor of #303
