### ISSUE TITLE
Constant "Reload" label in extension

### ISSUE THREAD

**Issue by gadders** [fabiospampinato/vscode-todo-plus#142]
Installed latest version manually via vsix file. Extension constantly displays "Reload" label. Reloading does not fix. Using version 1.20.0 of VS Code.

**Comment by fabiospampinato** [comment]
What's a "reload" label? Can you attach a screenshot?

Did you download the vsix from the marketplace or did you make it yourself?

**Comment by gadders** [comment]
Sorry - attaching a screenshot is difficult as can't login to github from my work PC. What I mean is that the extension constantly displays the "Reload" button on the extension's entry in the extension panel.

I downloaded the vsix from the marketplace.

**Comment by fabiospampinato** [comment]
Oh I see, this is a problem with VSCode, nothing to do with particular extensions. You should open an issue [here](https://github.com/Microsoft/vscode/issues).
