### ISSUE TITLE
Adding robust settings options

### ISSUE THREAD

**Issue by rbenson** [fabiospampinato/vscode-todo-plus#143]
I have been playing around with changing my theme at certain times of the day, dark to light. I know you can throw `todo.colors.xxx` in to customize settings. Some settings allow you to do:

    "workbench.colorCustomizations": {
        "settingOne": "xxx",
        "settingTwo": "......",
        "[LightTheme]":{  "settingOne": "yyy"}
        "[ThemeThree]":{  "settingOne": "zzz"}
      }

is there a way to allow this level of customization for todo+?

**Comment by fabiospampinato** [comment]
This isn't possible currently via Todo+ alone, we can't provide good colors for every theme by default (https://github.com/Microsoft/vscode/issues/32813) and we can't have a custom editor/tab color (https://github.com/Microsoft/vscode/issues/35379). 

Although I don't think there's an API for detecting if the current color scheme is dark or light it looks like VSCode supports defining both dark and light colors, and then it will pick the right ones on its own 🤔 I'll add support for this (maybe tomorrow), thanks for the suggestion 👍 

If you want to do this right now it would be possible via third party extensions that change your settings. You could have some `todo.colors.*` settings, then some `alt_todo.colors.*` settings or something like that, and the extension could toggle between the two. I don't know if any such extension exists but it should be doable.

**Comment by fabiospampinato** [comment]
Implementd in v4.10.0, there are now `todo.colors.dark.*` and `todo.colors.light.*` settings.
