### ISSUE TITLE
Why tags are separated into several arrays?

### ISSUE THREAD

**Issue by usernamehw** [fabiospampinato/vscode-todo-plus#145]
actual:
```json
"todo.tags.names": [],
"todo.colors.tags.background": [],
"todo.colors.tags.foreground": [],
```
expected:
```json
"todo.tags": [{
    "name": "critical",
    "foreground": "#000",
    "background": "#fff"
}]
```

When the array gets bigger it gets harder to track which tag you're editing at the moment.

**Comment by fabiospampinato** [comment]
With the introduction of the `todo.colors.dark.*` and `todo.colors.light.*` settings it made sense to move those colors under `todo.colors.*` as well. Your proposal looks indeed nicer but it doesn't support theming those colors for dark and light themes as easily.

**Comment by usernamehw** [comment]
```json
"todo.tags": [{
    "name": "critical",
    "foreground": "#000",
    "background": "#fff",
    "lightForeground": "#fff",
    "darkForeground": "#000"
}]
```

**Comment by fabiospampinato** [comment]
What arrays with empty values? What gap? I'm not sure I'm following.

If you're proposing that code as an alternative I think having all colors under `tags.colors.*` is better.
