### ISSUE TITLE
Show embedded but only for currently opened file(s)

### ISSUE THREAD

**Issue by regoje** [fabiospampinato/vscode-todo-plus#147]
I'd like to be able to see the TODOs only in currently open files -- not entirely sure whether that's possible.

**Comment by fabiospampinato** [comment]
I think there's no API for retrieving the set of opened files 🤔 

Maybe we could automatically scroll to the section containing todos for the currently active file though, would that be interesting?

**Comment by regoje** [comment]
Yeah, it seems there isn't one, that's too bad.

Scrolling would be an improvement definitely, but perhaps then we could
show *only *the ones from the current file.

BTW just so that we're on the same page I had the list in the sidebar in
mind.

**Comment by fabiospampinato** [comment]
>  I've just looked at the code for vscode-restore-editors and they cycle through the tabs basically since this API doesn't exist and that wouldn't work here.

Yeah that doesn't work for us.

> but perhaps then we could show *only* the ones from the current file.

Definitely doable. We would have to add a new button to the toolbar or something for switching between file-level and workspace-level todos though.

> Another alternative could perhaps be to "float" the file to the top as it's opened. 

I don't think I would like to have items rearrange themselves whenever we switch file.

I say let's see what the experience will be like with just scrolling to the active file first, perhaps we could also have a small indicator in the icon to make it obvious what the current file is.

If anyone would like to work on that PRs are welcome 👍

**Comment by regoje** [comment]
Gotcha.

Do you mind pasting your ```launch.json``` here?

**Comment by fabiospampinato** [comment]
There isn't one, see https://github.com/fabiospampinato/vscode-todo-plus#contributing

**Comment by fabiospampinato** [comment]
I've implemented a button/command for displaying only embedded todos in the currently active file, so I'm closing this.
