### ISSUE TITLE
Integrate with Problems panel

### ISSUE THREAD

**Issue by borekb** [fabiospampinato/vscode-todo-plus#149]
Hi, great extension! Do you think it would be possible to integrate the list with the problems panel so that it has a standard place in the UI?

**Comment by fabiospampinato** [comment]
I'm not sure, I haven't played with the problems pane yet 🤔 

I'm not sure this is particularly useful though, what's wrong with the activity bar views?

**Comment by borekb** [comment]
Nothing wrong for sure, we just treat todos as "warnings" and the Problems panel would be a natural place for that.

**Comment by fabiospampinato** [comment]
Makes sense. I'd be happy to consider a PR that adds support for the Problems pane for embedded todos.

**Comment by fabiospampinato** [comment]
Duplicate #282
