### ISSUE TITLE
Trailing colon in a code block turns the line blue

### ISSUE THREAD

**Issue by yamnikov-oleg** [fabiospampinato/vscode-todo-plus#15]
There is a minor issue in multiline code blocks. Trailing colon converts the line into a title, which is inconvenient in Python code samples:

![Screenshot](https://i.imgur.com/gOcCgPg.png)

PS. Thank you for the feature, it's awesome :)

**Comment by fabiospampinato** [comment]
It should be pretty easy to fix, thanks for opening the issue.

**Comment by fabiospampinato** [comment]
Fixed in v1.6.1.
