### ISSUE TITLE
Text Color Projects tags

### ISSUE THREAD

**Issue by samael205** [fabiospampinato/vscode-todo-plus#150]
Hello

Could you make the text color of the @ tags be forced in the headers, so that when you use it in a header line (Ends with :), take that color?

The improvements with respect to performance have been brutal, my congratulations

**Comment by fabiospampinato** [comment]
Can you show me a screenshot of the current situation?

I'm not sure what you mean by "header", maybe "project"?

**Comment by samael205** [comment]
thats right!

**Comment by samael205** [comment]
![image](https://user-images.githubusercontent.com/649740/48908416-7021af80-ee6a-11e8-808f-e6d03e44abcc.png)

**Comment by fabiospampinato** [comment]
Can you paste in the actual text? I'd like to reproduce the same problem exactly. You can probably change the project name if that's sensitive to you.

**Comment by samael205** [comment]
TS3-125 <eXAMPLE> Textual (@ToWork, @To-Test ):

Config tags
"todo.tags.names": [
"ToWork",
"To-Test"
],
"todo.colors.tags.background": [
"#ae81ff",
"#F55A00",
],
"todo.colors.tags.foreground": [
"#FFFFFF",
"#FFFFFF"
]

**Comment by fabiospampinato** [comment]
I meant the text in the screenshot, not in your settings.
