### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by n3rio** [fabiospampinato/vscode-todo-plus#154]
- Issue Type: `Performance`
- Extension Name: `vscode-todo-plus`
- Extension Version: `4.4.3`
- OS Version: `Linux x64 4.15.0-42-generic`
- VSCode version: `1.30.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/n3rio/fabiospampinato.vscode-todo-plus-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by fabiospampinato** [comment]
> ⚠️ Make sure to attach this file from your home-directory: /home/n3rio/fabiospampinato.vscode-todo-plus-unresponsive.cpuprofile.txt ⚠️

👆

If you can share reproducible steps that would be even better.
