### ISSUE TITLE
archive indent one space

### ISSUE THREAD

**Issue by SadWood** [fabiospampinato/vscode-todo-plus#155]
I set two indents, but when I use it, it is one indentation that causes the fold.
just like this:
```
1.one
 2.two
```
but I want this:
```
1.one
  2.two
```

**Comment by fabiospampinato** [comment]
@SadWood I'm not sure what you're trying to do, feel free to reopen the issue and writing some reproducible steps that I can try on my machine to reproduce the problem. Like: 1) what settings do you have 2) what's the content of the file 3) what are you trying to do.
