### ISSUE TITLE
Rg provider fails to find embedded TODOs

### ISSUE THREAD

**Issue by jfro** [fabiospampinato/vscode-todo-plus#158]
Whenever I try `rg` provider, Todo+ reports there's no embedded TODOs found. Setting provider to `javascript` & relaunching shows embedded TODOs OK. All other settings are left as default as I only recently installed this extension.

**OS:** macOS 10.14.2
**VSCode:** 1.30.1
**Todo+:** 4.11.2
**rg:** 0.10.0 (installed via brew)

Let me know if there's more information I can provide.

**Comment by fabiospampinato** [comment]
By default the best provider available is found automatically, is `rg` actually in your PATH? 🤔

**Comment by jfro** [comment]
Yup.
```jerome@Tak ~/P/rust-dnssd (master)> echo $PATH
/Users/jerome/.cargo/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin
jerome@Tak ~/P/rust-dnssd (master)> which rg
/usr/local/bin/rg
jerome@Tak ~/P/rust-dnssd (master)>
```
Should I be able to paste the default rg regex into terminal as one of rg's arguments? Because that does produce an error. "error: repetition operator missing expression"

**Comment by fabiospampinato** [comment]
@jfro the command is being generated here: https://github.com/fabiospampinato/vscode-todo-plus/blob/master/src/utils/embedded/providers/rg.ts/#L18-L19

You may try dumping that and see if you can run that from the terminal and if not what the problem is. I'm sorry I can't be more helpful right now but it's a very busy period for me.

**Comment by jfro** [comment]
OK does look like something maybe changed in rg to cause the existing regex to be invalid?

```
Error: Command failed: rg --color never --with-filename --pretty --ignore-case (?:#|//|/\*+|<!--|--|\* @|{!|{{!--|{{!) *(TODO|FIXME|FIX|BUG|UGLY|HACK|NOTE|IDEA|REVIEW|DEBUG|OPTIMIZE) /Users/jerome/Projects/rust-dnssd
extension.js:95268
regex parse error:
    (?:#|//|/\*+|<!--|--|\* @|{!|{{!--|{{!) *(TODO|FIXME|FIX|BUG|UGLY|HACK|NOTE|IDEA|REVIEW|DEBUG|OPTIMIZE)
                              ^
error: repetition operator missing expression
```

**Comment by fabiospampinato** [comment]
@jfro I think you should put the regex in single quotes first.

**Comment by jfro** [comment]
I believe execa module probably is doing that? If I manually run it, with single quotes, I get same error as pasted above. Without quotes would yield a shell error for sure.

**Comment by fabiospampinato** [comment]
> I believe execa module probably is doing that?

Yes, I mean you want to run the command directly from your shell in order to see what the error returned by `rg` is you have to quote it manually.

**Comment by jfro** [comment]
Yeah I did, same error as above when run in my shell, rg doesn't seem to like the default regex.

**Comment by jfro** [comment]
This seems to work, having to escape the {, they seem to be literals in this case?

`rg --color never --with-filename --pretty --ignore-case '(?:#|//|/\*+|<!--|--|\* @|\{!|\{\{!--|\{\{!) *(TODO|FIXME|FIX|BUG|UGLY|HACK|NOTE|IDEA|REVIEW|DEBUG|OPTIMIZE)'`

**Comment by fabiospampinato** [comment]
@jfro in v4.11.4 those curly braces should be properly escaped, let me know if this fixed the problem for you.
