### ISSUE TITLE
@created has purple background when critical and/or high tags removed

### ISSUE THREAD

**Issue by FletcherCodes** [fabiospampinato/vscode-todo-plus#159]
When I customise "todo.tags.names" and remove "critical" and/or "high", the @created tag changes from yellow text to a purple background.

I did have Solarized Dark but, even when removing the theme, the same thing happens.

# With Critical and High

![image](https://i.gyazo.com/7fb3a0a24a389442c3bb8b7119661b27.png)

![image](https://i.gyazo.com/cd1bd94d2dc1c5de03ff11b927a3ae4b.png)

---

# Without Critical and/or High

![image](https://i.gyazo.com/533bdd8f1e7044f008d55118baf39dbf.png)

![image](https://i.gyazo.com/abd1b08fc35f5c88ebe5e96eac8b008a.png)

**Comment by fabiospampinato** [comment]
@FletcherCodes weird, does the error persist if you reload VSC?

**Comment by FletcherCodes** [comment]
🤦‍♂️Should have tried that. Just ran "Reload Window", and the error doesn't persist.
