### ISSUE TITLE
Single backticks inside multiline code blocks revert the block formatting

### ISSUE THREAD

**Issue by yamnikov-oleg** [fabiospampinato/vscode-todo-plus#16]
Text enclosed in singular backticks inside a code block is colored gray, but probably shouldn't.

![Screenshot](https://i.imgur.com/IU3XObo.png)

**Comment by fabiospampinato** [comment]
That's happening because triple backticks aren't technically supported, the text in the screenshot contains 4 code blocks according to how it gets parsed.

I'm going to fix this by explicitly supporting triple backticks, thanks for reporting the issue.

**Comment by yamnikov-oleg** [comment]
@fabiospampinato Oh, I thought it's a special feature. My bad :)

**Comment by fabiospampinato** [comment]
Fixed in v1.6.1.
