### ISSUE TITLE
[Suggestion] Add support for @created and @due

### ISSUE THREAD

**Issue by Supportic** [fabiospampinato/vscode-todo-plus#160]
Hey, I'm loving to use this extension. I would like to suggest to more features though:

1. Add support for a @created TAG to insert the current timestamp for the created task to be able to see how long this task already exists
2. Add support for a @ due TAG to mark a specific date when the task has to be finished (by clicking on @ due the missing days until the deadline will appear) (ref: https://github.com/fabiospampinato/vscode-todo-plus/issues/23)

Best regards :)

**Comment by fabiospampinato** [comment]
Thanks!

> Add support for a `@created` TAG to insert the current timestamp for the created task to be able to see how long this task already exists

Already supported, you have to enable the `todo.timekeeping.created.enabled` setting.

> Add support for a @ due TAG

As you mentioned this is already tracked in a separate issue.
