### ISSUE TITLE
Add option to choose regex group numbers

### ISSUE THREAD

**Issue by rodrigoccurvo** [fabiospampinato/vscode-todo-plus#161]
Todo+ extension uses groups 1 and 2 of the regex for type and description, respectively. Because of that, anything else has to be made using lookahead, to avoid using the wrong group. On the other hand, the Highlight extension doesn't seem to work well with lookahead (my guess is because of position calculations), nor with subgroups. 

That makes it challenging to use complex regexes that work for both Todo+ and Highlight, since copying from one to the other will not always work.

Although solving Highlight limitations might be difficult depending on how it's implemented, I believe that the issue could be greatly reduced if Todo+ had an option to choose which group numbers would be used as type and description (instead of always using groups 1 and 2). That way, the need for lookahead would be greatly diminished, and the regex more easily ported to use with Highlight.

Another good option would be named groups, but I'm not sure about the compatibility with different regex processors.

**Comment by fabiospampinato** [comment]
I'm not sure what the issue here is: you can't use capturing groups `(foo)` before the first two because they have special meaning for the extension, but why not using _non capturing_ groups `(?:foo)`?

>  the Highlight extension doesn't seem to work well with lookahead (my guess is because of position calculations), 

Can you provide the configuration for Highlight that causes problems? Perhaps open an issue about this in its repo.

> nor with subgroups.

As the readme says, they are not supported at all:

> Note: Nested capturing groups are not supported.

I'm not sure how/if this could be fixed.

**Comment by fabiospampinato** [comment]
Also why are you writing your own regex? Is your use case something general enough that we could support by default?

The default regex is quite complicated and supports a lot of cases already.

**Comment by rodrigoccurvo** [comment]
The main issue is that I can't just copy a regex from Todo+ to Highlight and vice-versa, because it won't work. For example, take this simple regex:

"(TODO)(?::)(.*)"

It will work on Todo+, but if I copy to Highlight, it will miss the last char. My guess is that it's because of non-matching groups affect Highlight's way of calculating positions.

Maybe this could be fixed in Highlight. But because Highligh requires every char to be in a group, I don't know how it would work with non-matching groups. So I think it's easier to solve it from Todo+, since the simpler version (with only matching groups) works on Highligh:

"(TODO)(:)(.*)"

But it won't work on Todo+ because of the numbering of the groups. Besides, in the complex cases (like the default one), the regex is much cleaner without the non-matching groups.

As for your second question, I'm writing my own regex because I want my TODO's to have a particular format.

In any case, I can close this one and open an issue in Highlight if you think it's better.

**Comment by rodrigoccurvo** [comment]
Oh, I see. So Highlight works with subgroups as long as it's not capturing subgroups.

I'm not well versed in TS, but if I end up learning it I'll see if I can come up with a solution.

In any case, thanks for your time and for the extensions.
