### ISSUE TITLE
Refresh  Embedded?

### ISSUE THREAD

**Issue by dwfmarchant** [fabiospampinato/vscode-todo-plus#163]
I'm trying to figure out how to refresh the list of Embedded todo's.  The only way I can get it to work is change the option in Todo > Embedded: Provider (or exit and restart vs code).  I'm running Todo+ v4.11.4 on macOS.

**Comment by fabiospampinato** [comment]
It should refresh automatically, can you make a gif or something of the steps necessary to reproduce the problem?

**Comment by dwfmarchant** [comment]
Thanks for the quick response - actually it looks as though it is working fine for some projects and not for others.  Still working on coming up with a minimal example that reproduces the behavior.

**Comment by aNickzz** [comment]
I'm also having this trouble. The only way to refresh the list is to edit my user settings or reload vscode.
This happens regardless of which project I've got open.

**Comment by dwfmarchant** [comment]
I'm still trying to come up with a simple example of this.  Works great for some of my projects and doesn't for others...

**Comment by dwfmarchant** [comment]
Actually it does seem to be working for me now and I can't reproduce the problem.  Will close for now.
