### ISSUE TITLE
Accept TODOs that start with @

### ISSUE THREAD

**Issue by nikitavoloboev** [fabiospampinato/vscode-todo-plus#165]
The codebase I am working on has TODOs that start with `@` like:

```
// @TODO Fix this
```

Extension doesn't catch those currently. Would be nice if it did.

**Comment by nikitavoloboev** [comment]
Also @TODO is JSDoc default: https://github.com/fabiospampinato/vscode-todo-plus/issues/165

**Comment by fabiospampinato** [comment]
> Also @TODO is JSDoc default: http://usejsdoc.org/tags-todo.html

This is actually kind of already supported:

1. I think JSDoc-style todos should be written as:

```js
/**
 * @todo: foo
 */
```

2. You can edit the regexes used by Todo+ yourself to support any kind of syntax you like.

But I guess single-line jsdoc-ish todos should be supported by default, thanks for the suggestion!

**Comment by mtxr** [comment]
@fabiospampinato 

```js
/**
 * @todo: foo
 */
```

Is not working for me.

I've made no change except defining RG as a provider.

I use ripgrep for almost everything on my machine, so the path is ok.

Any ideas?

**Comment by mtxr** [comment]
Also if I switch to //todo: it shows, but duplicate

![image](https://user-images.githubusercontent.com/707561/54965155-03b8d900-4f4e-11e9-969b-ab12032516f6.png)

**Comment by fabiospampinato** [comment]
@mtxr Strange 🤔 I can't reproduce this. What OS and VSC version are you on? Did you change any other todo+ settings?

**Comment by mtxr** [comment]
Insiders 1.33, Linux fedora 29

I got it running chaning the regex to:
```json
    "todo.embedded.provider": "rg",
    "todo.embedded.providers.rg.regex": "(?:#|// +@|//|/\\*+|<!--|--|\\* @|\\{!|\\{\\{!--|\\{\\{!) *(DEPRECATED|TODO|FIXME|FIX|BUG|UGLY|HACK|NOTE|IDEA|REVIEW|DEBUG|OPTIMIZE)",
    "todo.embedded.regex": "(?:<!-- *)?(?:#|// +@|//|/\\*+|<!--|--|\\* @|\\{!|\\{\\{!--|\\{\\{!) *(DEPRECATED|TODO|FIXME|FIX|BUG|UGLY|HACK|NOTE|IDEA|REVIEW|DEBUG|OPTIMIZE)(?:\\s*\\([^)]+\\))?:?(?!\\w)(?: *-->| *\\*/| *!}| *--}}| *}}|(?= *(?:[^:]//|/\\*+|<!--|@|--|\\{!|\\{\\{!--|\\{\\{!))|((?: +[^\\n@]*?)(?= *(?:[^:]//|/\\*+|<!--|@|--(?!>)|\\{!|\\{\\{!--|\\{\\{!))|(?: +[^@\\n]+)?))"
```
> add DEPRECATED
> add // +@ if highest precendence

But still duplicate

**Comment by mtxr** [comment]
My todos:
https://github.com/search?q=todo+repo%3Amtxr%2Fvscode-sqltools&type=Code
https://github.com/search?q=deprecated+repo%3Amtxr%2Fvscode-sqltools&type=Code

This is everything I want to highight.

**Comment by fabiospampinato** [comment]
Just fixed this.

Btw the regexes used for finding todos are customizable (although they aren't easy regexes to read), check out the following settings:

- `todo.embedded.regex`
- `todo.embedded.providers.ag.regex`
- `todo.embedded.providers.rg.regex`
