### ISSUE TITLE
Support Todos with alternative box: - [ ]

### ISSUE THREAD

**Issue by mschmid** [fabiospampinato/vscode-todo-plus#166]
Hi, i really like Todo+!
I tried to change the Todo-Box-String from default to `- [ ]`, to be compatible with Githubs markdown syntax for todos.
But then toggling done doesn't work as expected, it generates `- [x] [ ]` instead of `- [x]`.
Is there a reason, that markdown syntax is not supported?

**Comment by fabiospampinato** [comment]
> Is there a reason, that markdown syntax is not supported?

Mostly it isn't supported because it wasn't supported by [PlainTasks](https://github.com/aziz/PlainTasks). And we already support writing todos as `- foo`. And there's no concept of a cancelled todo in markdown, what should that look like, `- [-]` maybe? Weird.

Is there any reason why you'd like to use Markdown's syntax? 🤔 I have a much more limited [extension](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-markdown-todo) that gives you those shortcuts for creating todos inside Markdown documents.

**Comment by mschmid** [comment]
Wow that was fast. To be honest, I am currently searching for the best way to organize myself across projects. I like the open file format of Todo+ and Markdown in contrast to proprietary tools. And I also like a nice rendering like for example in Notable.
If Notable could extract all todos from the notes this would be perfect - I thought I could configure Todo+ to accomplish this.

**Comment by fabiospampinato** [comment]
@mschmid The two aren't really meant to be interoperable.

I'm closing this as supporting the Markdown syntax seems out of scope.

**Comment by v-iashin** [comment]
I tried the extension today and it is quite nice! 

However, as the topic starter, I would also be happy to see the `.md` support or enhancement with todo+ features like (times, parsing code for TODO, timers). With this, we could get closer to the org-mode.

@fabiospampinato 👋 Why does it go against the scope?

**Comment by fabiospampinato** [comment]
> @fabiospampinato 👋 Why does it go against the scope?

Because I'm not interested in doing that with this extension.

**Comment by v-iashin** [comment]
Fair point! I see. 

If this request is reformulated from "support markdown" to "support `- [ ]`-based toggles", will it be within the scope?

https://user-images.githubusercontent.com/14952597/154551033-2744afcd-c800-4359-a1a6-13f4da65114f.mov

**Comment by v-iashin** [comment]
Well, it again comes down to md and its wide support beyond just local notes. 

With this fix, one could turn on the todo language on a .md file and have TODO+ annotation for it. It has several benefits eg support the rendering on Github as the issue starter suggested and the ecosystem of other extensions for it.

**Comment by fabiospampinato** [comment]
I guess that could be useful 🤔 Although one can't just enrich Markdown documents with this extension, by enabling this extension in them the whole file would be syntax highlighted differently.

There's an added complication in implementing this, currently no allowed symbol starts with any other allowed symbol, but `-` is already an allowed symbol for `box` so this assumption would break and various parts of the extension would need to be changed. IMO it's not worth working on this, but if somebody has the time I'd be open to consider merging a PR that properly adds support for `- [ ]`, `- [x]`, - [X]` and `- [-]`.

**Comment by v-iashin** [comment]
One possibility is to use * instead of -

* [ ] abs
```
* [ ] abs
```

**Comment by fabiospampinato** [comment]
Potentially 🤔 but the appeal of that decreases significantly, I think most people use `-` for lists in Markdown.
