### ISSUE TITLE
How can I enable time till completion on tasks with a due date?

### ISSUE THREAD

**Issue by foundationalnotes** [fabiospampinato/vscode-todo-plus#167]
How can I enable time till completion on tasks with a due date? (I promise I looked through the settings but am not sure which would apply)

For example:

Major task item due @due(02-13-19)

Under or beside this item I would like to see "33 days remaining" or something similar.

_Originally posted by @foundationalnotes in https://github.com/fabiospampinato/vscode-todo-plus/issues/61#issuecomment-461121662_

**Comment by fabiospampinato** [comment]
@foundationalnotes the `@due` tag isn't supported yet. https://github.com/fabiospampinato/vscode-todo-plus/issues/23
