### ISSUE TITLE
Badges for Custom Embeded Hits

### ISSUE THREAD

**Issue by Astrantia** [fabiospampinato/vscode-todo-plus#168]
Is there a way to add these badges for new custom regex matches?
![image](https://user-images.githubusercontent.com/32885386/52391260-5e63a780-2a6a-11e9-9d79-c8085ad3c925.png)

**Comment by fabiospampinato** [comment]
@Astrantia yes, first you have to update the regex used, then you have to set a specific color for your match via the `todo.colors.types` setting.

The regex can't be totally custom though, the first capturing group is supposed to capture the "type" of the comment.
