### ISSUE TITLE
Archive project can't be folded in the activity bar

### ISSUE THREAD

**Issue by dpajkovic** [fabiospampinato/vscode-todo-plus#169]
After the tasks are archived, they appear in the activity bar underneath the entry Archive:, as expected, however this entry can't be folded to hide the archived tasks - there is no triangle arrow next to it.

Versions:
VSCode 1.31
Todo+ 4.11.4
running on Windows 7 (if that matters)

**Comment by fabiospampinato** [comment]
@dpajkovic sounds like a problem with vscode maybe, my archive is foldable:

<img width="185" alt="screen shot 2019-02-07 at 13 54 55" src="https://user-images.githubusercontent.com/1812093/52412768-05cef180-2ae0-11e9-988f-487afdc49a08.png">

Can you post a screenshot?

**Comment by dpajkovic** [comment]
![2019-02-07 13_57_46](https://user-images.githubusercontent.com/25065850/52413403-cdc8ae00-2ae1-11e9-97e6-4e3caf5654bd.png)

The issue is not in the file view, but in the sidebar. 

Sorry for having to obsfucate the file, but I hope you get the idea from this.

**Comment by fabiospampinato** [comment]
I see here 2 different indentations, see how the todos inside the archive are less indented? That's the problem I think. You should update the `todo.indentation` setting and update the indentation of the todos inside the archive..
