### ISSUE TITLE
How to modify and add custom TODO filename?

### ISSUE THREAD

**Issue by Makogan** [fabiospampinato/vscode-todo-plus#17]
I was wondering if it is possible to have sutom TODO file names. Mainly because I want an independent TODO filename for each version of my project for log pouposes.

**Comment by yamnikov-oleg** [comment]
@Makogan Just create files with `.todo` extension. E.g. `version1.todo`, `version2.todo`.

**Comment by fabiospampinato** [comment]
@Makogan you can change the default name via the `todo.file` setting. You can have multiple todo files, just ensure they have a `.todo`, `.todos`, `.task` or `.tasks` extension. Alternatively, you can edit a file named whatever you want, just be sure to set its language to `Todo`.
