### ISSUE TITLE
Embedded view: sort tasks alphabetically

### ISSUE THREAD

**Issue by Astrantia** [fabiospampinato/vscode-todo-plus#170]
I have embed todos of the form // number 1, // number 2, …
They result in the following display:
![image](https://user-images.githubusercontent.com/32885386/52458093-591a6180-2b2b-11e9-9f4f-0c29b207c0a2.png)

I think it sorts by the code line number. Is it possible to sort them alphanumerically?

**Comment by fabiospampinato** [comment]
Not possible right now. I'd be happy to consider a PR for adding an option for doing this.
