### ISSUE TITLE
Add shortcut to turn item into category

### ISSUE THREAD

**Issue by pzmarzly** [fabiospampinato/vscode-todo-plus#171]
`<|>` indicates cursor position

```text
☐ test<|>
    ☐ more testing
```

After `Alt-C`:

```text
test:<|>
    ☐ more testing
```

So, such shortcut should run `Toggle Box` and add/remove colon at the end of the line.

**Comment by fabiospampinato** [comment]
I don't think we need such shortcut, just toggle the todo and press `:`. If you really want to save the extra keypress you can make such shortcut yourself with [macros](https://marketplace.visualstudio.com/items?itemName=geddski.macros).
