### ISSUE TITLE
Exclude not working

### ISSUE THREAD

**Issue by MKlblangenois** [fabiospampinato/vscode-todo-plus#173]
Hi!

I've tried many way to exclude path from Todo but no one's working.

My goal is the exclude WordPress core and plugins to my Todo view.

I've already tried the default exemple : 
`"todo.file.exclude": [
        "**/.!(todo|todos|task|tasks)/**"
    ]`

Thanks

**Comment by fabiospampinato** [comment]
@MKlblangenois Can you make a public repo where I can reproduce the issue?

**Comment by MKlblangenois** [comment]
> @MKlblangenois Can you make a public repo where I can reproduce the issue?

I've added you to my private repo as collaborator (Zeract)

My settings.json
`{
    "workbench.colorTheme": "Material Theme High Contrast",
    "workbench.iconTheme": "vscode-icons",
    "window.zoomLevel": 0,
    "editor.fontFamily": "\"Fira Code\", Consolas, 'Courier New', monospace",
    "editor.fontLigatures": true,
    "terminal.integrated.fontFamily": "monospace",
    "editor.fontSize": 16,
    "emmet.triggerExpansionOnTab": true,
    "workbench.startupEditor": "welcomePage",
    "editor.wordWrap": "on",
    "breadcrumbs.enabled": true,
    "todo.file.exclude": [
        "**/wp-admin/**",
        "**/wp-content/**"
    ]
}`

**Comment by fabiospampinato** [comment]
I see no files in the "file" view already, but you can exclude them with the following:

```
"todo.file.exclude": [ "**/wp-admin/**", "**/wp-content/**" ],
```

If you also don't want to see todos in the "embedded" view from those folders, add the following:

```
"todo.embedded.exclude": [ "**/wp-admin/**", "**/wp-content/**" ],
```
