### ISSUE TITLE
"Running the contributed command:'task.complete' failed." when completing a task

### ISSUE THREAD

**Issue by JohnArcher** [fabiospampinato/vscode-todo-plus#175]
Hey there!

I am not sure when this problem started but everytime I press Alt+D to complete a task I get the error `Running the contributed command:'task.complete' failed.` and the task is not marked as completed.

![image](https://user-images.githubusercontent.com/990724/53169757-6da43280-35de-11e9-969d-e509c94e7c48.png)

When I use the "Show Fixes" light bulb and click on "Complete the task" nothing happens (not even the error message).

Todo+ version: 4.11.4
VSCode version: 1.31.1
Plattform: Windows

**Comment by fabiospampinato** [comment]
We aren't contributing any command named `task.complete`, nor any lightbulb actions, you most probably have another extension conflicting with this.

**Comment by JohnArcher** [comment]
Oh, I am sorry, you are right. The extension "To Do Tasks" caused this problem, which I had accidentally enabled. Of course it is silly to have to of such extensions, but in the past there was no error, so I didn't realize I had both.
So, thanks for the help and sorry for the trouble.
