### ISSUE TITLE
Setting for including @done tasks in estimates

### ISSUE THREAD

**Issue by douglance** [fabiospampinato/vscode-todo-plus#176]
It'd be great to have a boolean flag for excluding @done tasks from your [est] statistics. That way, if it were `false`, then I could compare my estimates to actuals and see how well I am estimating.

**Comment by fabiospampinato** [comment]
I'm not sure if I'm understanding this right, from what I can see there's nothing to implement here.

`@est` tags of done tasks are not counted for the `[est]` token already.

And you can already compare how long it actually took to complete a task with your estimate, but there's still no way to toggle the "started" timer yet https://github.com/fabiospampinato/vscode-todo-plus/issues/88 so those numbers won't be accurate if for instance you work on a task for multiple days.

![foo](https://user-images.githubusercontent.com/1812093/53345869-66e72980-3916-11e9-9b15-fa696c04f675.gif)

**Comment by fabiospampinato** [comment]
Also you can actually see a small bug in my gif, it says 45 seconds have passed but that's not true. That's happening because we are not storing the seconds in the `@started` tag, but if that's important to you you can change the format used to include seconds and get a bit more accurate estimates.

**Comment by douglance** [comment]
@fabiospampinato I figured out what the issue was. If I type in my `@lasted` then trigger the `@done` it erases my `@lasted` and adds `@done`. That isn't the behavior I was expected.

**Comment by fabiospampinato** [comment]
What do you mean with "if I type in my `@lasted`", were you editing it? adding it manually?

**Comment by douglance** [comment]
Yes. I was adding it manually because I don't always remember to start a timer, or I'm working on something else and I get a task done; so I just type it in since I can't start a timer after it's already complete.

**Comment by fabiospampinato** [comment]
If you add that manually it should work too, after all the extension itself has no way of knowing if the tag has been added manually or not, but it must be written in the right format.

**Comment by douglance** [comment]
Right. It works great. The issue is that I have to write @lasted _after_ I trigger `@done ` or else the done command will erase my manually written `@lasted`.
