### ISSUE TITLE
Counter.todo

### ISSUE THREAD

**Issue by ulvido** [fabiospampinato/vscode-todo-plus#177]
if the file name is Counter.todo it doesn't show todos.

![2019-02-25 16-57-18 ekran goruntusu](https://user-images.githubusercontent.com/27722274/53342557-1f58a180-3906-11e9-92d3-4a45efd8a2a0.png)

**Comment by fabiospampinato** [comment]
Sorry I must have missed this issue. Your indentation doesn't look quite right, you're using 4 spaces but the settings for Todo+ (unless you've changed them) say that you should be using 2 spaces, update the related setting: `todo.indentation`.
