### ISSUE TITLE
guide

### ISSUE THREAD

**Issue by blondie63** [fabiospampinato/vscode-todo-plus#180]
Hi Fabio, is there a guide to use todo-plus ?

**Comment by fabiospampinato** [comment]
Hey, there's a small kind of tutorial [here](https://github.com/fabiospampinato/vscode-todo-plus#example-todo-file), other than that I guess just play with the provided commands and settings. Let me know if there's anything that's unclear.

**Comment by blondie63** [comment]
Ok thanks, reading better, now i understand..
