### ISSUE TITLE
Newbie Question regarding this and Markdown

### ISSUE THREAD

**Issue by jeff9315** [fabiospampinato/vscode-todo-plus#181]
I have a lot of markdown files that contain To Do items ... all with the extension _.md_ I was hoping I would be able to use those with ToDo-Plus. But it doesn't look like this is meant to be used with Markdown files. Am I correct in that? I'm already trying Notable.

Thanks ... Jeff

**Comment by fabiospampinato** [comment]
Yeah this doesn't support markdown files. I have [another](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-markdown-todo) extension that adds a few shortcuts for use within Markdown.
