### ISSUE TITLE
Setting

### ISSUE THREAD

**Issue by OsvaldoMartini** [fabiospampinato/vscode-todo-plus#182]

**Comment by OsvaldoMartini** [comment]
Hi, I'm testing ALL +, how do I change the settings, as I just want to filter specific tag like "ALL" or "FIXME", I just want to detect ie "TODO-MARTINI"

**Comment by fabiospampinato** [comment]
I'm not exactly sure what you mean here, if you're talking about embedded todos you can configure that via the `todo.embedded.regex` setting.
