### ISSUE TITLE
Switch to the new Tree component

### ISSUE THREAD

**Issue by nikitavoloboev** [fabiospampinato/vscode-todo-plus#183]
It would be nice if you could start typing characters and jump to corresponding TODOs in active Embedded View. So if in below view I would start typing `ge`:

![2019-04-03 at 14 50](https://user-images.githubusercontent.com/6391776/55480119-d809b300-561f-11e9-807c-2a927fc887f5.png)

It would jump focus to the item(s) starting with `ge`:

![2019-04-03 at 14 50](https://user-images.githubusercontent.com/6391776/55480151-e952bf80-561f-11e9-98e7-09ebed37833b.png)

This is common in macOS inputs. 

If this is not possible, there should be some other way to search within that embedded view to filter through TODOs.

**Comment by fabiospampinato** [comment]
The specific behavior you want (focusing to the element) I don't think can be implemented.

But filtering is already implemented this way:

![hjb](https://user-images.githubusercontent.com/1812093/55487574-a5b38200-562e-11e9-967c-b08895750f47.gif)

And I think the VSC team added a new Tree component that when used gives kind of the sort of filtering that you want:

![kjjkn](https://user-images.githubusercontent.com/1812093/55487605-b663f800-562e-11e9-9265-f2dafc84e7a8.gif)

But we aren't using the new Tree component yet so you don't have this.

**Comment by nikitavoloboev** [comment]
> filtering is already implemented this way

How do I access this panel from keyboard?




> we aren't using the new Tree component yet

Would love to see it added. Can look into it myself. 🙂

**Comment by fabiospampinato** [comment]
> How do I access this panel from keyboard?

Not possible right now, but it sounds like a nice addition, I'd be happy to consider a PR adding the following 2 commands:

- `Todo: Filter Embedded View`
- `Todo: Clear Filter Embedded View`

> Would love to see it added. Can look into it myself. 🙂

I'd be happy to consider a PR for this too, if you'd like to implement it I guess [this](https://github.com/fabiospampinato/vscode-todo-plus/blob/master/src%2Fviews%2Fview.ts) is the file that would need to be updated.

**Comment by marco-m** [comment]
Related (I think): #172

**Comment by fabiospampinato** [comment]
@nikitavoloboev It looks like your original proposal has been implemented by the new vscode version, once the embedded view is focused you can highlight and filter todos by keywords "natively".

I'm implementing the extra commands I proposed right now.

**Comment by fabiospampinato** [comment]
Just implement the commands too.

> How do I access this panel from keyboard?

Actually you could already do that, all toolbar buttons can be triggered by a shortcut because they in turn just trigger a command, simply assign a shortcut to that command.

The list of all provided commands should be listed in the "Contributions" page of each extension.
