### ISSUE TITLE
@file:///current root path?/

### ISSUE THREAD

**Issue by klukiyan** [fabiospampinato/vscode-todo-plus#184]
The extension can generatate the `@file://xx/xx/x.x` links to files and lines, however these are having disk drive as root D

Is it possible to make same links to use PROJECT FILE as root?
`@file:///current root path?/`

Instead of `@file:///d%3A/laragon/www/xxx/resources/views/layouts/front/xxx.blade.php`
to use `@file:///resources/views/layouts/front/xxx.blade.php`

**Comment by fabiospampinato** [comment]
I don't think you can use relative filenames with the `file://` protocol, but even if you could then if/when you save the file somewhere else all those links will be broken, so I don't think this is a good idea.

**Comment by klukiyan** [comment]
@fabiospampinato ,
if the links were relative to rootfolder, then they would work accross multiple computers.
With absolute links I get exactly the oposite!
On one computer the folder is in `C:/laragon`, on another is in `D:/laragon`
Thus if I save the filepath into ToDo on one computer, on the other they don't work anymore.
This stops me from using full potential of ToDo+ :(

**Comment by fabiospampinato** [comment]
🤔 I see the problem, are you saving the file for any particular reason instead of regenerating it every time?

**Comment by klukiyan** [comment]
I'm writing the big *.todo lists (in one file or multiple if big sets of project tasks) and they mainly contain my handwritten notes. Additionally I'm writing paths to file and lines in the files with or without ToDo tags in them to remind myself which files I worked on for particular development set. 

Regenerating the generate functionality I don't use much because they don't show the relation between filesets and development projects/branches. So I use the *.todo files and want to be able to link files in them

**Comment by fabiospampinato** [comment]
Ok, I'm not sure sure there's anything Todo+ specifically can do for this scenario, I just don't think the `file://` protocol supports relative paths. 

I guess what you want is an extension which enhances some special syntax for this, so that basically something like `relfile://./foo.js` gets highlighted and you ctrl+click it like you can do with other URLs, and I think this is out of scope with what Todo+ provides.

**Comment by klukiyan** [comment]
Thank you for your kind and detailed explanation.
And for the amazing extension. I use it in all my projects
