### ISSUE TITLE
Global todos instead of workspace specific todos

### ISSUE THREAD

**Issue by pavkum** [fabiospampinato/vscode-todo-plus#188]
Hello,

First of all, thank you for the awesome extension. I was wondering if there is a to put all todo in a global location (like in a dropbox folder) instead of workspace specific files/folders.

Thank you.

**Comment by fabiospampinato** [comment]
Hey, I think this is kind of supported already, check [this](https://github.com/fabiospampinato/vscode-todo-plus/issues/78) and [this](https://github.com/fabiospampinato/vscode-todo-plus/issues/140).

**Comment by pavkum** [comment]
Hi,
Thanks for the response. I tried that setting already but it didn't seem to work. I may have done some mistake. Let me have a look. 
Regards, 
Pavan
