### ISSUE TITLE
Filter by path

### ISSUE THREAD

**Issue by MrCreosote** [fabiospampinato/vscode-todo-plus#190]
Hi,

I just started using TD+ for embedded TODOs and it seems pretty great so far, thanks.

My workspace has several go modules in it and so I was wondering if there's a way to filter the embedded TODO pane by go module/ folder path / something like that, as the entire list is hard to navigate if I only care about one of the modules. My apologies if it's in the documentation and I missed it.

**Comment by fabiospampinato** [comment]
Filtering by go module sounds overly specific. We should enable filtering by path, it isn't possible currently, we would have to add a check for this [here](https://github.com/fabiospampinato/vscode-todo-plus/blob/fb764a46040b72b8aa093977e1fc9e34c28a6e29/src/utils/embedded/providers/abstract.ts#L143-L144)

**Comment by Wolfonye** [comment]
That would be much appreciated! May I add that I personally would find it desirable to be able to fixate the folders to be included depending on the workspace like it is possible for the project-wide search and replace menu, which I found to be incredibly useful in the past.

**Comment by fabiospampinato** [comment]
> May I add that I personally would find it desirable to be able to fixate the folders to be included depending on the workspace like it is possible for the project-wide search and replace menu, which I found to be incredibly useful in the past.

I think you can achieve that already by setting the `todo.embedded.exclude` setting.

**Comment by Wolfonye** [comment]
Shame on me! I didn't see that option before; I apologize!

**Comment by fabiospampinato** [comment]
No worries, we have lots of options :)

**Comment by fabiospampinato** [comment]
I just implemented this, wait for the next release to try it out.
