### ISSUE TITLE
Bug?: Question on @est and @lasted

### ISSUE THREAD

**Issue by sahil48** [fabiospampinato/vscode-todo-plus#195]
It seems that when I add a `@lasted`  tag to tasks with an `@est` tag preceding it, both items get added to the time for a project. Should it not favor `@lasted` tag over `@est` when making this calculation?

**Comment by sahil48** [comment]
Similarly, can tasks with start and done times infer the time the task lasted, add it to the tag statistics, and take precedence over `@lasted` and `@est` tags?

**Comment by fabiospampinato** [comment]
> It seems that when I add a @lasted tag to tasks with an @est tag preceding it, both items get added to the time for a project. Should it not favor @lasted tag over @est when making this calculation?

@sahil48 can you share a file that reproduces the issue?

> Similarly, can tasks with both start and done times infer the time the task lasted, add it to the tag statistics, and take precedence over @lasted and @est tags (for calculation of the tag statistics)?

I don't think it should take precedence over `@lasted`, and those shouldn't generally be really different, unless you are editing them manually for some reason.

**Comment by est** [comment]
Do you have a question for me?

I am @est btw.
