### ISSUE TITLE
[Question] Hide timestamps, change line color

### ISSUE THREAD

**Issue by claudiojrt** [fabiospampinato/vscode-todo-plus#197]
Hi, I'm using this extention to manage my todo list at work, and I don't need the timestamps for started, done, etc.

What I really need is a way to highlight a full line (like when it's done or cancelled) when I start a todo, with some color other than the normal, and maybe changing the icon to be like a square with a dot inside, or anything different than the normal square.

Is there a way to hide the timestamps and highlight the "started" items?

**Comment by claudiojrt** [comment]
Hey, I just found a way to hide the @done/@cancelled labels and timestamps, but I didn't found a way to hide the @started tag.

**Comment by Pnoexz** [comment]
@claudiojrt would you mind sharing how to hide timestamps for **done** and **cancelled**?

**Comment by claudiojrt** [comment]
@Pnoexz File > Preferences > Settings > Extensions > Todo - Configuration > Insert the time inside the @done/cancelled tag

**Comment by Pnoexz** [comment]
@claudiojrt Thanks! while looking for those settings I also found the one for the **started** tag, if you can't find it in the settings, this is the json config:

```
  "todo.timekeeping.elapsed.enabled": false,
  "todo.timekeeping.created.time": false,
  "todo.timekeeping.finished.enabled": false,
  "todo.timekeeping.finished.time": false,
  "todo.timekeeping.started.time": false
```

In the UI config, it's the last item in this screenshot: 
![image](https://user-images.githubusercontent.com/3297901/57623573-63069300-7566-11e9-9f13-f3bb7b040eab.png)

**Comment by claudiojrt** [comment]
@Pnoexz Yes, there is a way to hide the @done/cancelled tag and timestamp, but there's no way to hide the @started tag specifically, only the timestamp.

**Comment by fabiospampinato** [comment]
> Is there a way to hide the timestamps 

as @Pnoexz noted those tags can be disabled by setting the following options to `false`:

```js
  "todo.timekeeping.created.enabled": false, // Enable the @created tag
  "todo.timekeeping.finished.enabled": true, // Enable the @done/cancelled tag. It's always enabled if you explicitly start a todo or if you use only 1 symbol
  "todo.timekeeping.elapsed.enabled": true, // Enable the @lasted/wasted tag
```

>  but there's no way to hide the `@started` tag specifically, only the timestamp.

The `@started` tag is added only if you explicitly run `Todo: Toggle Start`, simply don't do it if you don't want the `@started` tag.

> and highlight the "started" items?

First of all how do we now that a todo has started? via the `@started` tag, you can't remove it if you want notes to be recognized as started.

There's no specific line highlight for started/done/cancelled/pending todos currently, you might achieve the desired effect via [Highlight](https://github.com/fabiospampinato/vscode-highlight) though.

Let's track the addition of customizable line colors here: https://github.com/fabiospampinato/vscode-todo-plus/issues/59

**Comment by claudiojrt** [comment]
Well, how do we know that a todo has been done if I disable the @done tag? I thought it was via symbols ("todo.symbols.box", "todo.symbols.done" and "todo.symbols.cancelled").

I thought it would be nice to have a symbol for "Started" and a color for it in a standard way, because when you have a long list the @started gets always to the end of the line (the reason why i disabled those)

Probably I can do this using the Highlight too, gonna give it a try. Thanks!

**Comment by fabiospampinato** [comment]
> Well, how do we know that a todo has been done if I disable the @done tag? I thought it was via symbols ("todo.symbols.box", "todo.symbols.done" and "todo.symbols.cancelled").

Yes, there isn't a symbol for "started".

> I thought it would be nice to have a symbol for "Started" and a color for it in a standard way, because when you have a long list the @started gets always to the end of the line (the reason why i disabled those)

I don't think this should be wise, as a todo could be in multiple states, now it could be "started", in the future it could be "overdue", maybe it can be "assigned to me", there can't be a symbol for all of this, we must use something like tags.
