### ISSUE TITLE
New Symbols

### ISSUE THREAD

**Issue by jaqra** [fabiospampinato/vscode-todo-plus#198]
Can you also add Question (?) And Warning (!) items?

**Comment by fabiospampinato** [comment]
It sounds a bit too specific and not related-enough to task management 🤔 Perhaps you can already achieve that today via [Highlight](https://github.com/fabiospampinato/vscode-highlight)

**Comment by jaqra** [comment]
I can not manage my todo items which is waiting to be answered from someone.
Or warning messages not only information.

It would be nice :/

**Comment by fabiospampinato** [comment]
Perhaps you should define a special `@blocked` tag or something. Also try the Highlight extension, if it doesn't conflict too much with this extension it will solve your problem.
