### ISSUE TITLE
Symbols not being correctly swapped when toggling

### ISSUE THREAD

**Issue by vfonic** [fabiospampinato/vscode-todo-plus#199]
I wanted to keep it simple and markdown-compatible so I put this in my config:

```json
{
  "todo.symbols.box": "- [ ]",
  "todo.symbols.done": "- [x]",
}
```

However, toggling done makes an incorrect change:

```
// from
- [ ] Remove
// to
- [x] [ ] Remove
```

Toggling again does the same incorrect change, the other way around:

```
// from
- [x] [ ] Remove
// to
- [ ] [x] [ ] Remove
```

I think it might have to do with regex not being escaped? 🤔 
I tried looking through the code, but couldn't figure out what was wrong exactly.

**Comment by fabiospampinato** [comment]
Those aren't supported symbols (you can't mix multiple supported symbols), the supported symbols are listed here https://github.com/fabiospampinato/vscode-todo-plus#features

If you want something very simple for markdown files try Markdown Todo https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-markdown-todo
