### ISSUE TITLE
Custom symbol doesn't get colored

### ISSUE THREAD

**Issue by neilsustc** [fabiospampinato/vscode-todo-plus#2]
When using ⬜ as box symbol

![image](https://user-images.githubusercontent.com/7588612/29542324-d8bda06a-870c-11e7-9036-7f9a2b0c6d5d.png)

**Comment by fabiospampinato** [comment]
Fixed with the latest update.

Keep in mind that arbitrary symbols are not supported, the list of supported ones is written in the readme.

**Comment by neilsustc** [comment]
Okay, thank you
