### ISSUE TITLE
`todo.file.name` not working for .md file

### ISSUE THREAD

**Issue by vfonic** [fabiospampinato/vscode-todo-plus#200]
I set `"todo.file.name": "TODO.md"` in my settings, but when I open the TODO sidebar, it says "No todo files found". It also doesn't recognize the file at all when I open the file (no hotkeys are working)

I also removed the installed Markdown Todo extension and that didn't help.

The only one that works on `TODO.md` is Markdown Todo extension.

**Comment by fabiospampinato** [comment]
That setting sets the name of the file the extension will create, the setting for finding those files is `  `todo.file.include`.

But I would advise against using markdown files with this extension, otherwise you'd have to toggle manually between the set language (Markdown vs Todo)

**Comment by 1st** [comment]
Hello. I have set the setting `todo.file.include` to `docs/TODO.md` and `todo.file.name` to `docs/TODO.md`. When I open the `docs/TODO.md` it's open automatically in the Markdown syntax.

Is it possible to change syntax to the `TODO` when the file name exactly matches the one of pattens that I have entered above in the settings?

Will be nice to do such small but useful improvement. @fabiospampinato

**Comment by fabiospampinato** [comment]
@1st there's a setting somewhere in VS Code, called "files.associations" or something like that, that lets you override the file associations, you should assign the "todo" language to the "docs/TODO.md" file there.
