### ISSUE TITLE
EACCES: permission denied

### ISSUE THREAD

**Issue by b-fett** [fabiospampinato/vscode-todo-plus#201]
In case of you have inside project directory with altered permissons (for example, some bindings from docker container) you gets access error and extension doesn't work at all.

**Comment by fabiospampinato** [comment]
@b-fett can you link an example repo that reproduces the issue? I can't reproduce this, I've tried creating a file and setting it's permissions to 0o000, but the extension then just detects it to be empty.

**Comment by b-fett** [comment]
@fabiospampinato, well, as i mentioned, you have to create directory but no file.

**Comment by fabiospampinato** [comment]
@b-fett Can you provide clear reproducible steps?

**Comment by b-fett** [comment]
```bash
mkdir test-repo
mkdir test-repo/inaccessible-dir
chmod 000 test-repo/inaccessible-dir
code --add test-repo
```
And hit extension button.

**Comment by fabiospampinato** [comment]
> And hit extension button.

What button? The one in the statusbar?

**Comment by fabiospampinato** [comment]
I think this is an upstream issue: https://github.com/microsoft/vscode/issues/74169

I don't think this specific extension is doing anything weird that could trigger this error.

**Comment by b-fett** [comment]
@fabiospampinato any thoughts how to fix it? Or at least to have workaround.
I tried to add folder to `todo.file.exclude` section, but it didn't work.

**Comment by fabiospampinato** [comment]
@b-fett Sorry I don't think I have a workaround for you.
