### ISSUE TITLE
Make embedded view keyboard friendly

### ISSUE THREAD

**Issue by nikitavoloboev** [fabiospampinato/vscode-todo-plus#202]
I would love it if when I'm on line with TODO and there is `@file://..` URL. Pressing return would open this file in a new tab (same as pressing cmd + click on the link).

Not sure if it's possible but it would be great.

**Comment by fabiospampinato** [comment]
I like the idea a lot.

It's implementable, but I'm closing this because I think this should be implemented as a standalone extension, as it has its uses outside of `*.todo` files too.

If anybody would like to make this extension I'd be happy to link to it from the readme 👍
