### ISSUE TITLE
Add todos in the current file to Embedded View

### ISSUE THREAD

**Issue by nikitavoloboev** [fabiospampinato/vscode-todo-plus#205]
On top of this view:

![2019-06-10 at 14 03](https://user-images.githubusercontent.com/6391776/59197186-900b8d00-8b88-11e9-9624-e59ff493a11d.png)

It would also be nice if Files tab will get collapsed when it's empty.

**Comment by fabiospampinato** [comment]
An "embedded" view that only displays todos belonging to the same file would be interesting.

> It would also be nice if Files tab will get collapsed when it's empty.

Sounds reasonable.

**Comment by nikitavoloboev** [comment]
> An "embedded" view that only displays todos belonging to the same file would be interesting.

I want to see both embedded (global) and embedded (local) in one sidebar view. Like right now there is `Files` and `Embedded`.

**Comment by fabiospampinato** [comment]
Just implemented. There were a gazillion ways to do it, in the end I added a button (and standalone command palette command) in the embedded view toolbar for toggling between viewing all files or only the current one.

**Comment by regs01** [comment]
Somehow it doesn't work for me. When toggling Active File the list is just empty. While it is there while seeing all files.
