### ISSUE TITLE
Open .txt files

### ISSUE THREAD

**Issue by meadows19** [fabiospampinato/vscode-todo-plus#206]
Hello.

How do I open a .txt file with this extention?

You mentioned that it can be done using Files. Associations, but I don't know how to do that? Can you please help?

Thank you!

**Comment by fabiospampinato** [comment]
You can either just open it and change the language more, or set the language association as I mentioned in the other issue, it's a setting for vscode basically. Maybe you'll find more infos about that in vscode's docs.
