### ISSUE TITLE
Update the icons

### ISSUE THREAD

**Issue by johnletey** [fabiospampinato/vscode-todo-plus#209]
With the release of the new vscode icons coming up, the project should have similar (and the same) icons so that it looks visually appealing and also up-to-date!

I have already done this work:

- I have changed the activity bar icon to be 24x25 (the same size as the other official vscode icons)

![activity_bar_logo](https://user-images.githubusercontent.com/30328854/61179102-5d7c0680-a604-11e9-8e07-27431d67bda5.png)

- I have also completely updated all of the other icons:

<img width="857" alt="Screen Shot 2019-07-14 at 6 52 28 AM" src="https://user-images.githubusercontent.com/30328854/61179106-708ed680-a604-11e9-808a-8789b04059e9.png">

You can find all of the changed icons on [Figma](https://www.figma.com/file/IrU1Nr76NTdIBhv2EMUaRwU7/fabio-vscode-icons)

**Comment by fabiospampinato** [comment]
PR welcome 👍 	

> I have changed the activity bar icon to be 24x25

I suppose it should use the new style also?

> I have also completely updated all of the other icons:

The "tree_icon" icon is actually embedded in the code and we are changing its color dynamically: https://github.com/fabiospampinato/vscode-todo-plus/blob/master/src%2Futils%2Fview.ts/#L49-L50

I'm not sure it will look nice in the new style, that's something that should be tested. I'd be great if you could attach a screenshot where the new icon is visible.

**Comment by johnletey** [comment]
> I suppose it should use the new style also?

Sounds good ... will update as soon as possible!

> I'm not sure it will look nice in the new style, that's something that should be tested. It'd be great if you could attach a screenshot where the new icon is visible.

So you mean like edit the code to contain the SVG code of my new `tree_icon` in my last screenshot ... and then run the extension locally?

**Comment by fabiospampinato** [comment]
> So you mean like edit the code to contain the SVG code of my new tree_icon in my last screenshot ... and then run the extension locally?

Exactly, basically I'm not sure that icon should be changed, changing it needs to be worth it.

**Comment by johnletey** [comment]
@fabiospampinato Sounds good ... I'll hopefully have a screenshot up soon ... also, here is the new sidebar icon taken from the vscode source and resized:

<img width="145" alt="Screen Shot 2019-07-14 at 7 46 18 PM" src="https://user-images.githubusercontent.com/30328854/61186621-293e2f80-a670-11e9-947b-6850fb6188f0.png">

I will run the extension in development mode now ... not quite sure how though

**Comment by fabiospampinato** [comment]
@johnletey That's a different shape though, the shape should remain the same, but its style should be updated (unless it would necessarily look ugly for some reason 🤔).

> I will run the extension in development mode now ... not quite sure how though

> If you want to make a pull request you can debug the extension using Debug Launcher.

Basically install that other extension and run "Debug Launcher: Auto".

**Comment by johnletey** [comment]
> That's a different shape though, the shape should remain the same, but its style should be updated (unless it would necessarily look ugly for some reason 🤔).

Sounds good ... will update

> Basically install that other extension and run "Debug Launcher: Auto".

@fabiospampinato I did that ... but it didn't work ... I'm getting an error with webpack when it runs ... will investigate further

**Comment by fabiospampinato** [comment]
> @fabiospampinato I did that ... but it didn't work ... I'm getting an error with webpack when it runs ... will investigate further

Maybe there's a typescript error somewhere? 🤔

**Comment by johnletey** [comment]
Maybe @fabiospampinato ... I just pushed the updates to my [fork](https://github.com/johnletey/vscode-todo-plus/tree/refactor/icons)

Could you maybe try to run the code and see what you get? I still can't figure out what is going on!

**Comment by fabiospampinato** [comment]
I'll see what I can do 👍

**Comment by fabiospampinato** [comment]
Just implemented this, I've left out the tree item icon as the outline version of it looks too distracting to me.

Thanks @johnletey, the icons you provided were very useful, I used all of them except the activity bar one.

**Comment by johnletey** [comment]
Wonderful ... thank you so much for updating the icons @fabiospampinato!
