### ISSUE TITLE
Bug: Syntax Highlighting of @:

### ISSUE THREAD

**Issue by sahil48** [fabiospampinato/vscode-todo-plus#211]
I have been adding a special character to organize my tags better

For example.

* @>Mike means I am assigning something to Mike 
* @<Mike means I am waiting for something from Mike
* @#home means the context is home

One of these combinations @: (ex. @:project1 means that the task is associated with this project) does not get recognized as a tag and become yellow. Please fix this.

**Comment by fabiospampinato** [comment]
@sahil48 Can you post a file that reproduces the issue?

**Comment by sahil48** [comment]
How do I upload files to github? Never did that in github.

A screenshot of what happens in a .taskpaper file is shown below.
![image](https://user-images.githubusercontent.com/6100774/61797317-29b79280-adf5-11e9-86a1-ab62654bcbcf.png)

**Comment by fabiospampinato** [comment]
> How do I upload files to github? Never did that in github.

Those are really questions for google to answer 😄

**Comment by fabiospampinato** [comment]
Ok I can see the issue now.

It looks like we are explicitly forbidding colons [here](https://github.com/fabiospampinato/vscode-todo-plus/blob/master/src%2Fconsts.ts/#L67), I'm not quite sure why. 

PR welcome for fixing this 👍

**Comment by sahil48** [comment]
> Those are really questions for google to answer 😄
😄

> It looks like we are explicitly forbidding colons here, I'm not quite sure why.

Thanks for the explanation. Can those be updated from todo-plus settings? Finally something google can't answer. :-)

![image](https://user-images.githubusercontent.com/6100774/61798107-ba42a280-adf6-11e9-91b5-2c5bbaedf52e.png)
So it's drag and drop only if it is a txt file, and if .taskpaper extension is used, it has to be zipped any attached.

**Comment by fabiospampinato** [comment]
> Finally something google can't answer. :-)

You'd be surprised. You can't update them.

**Comment by fabiospampinato** [comment]
Fix fixed, update coming soon.
