### ISSUE TITLE
Always display cumulative @lasted time on projects

### ISSUE THREAD

**Issue by hellos3b** [fabiospampinato/vscode-todo-plus#212]
When you have any unchecked items, it shows you total time next to the todo:

<img width="529" alt="Screen Shot 2019-07-30 at 1 40 50 AM" src="https://user-images.githubusercontent.com/4062679/62114307-4297cc00-b26b-11e9-892d-585988eece44.png">

*(The `1hr25m21s`)*

When you mark all items as done, this tracker goes away

<img width="527" alt="Screen Shot 2019-07-30 at 1 42 47 AM" src="https://user-images.githubusercontent.com/4062679/62114355-5d6a4080-b26b-11e9-83c8-e540a781f73e.png">

Can we have an option to always display it?

--

I usually split my lists by feature, and it'd be nice to see how much time I've spent on each one. But also on my latest side project, I'm using it as a "clock in" - "clock out" tracker just for fun to see how much time I've spent on it

**Comment by fabiospampinato** [comment]
Sounds like a reasonable feature, PR welcome 👍

**Comment by damianavila** [comment]
@fabiospampinato can you give us some hints about where we should start looking to implement this feature?

**Comment by hellos3b** [comment]
Gave it a shot

**Comment by damianavila** [comment]
Check it, but I think it is not enough.
I think the PR from @hellos3b (thanks!) goes in the direction we wanted.

**Comment by fabiospampinato** [comment]
Let's track this [there](https://github.com/fabiospampinato/vscode-todo-plus/pull/213) then.
