### ISSUE TITLE
Not supporting cyrillic characters

### ISSUE THREAD

**Issue by alexsmff** [fabiospampinato/vscode-todo-plus#215]
Hi!
I found what after save and load workspace all cyrillic characters in todo look like ?????

**Comment by fabiospampinato** [comment]
We aren't doing any character replacements. Are you sure this is a problem with ToDo+? Can you post a file that reproduces the issue?

**Comment by alexsmff** [comment]
[TODO.txt](https://github.com/fabiospampinato/vscode-todo-plus/files/3489192/TODO.txt)

You can try add  text like 'Сделать в ближайшее время' and reload workspace

**Comment by fabiospampinato** [comment]
I don't see any difference. I highly doubt this issue is related to this extension.
