### ISSUE TITLE
Project header count is '(0)' if tab character is used as indentation

### ISSUE THREAD

**Issue by adamkiss** [fabiospampinato/vscode-todo-plus#219]
Hi,

first: thank you for this extension.

the problem is with using indentation as `"\t"` — The project task count doesn't stays at `(0)`

![Screenshot 2019-08-30 14 01 05](https://user-images.githubusercontent.com/481362/64019252-eefcf480-cb2e-11e9-86c2-c6c762212369.png)

**Versions:**
VSCode: 1.37.1
Todo+: 4.14.0

**Settings changed:**
``` json
{
    "todo.file.defaultContent": "Todo:\n\t- Item",
    "todo.file.name": "TODO.taskpaper",
    "todo.indentation": "\t",
    "todo.symbols.box": "-",
    "todo.symbols.done": "-",
    "todo.symbols.cancelled": "-"
}
```

Thank you

**Comment by fabiospampinato** [comment]
Keep your indentation consistent and update `"todo.indentation": "\t"` accordingly.

**Comment by adamkiss** [comment]
@fabiospampinato That was only for illustration; consistent indentation results in the same.

![Screenshot 2019-08-30 14 18 38](https://user-images.githubusercontent.com/481362/64020192-3edcbb00-cb31-11e9-86ee-b9dd587246a2.png)

**Comment by fabiospampinato** [comment]
@adamkiss can you post the raw note the reproduces the issue?

**Comment by adamkiss** [comment]
Of course:

```
List using tabs (default):
	- Default
	- Second task

List using spaces:
	- Woop
	- Another
	Subproject:
		- task
```

[TODO.taskpaper.zip](https://github.com/fabiospampinato/vscode-todo-plus/files/3559891/TODO.taskpaper.zip)

Don't know if this has any impact on things, but this is a `.editorconfig` rule for `*.taskpaper` files:
``` ini
[*.taskpaper]
charset = utf-8
indent_style = tab
indent_size = 4
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
```

**Comment by fabiospampinato** [comment]
I can't reproduce, both setting `"todo.indentation": "\t"` and leaving it unchanged work for me 🤷‍♀

![image](https://user-images.githubusercontent.com/1812093/64021163-9d0a9d80-cb33-11e9-8c9e-bedb36cb6e78.png)

You should probably try reproducing it in a clean vscode installation (or vscode insiders).

**Comment by fabiospampinato** [comment]
I don't think `.editorconfig` should make any difference 🤔

**Comment by adamkiss** [comment]
Cool, trying out insiders.

**Comment by adamkiss** [comment]
@fabiospampinato ¯\_(ツ)_/¯ disabled and enabled all extensions and now it works.

It's been a while "did you try turning it on and off" worked for me…

thank you, and have a nice day.

**Comment by fabiospampinato** [comment]
Weird, I'm glad it works now 👍
