### ISSUE TITLE
A tag for time estimates

### ISSUE THREAD

**Issue by shvfn** [fabiospampinato/vscode-todo-plus#22]
Hi, I got an idea for a feature. It's not a small one, but I thought it doesn't hurt to suggest it. 

So, I think it would be useful if a user could add a tag with an estimated duration to a task. Those estimates could then be automatically added up next to the encapsulating project title. 

For example, if we have a todo-list like this:

```
Add that thing to project:
 ☐ plan it  
 ☐ implement it
 ☐ test it
```
 
then the user could add time estimates like this: 

```
Add that thing to project:
 ☐ plan it @est 30m
 ☐ implement it @est 3h
 ☐ test it @est 1h30m
```

And when that's done, the user calls a VSCode action "Todo: update estimated times" and that would add up the estimates in the project title like this:

```
Add that thing to project (est: 5h):
 ☐ plan it @est 30m
 ☐ implement it @est 3h
 ☐ test it @est 1h30m
```

For nested projects, it would have to add up all item and child project estimates:

So when we start with these estimates: 

```
My project:
  ☐ write documentation @est 2h
  That one feature:
	☐ item 1.1 @est 1h30m    
	☐ item 1.2 @est 45m    
  That other feature:
	☐ item 2.1 @est 1h
	☐ item 2.2 @est 10m   
``` 

the "update"-action would result in this:

```
My project (est: 5h25m)
  ☐ write documentation @est 2h
  That one feature (est: 2h15m):
	☐ item 1.1 @est 1h30m    
	☐ item 1.2 @est 45m    
  That other feature (est: 1h10m):
	☐ item 2.1 @est 1h
	☐ item 2.2 @est 10m    
```

because it adds up the "write doc"-item and the two sub-project titles.

If it's too much work, out of scope or just not doable, just close this, but I think this could be really useful.

In any case: Thanks a lot for this addon!

**Comment by fabiospampinato** [comment]
Thanks for the suggestion! 

I like the idea, but I think there are more important features to implement first. I'll keep this open in order to monitor the popularity of the request.

**Comment by fabiospampinato** [comment]
How to implement this:

- We should use `@est(1h30m)` for this, perhaps we should support a shorthand tag too: `@1h30m` (less tedious to write).
- A new token (`est`) should be added  [here](https://github.com/fabiospampinato/vscode-todo-plus/blob/e2e5433d31e242055c691011c0f031e8d7bfa2f8/src/utils.ts#L452) and [here](https://github.com/fabiospampinato/vscode-todo-plus/blob/e2e5433d31e242055c691011c0f031e8d7bfa2f8/src/utils.ts#L484).
- Figure out a way to sum all those estimates (This is the tricky bit, how do we support things like `@2day`, `@2d`, `@est(2 days)`?)

**Comment by fabiospampinato** [comment]
Implemented in v1.17.0, I'm quite pleased with the result, check it out:

![estimate](https://user-images.githubusercontent.com/1812093/40318265-518b9662-5d24-11e8-97a8-c6a153c145b9.gif)

**Comment by shvfn** [comment]
This is sooo cool! Awesome! Thanks a lot, Fabio! :)

**Comment by eteisman** [comment]
Amazing! I was looking for this.

One remark: can you update the documentation for this?
I only found out this is possible when I attempted to add an almost identical feature request.

Thank you!

**Comment by fabiospampinato** [comment]
@eteisman Actually it is already mentioned:

> Time estimates: you can estimate the time it will take to complete a todo by adding a tag to it that looks like this: @est(3 hours), @est(2h30m) or @2h30m. Then you can use the [est] token in statistics

![](https://github.com/fabiospampinato/vscode-todo-plus/raw/master/resources/demo/timer.gif)

Unfortunately since we provide many features it's hard to miss some just by reading the readme.

**Comment by est** [comment]
@fabiospampinato  yo got me a github notification lolwat

**Comment by fabiospampinato** [comment]
@est Sorry, copying the paragraph I quoted didn't preserve the backticks.
