### ISSUE TITLE
Usability Improvement: Do not update Syntax Highlighting of Active Line

### ISSUE THREAD

**Issue by sahil48** [fabiospampinato/vscode-todo-plus#221]
Changes in color and addition of project information are distracting while I am typing and tends to glitch midway. It would be great if the line you were typing in does not get updated until you leave that line. (up or down arrow, enter, or clicking outside of the line). If an escape out of the line is not detected for maybe 5 or 10 seconds once you stop typing, then the line could be updated if not all edge cases were detected. For me at least, this would make the behavior of syntax highlighting more predictable and less distracting.

**Comment by fabiospampinato** [comment]
I don't agree with this, I think the document should be correctly syntax highlighted at any point in time, like any programming language would.

**Comment by sahil48** [comment]
> If the syntax highlighting is glitchy then that's the issue.

In that case, the one item that seems to be at issue is pressing a space after a colon. If I press return after typing a colon, I am intending to create a product and the line color should change to blue. If I type a space after the colon, I am still writing the rest of my note, and the color of the line should stay gray, and no project statistics should show.

The cursor always ends up to the right of the project statistics which is also jarring. So perhaps the project statistics should always be to the right of the cursor if both are on the same line
![image](https://user-images.githubusercontent.com/6100774/64428243-46481b00-d081-11e9-89db-7b555903a17f.png)

After typing text, the line quickly turns back to gray.
![image](https://user-images.githubusercontent.com/6100774/64428272-552ecd80-d081-11e9-93b7-6b1d026e60a2.png)

**Comment by fabiospampinato** [comment]
I see the issue 🤔 What kind of texts are you writing after the colon? Like are you writing tags or something else?

Btw you can "fix" this already if you want by setting the "todo.statistics.project.enabled" appropriately so that no project-level statistics are shown if there are no todos in it.

**Comment by sahil48** [comment]
If I am writing a note, it would be a keyword, followed by a colon, followed by a definition.

More frequently, I use a colon a lot for events that occur between tasks. I think of events as distinguished from tasks. They don't really accomplish anything (I mean, we get a lot done, but the things done would be marked as complete for separate tasks nested under the event), but I must make myself available then.

- task 1
10:30 to 11: Event
- task 2

I like project level statistics with the event syntax.

**Comment by fabiospampinato** [comment]
> If I am writing a note, it would be a keyword, followed by a colon, followed by a definition.

Can you provide me some actual text so that I can better understand your use case?

**Comment by sahil48** [comment]
This is usually how I organize a day with Todo. Took out names and parts and put them in curly brackets. Hope this Helps. So, anything with a colon after it usually provides additional context for a task, or includes other non-task related items that occur in the day.

2019-09-05
Sequence:
    - Send PO for {Part} quoted by {Customer} @done(2019-09-05 08:51:45)
    - Download receiving orders from {Software}@done(2019-09-05 09:20:56)
    - Send all unsent invoices @done(2019-09-05 09:41:19)
    10:30am: Review {Part} with {Vendor} @done(2019-09-05 10:57:56)
    - Produce draft of instructions for Replacing {part} @cancelled(2019-09-05)
    - Locate {Part} in Service Manual @done(2019-09-05 11:10:42)
    12:40-1pm: Follow up with {Vendor} on the {Product} @done(2019-09-05 12:41:20)
     INTERRUPTION: had {Person} sign appropriate documents @done(2019-09-05)
    - Teach {coworkers} how to use the {tool} @done(2019-09-05 13:59:19)
    - Prepare PO for {Part} @>{Person who will do it} @done(2019-09-05)
    - Package {Part} @done(2019-09-05)
    Objective: Build {Product} to the point where {Part} can be installed on the {Product}
        - Align already flattened {part} to {other part}; perform other alignment activities @done(2019-09-05)

**Comment by fabiospampinato** [comment]
Ok I see the issue, IMHO setting the following:

```
"todo.statistics.project.enabled": "global.projects < 100 && project.all > 0",
```

Largely solves it.

**Comment by sahil48** [comment]
Okay, I think that works. So basically, if no task is nested in the project, the project statistics do not show, correct?

**Comment by fabiospampinato** [comment]
Yess

**Comment by sahil48** [comment]
Great. I agree that this seems like a sensible default.

**Comment by fabiospampinato** [comment]
It's now the default 👍
