### ISSUE TITLE
Project metadata not working randomly/ with externally created files ([all] [est])

### ISSUE THREAD

**Issue by filipgoc** [fabiospampinato/vscode-todo-plus#222]
Hi!
I have to say this extension looks amazing. But I have this: 

**Issue**
In some files, the metadata works just fine, in others it remains at "0" no matter what. 

---

Maybe I'm misunderstanding how to use the extensions. (I have just started using it today). 

Do I always have to create new files from within the app? (Using Project: Open)
Is there any way to create the TODO file in a different app and still work?

---

## Here's some tests I have replicated so far: 

1. Download the https://raw.githubusercontent.com/fabiospampinato/vscode-todo-plus/master/resources/readme.todo;
👍all is fine. 
![image](https://user-images.githubusercontent.com/16858474/64476685-7fbc7b80-d192-11e9-9be9-586336c5b444.png)

2. Change the file above to anything (including copy paste from files that do _not_ work),
👍 all is fine. 

3. Make a new file in taskpaper (the settings are adjusted to work like that) and open it with vscode
👍 colors are recognized and the shortcuts work
👎 the metadata do not work
![image](https://user-images.githubusercontent.com/16858474/64476740-34569d00-d193-11e9-8034-5b9c08891291.png)

4. Start a new project. Make a new todo file via this extension (Project: Open). 
(The default is set to `"todo.file.defaultContent": "\nTodo:\n  - ?\n"`)
👍 all works
![image](https://user-images.githubusercontent.com/16858474/64478377-fca62000-d1a7-11e9-88c0-08ac460f9910.png)

5. Create a new file in vscode.
Save this file with .todo extension.
Then write some todos. 
👍 colors are recognized and the shortcuts work
👎 the metadata do not work

6. Create a new file in vscode.
First write some todos
Then save this file with .todo extension.
👍 colors are recognized and the shortcuts work
👎 the metadata do not work

7. Make a new plaintext file in atom or another editor, name it with the .todo extension
Then open in vscode. 
👍 colors are recognized and the shortcuts work
👎 the metadata do not work
![image](https://user-images.githubusercontent.com/16858474/64476732-16893800-d193-11e9-8957-af074aed2d76.png)

8. **This one is weird.**  (Given the scenarios above that fail). 
Take a random file, in my case a .step file (a 3D object file in fact). 
Change extension to .todo
Open in vscode
Replace the data with some todos. 
👍 all works
What?!

OK. I tried number 8 for the 2nd time and it did NOT work the 2nd time
What?!

---

Any help is appreciated! I don't know what's happening.

**Comment by fabiospampinato** [comment]
The extension doesn't care where you're writing or creating your todo files.

I don't think there's actually a problem here, you're seeing `(0)` in the statistics because those projects actually have 0 todos inside them. The todos you wrote aren't actually inside the project, but at the same level of the project. Just indent them a bit.

**Comment by filipgoc** [comment]
@fabiospampinato Hahahaha. 
I'm still happy I posted - this cost me time and brought me to the brink of insanity. 
Thank you for a quick reaction!
