### ISSUE TITLE
no TYPES changes my color

### ISSUE THREAD

**Issue by LeninZapata** [fabiospampinato/vscode-todo-plus#223]
Hello, for some reason no TYPES changes my color, what could be happening?
http://prntscr.com/p4k3qf

**Comment by fabiospampinato** [comment]
That's about the color of the icon in the activity bar, use [vscode-highlight](https://github.com/fabiospampinato/vscode-highlight) for syntax-highlighting todos.

**Comment by LeninZapata** [comment]
Thank you very much this worked!
