### ISSUE TITLE
New types not shown

### ISSUE THREAD

**Issue by LeninZapata** [fabiospampinato/vscode-todo-plus#224]
Hello, in the parameters `todo.embedded.providers.ag.regex` and `todo.embedded.providers.rg.regex` I have new ones **types** for my personalization but they do not appear in the section of  **embedded**, what am I doing wrong?
🖼️ http://prntscr.com/p4umz8

**Comment by fabiospampinato** [comment]
You have to update `todo.embedded.regex` as well.

**Comment by LeninZapata** [comment]
Thank you!
