### ISSUE TITLE
Color balance between new TYPES and the embedded

### ISSUE THREAD

**Issue by LeninZapata** [fabiospampinato/vscode-todo-plus#225]
Hi, how can I change the color of the indicator in the **embedded** section, my ALL color is bluish, the same color I want to keep in the **embedded** section.

- 1) How can I configure it?
- 2) Do the new types added have no color icon, how do I add them?

![Image of Yaktocat](https://i.imgur.com/E5ytUPc.jpg)
[screenshot](https://i.imgur.com/E5ytUPc.jpg)

**Comment by fabiospampinato** [comment]
Set `todo.colors.types`.

**Comment by LeninZapata** [comment]
OK thank you very much.
