### ISSUE TITLE
Convert an untitled file to a todo list

### ISSUE THREAD

**Issue by garyking** [fabiospampinato/vscode-todo-plus#228]
Please make it possible that I can open an untitled file in VSC, and convert it to a TODO list. So that I don't have to save it anywhere. Because sometimes, I have a list of todos I want to complete, not associated with a workspace, and I don't want to save it, because when I'm done with it, then I just want to close the untitled file.

Also, is it possible to have multiple TODO files for one workspace?

**Comment by fabiospampinato** [comment]
> Please make it possible that I can open an untitled file in VSC, and convert it to a TODO list.

Already possible, switch the language from "Plain Text" to "Todo".

> Also, is it possible to have multiple TODO files for one workspace?

Absolutely.
