### ISSUE TITLE
Links in "Embedded Todo" don't work with remote development

### ISSUE THREAD

**Issue by corani** [fabiospampinato/vscode-todo-plus#234]
Not sure if this is an issue in VS Code/Remote Development itself, or with this extension. But the generated links in "Embedded Todo" don't work, while those in the sidebar *do* work.

(I'm using remote development over SSH, with VSCode 1.41.0-insiders and todo+ 4.14.1)

**Comment by fabiospampinato** [comment]
What links are you talking about, the `file://` ones?

**Comment by corani** [comment]
Yes, exactly: `@file:///path/to/file`

**Comment by fabiospampinato** [comment]
I don't think there's much we can do about that, it seems like a problem with VSCode 🤔
