### ISSUE TITLE
Feature Request: Enable users to automatically add tag when keyword is entered

### ISSUE THREAD

**Issue by sahil48** [fabiospampinato/vscode-todo-plus#235]
For automating the entry of tags in tasks, it would be great in todo plus to automatically add tags when a task is entered and the user presses enter.

ex. if keyword "cook" is mapped to `@home` and `@night`

When I type in

`- cook soup`

and press enter, todo plus would automatically add the tag `@home` and `@night`

`- cook soup @home @night`

I have tons of tasks like these, especially at work. When I am spending time working for a specific customer, it would be great to search tasks for a customer tagged automatically with "@customername" thanks to a number of keywords associated with that tag associated with that customer.

**Comment by fabiospampinato** [comment]
> For automating the entry of tags in tasks, it would be great in todo plus to automatically add tags when a task is entered and the user presses enter.

It seems a title too specific and perhaps out of scope, maybe your text expander should take care of this.

> it would be great to search tasks for a customer tagged automatically with "@customername" thanks to a number of keywords associated with that tag associated with that customer.

Let's track filtering by tags here: #18
