### ISSUE TITLE
Feature Request: shortcut to move all tags to end of a line

### ISSUE THREAD

**Issue by sahil48** [fabiospampinato/vscode-todo-plus#236]
After reading your comments about using a text expander in [Issue 235](https://github.com/fabiospampinato/vscode-todo-plus/issues/235), I narrowed the scope of my feature request further.

It would be helpful to have a shortcut for moving all tags to the end of the line a cursor is on or the lines selected by highlighting them.

For example, continuing the example in Issue 235, if I type:

`- cook soup`

and with the autocomplete, the following ends up on the line:

`-cook @home @night soup`

I would want the shortcut to rearrange this to:

`- cook soup @home @night`

------

Any tags with a date or time in them should go after tags without a date or time, at the end of the line but ordered chronologically

For example

`-@scheduled(6:30pm) cook @home @night soup @start(7:30pm) @done(8:00pm)`

Should convert to
`- cook soup @home @night @scheduled(6:30pm) @start(7:30pm) @done(8:00pm)`

**Comment by fabiospampinato** [comment]
It seems to specific, if you wan tags at the end insert them there to begin with.
