### ISSUE TITLE
// NOTE & // INFO as well?

### ISSUE THREAD

**Issue by reinhardjung** [fabiospampinato/vscode-todo-plus#237]
Hi

i love your ext. but how can i add // NOTE and // INFO as well.
Not only // TODO and // FIXME?

Thanx a lot for helping me

**Comment by fabiospampinato** [comment]
Configure "todo.colors.types", "todo.embedded.regex", "todo.embedded.providers.ag.regex" and "todo.embedded.providers.rg.regex".
