### ISSUE TITLE
Archive destroys the "format"

### ISSUE THREAD

**Issue by tyoc213** [fabiospampinato/vscode-todo-plus#24]
It would be nice if the line could by hided as is now, but marked with a special icon instead of moved of line...

I propose for example: ⌨ as icon?

Maybe ☺ ☻ ▦ ▧ ▨ ▩ or something so it is not confused with other icons

Or keep the format of the things.... but in the cancelled section... so to interleave the projects and append at end of archived task... (but I think the first option is best, because you can mantain it in a git repo or something... well if needed)

**Comment by fabiospampinato** [comment]
Man, I've no idea what you're talking about.

What's the "format"? 

> It would be nice if **the line** could by hided as is now

What line? What do you mean "hided"?

It would be better if you could make me a screenshot or something.

**Comment by tyoc213** [comment]
sorry @fabiospampinato I was referring that when there are done and cancelled task, when you `Archive` the task are moved from their original positions to the end of the file.

So it will be nice if the task where grayed out only instead of moved out... thought dont know, that is only personal preference...  I guess. And the icon was just to "mark" that it was already archived...

Thanks anyway :), by the way the total time output, I use to update my task on gitlab with the `/spend 1d3h` xD so I can track and fill that time with your plugin.

**Comment by fabiospampinato** [comment]
The whole point of the Archive section is to move finished there, if you don't want that just don't use it.

There are settings for changing the color of completed tasks, maybe you can set them to a gray color of your likings.
