### ISSUE TITLE
Embedded stopped working for workspace

### ISSUE THREAD

**Issue by mtxr** [fabiospampinato/vscode-todo-plus#240]
![image](https://user-images.githubusercontent.com/707561/74076616-eec72600-49f7-11ea-8ac0-a20afc630094.png)

You can check a reproducible repo from my project:
https://github.com/mtxr/vscode-sqltools/tree/lazy-tree

If I open `packages/extension` in VSCode, I get it working, 
if I open `project.code-workspace` it doesn't.

**Comment by mtxr** [comment]
nvm, I had deleted folder and that was generating an error. The only problem I see is that I had to clone, install, build and run to see the error in the debug console. Couldn't we have an output channel just for errors?

**Comment by fabiospampinato** [comment]
What errors are we talking about?

**Comment by mtxr** [comment]
In this casa, "no such file or directory"

**Comment by mtxr** [comment]
Eg: set invalid args to your provider, like this:
```
"todo.embedded.providers.rg.args": [
    "--ignore-case",
    "--INVALIDARG",
  ],```
it breaks and no error is thrown anywhere.

**Comment by fabiospampinato** [comment]
> Couldn't we have an output channel just for errors?

PR welcome.
