### ISSUE TITLE
Provide ripgrep and silversearcher binaries

### ISSUE THREAD

**Issue by surpavan** [fabiospampinato/vscode-todo-plus#242]
Is it possible to configure/use repgrep or silversearcher without installation?  I do not have admin privileges on my laptop.
Java search is very slow.
Windows 10

**Comment by fabiospampinato** [comment]
PR welcome for using the ripgrep binary that VSCode itself ships if available.

**Comment by surpavan** [comment]
not sure, but does this help? 
https://github.com/microsoft/vscode-ripgrep

**Comment by fabiospampinato** [comment]
If I remember correctly Todo Tree is linking to the ripgrep binary that ships with vscode: https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree

**Comment by surpavan** [comment]
ok.  Will shift to that now.

**Comment by jods4** [comment]
I am curious about such improvements.

I have a 1200 lines TODO file and every time I type a `@` sign VS code freezes for 2 or 3 sec.

**Comment by surpavan** [comment]
@jods4 - @fabiospampinato - this is a well balanced extension for me or people who do not want unnecessary big stuff.

**Comment by fabiospampinato** [comment]
Providing precompiled binaries is a pain in the ass, not gonna happen.
