### ISSUE TITLE
Treat `@est` times as `@lasted` times in completed tasks

### ISSUE THREAD

**Issue by hirasso** [fabiospampinato/vscode-todo-plus#244]
Hi there, 

what a great extension, thanks so much!!!

...I head an idea, that I imagine could be very useful. I use the shorthand for @est in my tasks:

![image](https://user-images.githubusercontent.com/869813/75260003-349e2f80-57e9-11ea-9552-28f534de89bc.png)

This is my setting for project statistics:

```json
"todo.statistics.project.text": "([pending]) [est] [lasted]"
```
Now if I mark a task as `done`, it would be great if it's @est time would be counted to the [lasted] statistic. Here's a mockup (hardcoded it in settings as "todo.statistics.project.text": "([pending]) [est] 2h"):

![image](https://user-images.githubusercontent.com/869813/75260249-9b234d80-57e9-11ea-9446-0213eff9b963.png)

Does this make sense and would it be possible to implement?

**Comment by fabiospampinato** [comment]
🤔 it sounds like a good idea, but what if a task takes actually more than what was estimated? I'm not sure the extension could then be able to account for this and show meaningful numbers.

**Comment by est** [comment]
It's a bad idea to quote arbitrary other people like me. Please use code block like `@est`

**Comment by hirasso** [comment]
> 🤔 it sounds like a good idea, but what if a task takes actually more than what was estimated? I'm not sure the extension could then be able to account for this and show meaningful numbers.

I thought it could only do this if there would be no @lasted(2h) on the same line.

**Comment by hirasso** [comment]
Some pseudo code:

```
if(line_is_marked_done() && line_contains(@2h) && line_doesnt_contain(@lasted) ) {
  count_lasted(@2h)
}
```
something like this? :)

**Comment by fabiospampinato** [comment]
Maybe, I'm not too convinced about this because it overloads the meaning of est tags 🤔 it could be handy though. I think there are more pressing issues to tackle right now though.
