### ISSUE TITLE
'hours' todo.timekeeping.estimate.format

### ISSUE THREAD

**Issue by hirasso** [fabiospampinato/vscode-todo-plus#245]
Hi there,

would it be possible to allow for a more open setting for `todo.timekeeping.estimate.format` ?

In my case, I would like to have the option to only display hours, not days. So instead of `1d2h` I would prefer `26h`. Something like this would be amazing:

```json
"todo.timekeeping.estimate.format": "hours"
```

Background: I would like to use my Todo lists for my estimates. In these, the total amount of estimated hours for my tasks would be a very handy information.

**Comment by hirasso** [comment]
@fabiospampinato I'd definitely like to help – but how?

**Comment by fabiospampinato** [comment]
@hirasso What do you mean "how"? You should basically implement a new format here: https://github.com/fabiospampinato/vscode-todo-plus/blob/master/src/utils/time.ts/#L20-L26

**Comment by hirasso** [comment]
@fabiospampinato Thanks for the pointer to `time.ts` – The actual code shouldn't be too hard I guess – but I don't have any experience with the whole vscode extension architecture, yet... do you have a contributing-guide?

**Comment by fabiospampinato** [comment]
@hirasso https://github.com/fabiospampinato/vscode-todo-plus#contributing

**Comment by hirasso** [comment]
see #246
