### ISSUE TITLE
Add an option to automatically archive when marking done

### ISSUE THREAD

**Issue by jylin** [fabiospampinato/vscode-todo-plus#247]
It would be nice to have an option to make be one step to both mark done and archive a todo.

**Comment by fabiospampinato** [comment]
I'm not sure it'd be a good idea, it seems a bit overly specific of an option 🤔

In any case I think you can do that today by defining a macro (https://marketplace.visualstudio.com/items?itemName=geddski.macros) and assigning a shortcut to it.

**Comment by fabiospampinato** [comment]
Closing as this is too error prone, as items can't be put back where they were from the archive reliably.
