### ISSUE TITLE
Replace moment.js with date-fns

### ISSUE THREAD

**Issue by jylin** [fabiospampinato/vscode-todo-plus#248]
I think date-fns is now the more modern date library. Some reasons why it's preferable over moment.js: https://www.quora.com/What-is-better-Date-fns-or-moment-js. This is definitely not urgent, but it might be a nice dev experience upgrade to use a newer cleaner API.

As a side note: would you be open to switching to using an opinionated code formatter like prettier?

**Comment by fabiospampinato** [comment]
This could make the extension smaller and start up quicker 👍 I don't really care about what's considered modern nowadays.

> As a side note: would you be open to switching to using an opinionated code formatter like prettier?

No. However at some point I'll have a standalone CLI app for using ESLint with my configuration, that should make adhering to a similar coding style easier.

**Comment by fabiospampinato** [comment]
Closing in favor of https://github.com/fabiospampinato/vscode-todo-plus/issues/313
