### ISSUE TITLE
Add a "Delete" right-click menu option

### ISSUE THREAD

**Issue by jylin** [fabiospampinato/vscode-todo-plus#249]
Would be nice to have "delete" as a right-click menu option. It should just delete the current line if it's a task. I think this would be nice to be more similar to a full task manager like "Microsoft Todo" which has delete as a right-click menu option.

**Comment by fabiospampinato** [comment]
It sounds like something like this is general enough that perhaps the editor itself, or a more general extension, should implement this 🤔

**Comment by fabiospampinato** [comment]
You can use the editor's "cut" command for this basically.
