### ISSUE TITLE
Add option for daily tasks

### ISSUE THREAD

**Issue by BareDesigns** [fabiospampinato/vscode-todo-plus#252]
# Adding option for a daily tag

Looking for assistance with possibly adding an @daily tag. It would simply do the following:

* If daily tag TODO remains unchecked, leave as is
* If daily TODO is completed, it simply becomes "undone" the very next day

Just learning TS so not sure how simple/complex this would be. Any help would be appreciated.

**Comment by fabiospampinato** [comment]
Just put your daily tasks in the same parent project, select them all each day and uncheck them.
