### ISSUE TITLE
Provide original estimation in project summary

### ISSUE THREAD

**Issue by bastibuck** [fabiospampinato/vscode-todo-plus#253]
Hey,

stumbled upon this extension and it's just what I needed to layout my plans before working on a feature. Thx!

I adjusted my project summary text to be `([done]/[all] [percentage]%) | Remaining time est: [est] | Used time: [lasted]`. 

Wish there was something like 
```
[orig-est] 
```
for an original estimation sum in contrast to `est` which displays the open estimation. So I can easily see how far off my guess was at the end. Something like 
```
([done]/[all] [percentage]%) | Remaining time est: [est] | Used time: [lasted] | Estimated time: [orig-est]
```

What do you think? 

Cheers

**Comment by fabiospampinato** [comment]
Sounds reasonable, maybe we should call it `est-total`. PRs welcome 👍

**Comment by bastibuck** [comment]
As my PR in #255 is merged we can close this.

Thanks for adding this to the extension :)
