### ISSUE TITLE
Math support

### ISSUE THREAD

**Issue by dhrunia** [fabiospampinato/vscode-todo-plus#256]
Thanks for the great extension. Coming from Emacs to VScode I have been looking for a replacement to Emacs org mode. Your extension is the closest to it but one thing I miss a lot is the support for math. If you could add support for embedding math similar to what some markdown extensions do it would be awesome. I am new vscode but if you need some help with adding math support I can try if you point me to what needs to be done to achieve that.

**Comment by fabiospampinato** [comment]
I don't think Maths support would make a lot of sense for this extension 🤔 why would you use this extension for rendering maths expressions?

**Comment by dhrunia** [comment]
I keep a todo list of the ideas I am exploring or will explore in future for my thesis. Quite often that involves having some math in the description of that idea. 

Currently, I am using markdown but it doesn't allow have any support for status like todo, done, cancelled etc. I just saw the embedded todos feature and trying to figure if I can make this extension pull from a markdown file. You have any suggestions?

**Comment by fabiospampinato** [comment]
> Currently, I am using markdown but it doesn't allow have any support for status like todo, done, cancelled etc

There's no "cancelled" status there, but there are "pending" and "done" tasks too:

```markdown
- [ ] pending
- [x] done
```

Result:

- [ ] pending
- [x] done

Maybe that's good enough?

**Comment by dhrunia** [comment]
Unfortunately I have been using multiple custom statuses. So just `pending` and `done` are not enough unless I refactor my whole todo list which is cumbersome.

However, the emebedded view is awesome and I managed to get it to show all my different statuses by adding them to the regex. However, I can't seem to figure out how to assign icons to each status. All the `todo` items have a yellow icon next to them which is quite nice and now I am spoiled and trying to figure out how to set such icons on different custom statuses I am using. Is it possible to configure such a thing?

**Comment by fabiospampinato** [comment]
Yeah, you have to update the `"todo.colors.types"` setting too.

I'm closing this as I don't think support for rendering custom maths will be added.
