### ISSUE TITLE
[Feature Request]: Embedded custom tags into todo files

### ISSUE THREAD

**Issue by wimille** [fabiospampinato/vscode-todo-plus#257]
Hi

I've saw that it is possible to define tags into the personnal settings file with following line:
"todo.tags.names": ["critical", "high", "low", "today"], // Special tags' names

However, i'm wondering if it is possible to have custom tags names into each todo file.

I explain myself, i've created a todo list for a project, and i would to assign tasks to engineers. But, according to projects or even during the life of the same project, this list can be evolve. So i'd prefer to update my todo file instead of my personnal setting file.

Regards

**Comment by fabiospampinato** [comment]
You can put that settings into `./your-project/.vscode/settings.json`.
