### ISSUE TITLE
Extension is not working on a proxied network

### ISSUE THREAD

**Issue by OrelsProjects** [fabiospampinato/vscode-todo-plus#263]
I am using the extension in a proxied network, and I finally managed to get it to be installed in vs code, after downloading for github and packaging it into a vsix file.

The problem is I get the following error:
"Activating extension 'fabiospampinato.vscode-todo-plus' failed: Cannot set property 'preciseDiff' of undefined."
And when I try to run a command, it says:
"Error: command 'todo.viewFilesExpand' not found'

Any ideas?

**Comment by fabiospampinato** [comment]
`moment` broke things in a minor release. Try again now, it should work.

Btw you are kind of wasting your time with this, you could just download precompiled vsix files from the marketplace, and they are really just zip files you can unpack and look at the code yourself.
