### ISSUE TITLE
Embedded view does not update

### ISSUE THREAD

**Issue by andrewufrank** [fabiospampinato/vscode-todo-plus#267]
I use `todo+` 4.17.1 and do not understand how to refresh the embedded todo list. The feature is a great idea and it found all the todos in my files originally and shows them. In the mean time I have added todos in some of the files, but these do not show. How can i force 
the tool to update the list? I assume you built it to update automatically; what could prevent it to do so? 
thank you for a valuable tool!

**Comment by fabiospampinato** [comment]
It should indeed update itself automatically, I'm not sure why it isn't doing that for you 🤔 Can you reproduce even when opening only a folder containing just one file for example?

**Comment by DanteMarshal** [comment]
I can confirm this bug, But it seems that this only happens in Large projects with huge number of files.
I checked this in a Single-file project and it indeed does update automatically, But on my bigger project (Somewhat like 100'000 files or so ?) it does not update at all.

**Comment by zdima** [comment]
I can' conform the issue with a project with a single file.
VS Code:
   Version: 1.54.1 (Universal)
   Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
   Date: 2021-03-04T22:42:18.719Z
   Electron: 11.3.0
   Chrome: 87.0.4280.141
   Node.js: 12.18.3
   V8: 8.7.220.31-electron.0
   OS: Darwin arm64 20.3.0
TODO+ v4.18.3

**Comment by fabiospampinato** [comment]
I can't reproduce the problem, it's working fine for me.

Maybe having a file that you guys use to reproduce the problem could be useful.

**Comment by fabiospampinato** [comment]
Happy to reopen as soon as somebody shows me a way to reproduce this.

**Comment by zdima** [comment]
I was away and didn't have access. Attached is screen cast to reproduce the issue.

https://user-images.githubusercontent.com/298260/113461097-36bdbf00-93e9-11eb-92a0-189001f5cb40.mov
