### ISSUE TITLE
Behavior Improvement: Adding @done and other tags with shortcut should move the cursor to the end of the tag

### ISSUE THREAD

**Issue by sahil48** [fabiospampinato/vscode-todo-plus#269]
When I press Alt-d, the `@done` tag is added, but the cursor is before `@` instead of at the end of the tag. When I press Alt-d, I usually intend to press enter to add a new line. Instead, the tag also goes to the next line.

**Comment by fabiospampinato** [comment]
Use Ctrl+Enter/Cmd+Enter instead of just Enter in these situations.

I think it's generally more appropriate for the cursor to attempt to remain where it was before you marked a todo as done or not.

**Comment by sahil48** [comment]
That makes sense. I have it working now. However, ctrl-enter for new line was conflicting with Todo: Toggle Box in Windows.

**Comment by fabiospampinato** [comment]
Oh right 🤔 well spotted

**Comment by sahil48** [comment]
Life must be great on the mac side of the universe! 😉
