### ISSUE TITLE
Support for .taskpaper and .tp extension

### ISSUE THREAD

**Issue by metbril** [fabiospampinato/vscode-todo-plus#27]
The taskpaper app uses the .taskpaper or .tp extension. Please support this for the extension, too.

**Comment by fabiospampinato** [comment]
Thanks for the suggestion, I'll probably add support for this.

**Comment by fabiospampinato** [comment]
I've added support for the `.taskpaper` extension in v1.8.0.

I've left behind the `.tp` extension though, I've downloaded the latest version of TaskPaper from their website, created a file, and changed its extension to `.tp`, and it's not even recognized by TaskPaper itself. Also this extension seems to be used by Turbo Pascal, but that's a minor thing.

Of course you can always change the language mode from within VSC and use Todo+ with any extension you like.
