### ISSUE TITLE
Error in new versions of VSCode

### ISSUE THREAD

**Issue by Nick-Hopps** [fabiospampinato/vscode-todo-plus#275]
[fabiospampinato.vscode-todo-plus]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api fabiospampinato.vscode-todo-plus

**Comment by fabiospampinato** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/102170#issuecomment-658041160

I think they fixed it already.
