### ISSUE TITLE
Embedded View - Show Only Active File Not Working on Windows

### ISSUE THREAD

**Issue by wchisenski** [fabiospampinato/vscode-todo-plus#277]
I use the embedded view heavily to track todos within files. Utilizing the default **"Show All Files"** view works as designed, but when I toggle to **"Show Only Active File"** it simply states `No embedded todos found` in the window. I've installed different versions going back to 4.14 and haven't found one that works.

**Comment by fabiospampinato** [comment]
Did you save the file in question? https://imgur.com/a/Zbgd4hE

**Comment by wchisenski** [comment]
Hi Fabio,

Thanks for taking a look and posting the quick video clip. I noticed you were on macOS, so I tested the behavior on my MacBook Pro and found it to behave **as expected**. Although I double checked on Windows 10 and verified the open file was saved and it still listed `No embedded todos found`. Thoughts on why it would be platform specific?

**Comment by fabiospampinato** [comment]
> Thoughts on why it would be platform specific?

None unfortunately 🤔

**Comment by wchisenski** [comment]
Hi @fabiospampinato,

Attaching some screenshots to show you what I'm seeing between macOS and Windows. Unfortunately, I only have a single Windows device (issued from work) -- so I'm wondering if it could be a security setting/GPO or something else causing the behavior.

## macOS (Working)

### Embedded Todo Showing All FIles
<img width="566" alt="todo-all-files-macos" src="https://user-images.githubusercontent.com/53623427/94054876-0db0d780-fd91-11ea-8fcf-fe73f70eb2e8.png">

### Embedded Todo Showing Current Open File
<img width="565" alt="todo-current-file-macos" src="https://user-images.githubusercontent.com/53623427/94054953-24572e80-fd91-11ea-8d95-73eae300ba9b.png">

## Windows

### Embedded Todo Showing All Files (Working)
![todo-all-files-windows](https://user-images.githubusercontent.com/53623427/94055003-38029500-fd91-11ea-8933-90a6c22d76f2.png)

### Embedded Todo Showing Current Open File (**Not Working**)
![todo-current-file-windows](https://user-images.githubusercontent.com/53623427/94055101-55cffa00-fd91-11ea-8b6b-14246b1ee04f.png)

**Comment by Dayw81** [comment]
> [...] if it could be a security setting/GPO or something else [...]

Just want to chime in to report the same problem on three different machines with a standard Windows 10 Pro installation.

**Comment by fabiospampinato** [comment]
PR welcome, I don't currently have the time to work on this.

**Comment by regs01** [comment]
filePath and activeFilePath are using different slashes.
<img width="362" alt="Code_2020-10-09_23-24-57" src="https://user-images.githubusercontent.com/10468217/95628528-e6435580-0a86-11eb-94b3-c95daba673a1.png">

**Comment by regs01** [comment]
#294

**Comment by regs01** [comment]
vsix for the time while waiting an update
[vscode-todo-plus-4.18.0.zip](https://github.com/fabiospampinato/vscode-todo-plus/files/5398350/vscode-todo-plus-4.18.0.zip)

**Comment by fabiospampinato** [comment]
It should be fixed by in v4.18.1, thanks for a PR from @regs01.
