### ISSUE TITLE
Change plain text color

### ISSUE THREAD

**Issue by 1bionix1** [fabiospampinato/vscode-todo-plus#279]
Hi,

I would like to know if it's possible to change the color of the plain text? I have a dark background and the plain text color is too similar and hard to read.

Thank you
![image](https://user-images.githubusercontent.com/32801903/88403022-edb56580-cd99-11ea-8e0c-f4aeda6d384f.png)

**Comment by fabiospampinato** [comment]
Yes, I think you have to set the "todo.colors.comment" setting.

**Comment by davidzoli** [comment]
Any chance, we will get an option for the color of the todo text? This is the color of the box and the "Simple" text on the image.

Now I get the Done tasks "highlighted" by a color, but I want to highlight the tasks I have to do yet. 
I can set the Done to a grayish color, but now I cannot make the todos more visible than white.

**Comment by fabiospampinato** [comment]
@davidzoli that's just not decorated, it uses the same color defined in your theme for plain text. I suppose we could decorate it, but I'm not sure it's worth it and whether or not there will be any conflict with the other decorations 🤔

**Comment by davidzoli** [comment]
I see. Thank you for the explanation.
Now I'll try to modify the theme to set a color for the plain text only for a todo file/language.

**Comment by fabiospampinato** [comment]
@davidzoli I'm not sure that's possible 🤔 What color would you like to use for the non-completed tasks?

**Comment by davidzoli** [comment]
@fabiospampinato To be honest, I'd use the color of the Done status to make the todo more visible and would "fade out" what is Done with some grayish color (like the comment on the image).

I can understand if introducing a new color for the "boxed" lines like "todo.colors.todo" can lead to performance issues and/or complicated logical semantics.

I've already set my done color to a grey one. White and grey is a kind of a solution already. If there is a workaround to colorize a whole line with some existing tool we have already (tag, type, something) that would perfect for me.
Maybe I'll swap the box and cancel symbols and with this I'll be able to colorize the non-completed (technically cancelled). 
I'll try something.

**Comment by fabiospampinato** [comment]
@davidzoli I actually have made another [extension](https://github.com/fabiospampinato/vscode-highlight) for dynamically highlighting stuff, you could try using that for highlighting non-done tasks, however I think there will be conflicts where the colorization performed by vscode-highlight takes precedence over the one performed by vscode-todo-plus, or vice versa, in order to implement this properly I think vscode-todo-plus should take care of that.
