### ISSUE TITLE
Archive removes non empty project for 'todo.todo'

### ISSUE THREAD

**Issue by metbril** [fabiospampinato/vscode-todo-plus#280]
When using the filename `something.todo` (mind the extension) then archiving works just fine. Projects with remaining tasks are left untouched.

But when you use a filename of `todo.todo` (where both filename and extension are similar), the project title is removed when archiving.

Reproduce:

1. Create test file `test.todo` with 3 todos
2. Mark first todo done
3. Archive
4. Save file
5. Rename file to `todo.todo`
6. Mark second todo done
7. Archive

**Comment by fabiospampinato** [comment]
Can't reproduce https://i.imgur.com/shP3YK8.mp4

**Comment by metbril** [comment]
I'll try to upload a clip, too.

**Comment by metbril** [comment]
At first, I couldn't reproduce. But now I know what's different.
Initially I create a test project with indented task, by hitting <tab>. This inserts 4 spaces. When marking as @done, and then Archive, al goes well. But when I indent tasks in the project with 2 spaces, the project title is removed.


https://filebin.net/ya820gnhc27wsndb

**Comment by fabiospampinato** [comment]
Does setting `"todo.indentation"` properly fix the issue for you?

**Comment by metbril** [comment]
I'm not sure. The default seems to be 2 spaces, and that's what I like. A tab after creating a project gives me 4 spaces, and auto indentation aftwards.

If I change to setting to "xx" that only seems to be used for the archiving, and nothing else.

**Comment by fabiospampinato** [comment]
You need to use a consistent indentation _and_ tell the extension what that indentation is. You are using 4 spaces but the app is configured by default to only use 2, since you also say that 2 spaces is what you like then you need to configure vscode to write 2 spaces for a tab, otherwise the thing breaks.

Don't forget to update the existing document with the configured indentation.
