### ISSUE TITLE
Show statusbar all the time

### ISSUE THREAD

**Issue by liangjiancang** [fabiospampinato/vscode-todo-plus#281]
I mean `todo.statistics.statusbar`.

Don't just display it when you open a todo file, I need to always display it when you open other files in the entire project.

**Comment by fabiospampinato** [comment]
🤔 that's not really implementable in the general case, like you have 10 todo files which one should we show in the statusbar? and why? Perhaps a setting could be added about this.

**Comment by liangjiancang** [comment]
> 🤔 that's not really implementable in the general case, like you have 10 todo files which one should we show in the statusbar? and why? Perhaps a setting could be added about this.

The sum of them.

Imagine if you can't see how many unfinshed todos anytime, they'll always be selectively ignored.

**Comment by fabiospampinato** [comment]
Closing as I don't see how it can be implemented effectively in general.

**Comment by antonsoroko** [comment]
@fabiospampinato 
btw
https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree has this feature for several use cases (total, per tag, top 3, for current file). maybe it can be borrowed from there.

also i think "for current file" is quite enough and should not be "slow" to compute.

**Comment by jdamboeck** [comment]
Yeah this would be incredibly useful.
