### ISSUE TITLE
Commands not found 

### ISSUE THREAD

**Issue by DeXtr0niC** [fabiospampinato/vscode-todo-plus#285]
Just wanted to try out the extension. Sadly it is not working for me right now with a strange behaviour. Almost every action (except 'Todo: Open') throws a 'todo.xxxx command not found'-Error.  

![Screenshot_2020-08-19_10-57-30](https://user-images.githubusercontent.com/8284140/90614926-9de88380-e20b-11ea-937c-9de77b6fc66c.png)

**VSCode Setup:**
Version: 1.48.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.18.0-193.6.3.el8_2.x86_64

**Comment by fabiospampinato** [comment]
Do you see any errors in the debug pane? 
Does it break also when opening things like an empty folder?

**Comment by DeXtr0niC** [comment]
Issue dissappeared. No idea what caused it sadly.
