### ISSUE TITLE
Todo's not getting highlighted

### ISSUE THREAD

**Issue by mariusbolik** [fabiospampinato/vscode-todo-plus#286]
First of all, thank you for this great plugin. I installed it and also restarted VSCode. But what I need to do to highlight the Todo's in my code?

<img width="461" alt="Bildschirmfoto 2020-08-20 um 11 22 00" src="https://user-images.githubusercontent.com/39862171/90752325-8676cc80-e2d7-11ea-8fa1-a7ca5e256351.png">

Best Regards
Marius

**Comment by DeXtr0niC** [comment]
This extension is not for highlighting todos, you'll need another extension for this. Check out 'Highlight' by the same author as this one.

**Comment by mariusbolik** [comment]
Oh okay thank you. But also "Highlight" does not highlight anything for me. I'll open an issue in the corresponding repo.
