### ISSUE TITLE
Register Commands for keyboard shortcuts

### ISSUE THREAD

**Issue by b1m1nd** [fabiospampinato/vscode-todo-plus#290]
I might have missed it but I can't find the actual commands for alt+d ect. I would like to be able to assign them to key combo for use with vim extension.
IE:
```
		{
			"before": ["<leader>", "d"],
			"commands": ["todo.action.markdone"] <--- something like this?
		},
```
if this exists can I get a list maybe put it in the readme for others that want to rebind or use like my self"

**Comment by fabiospampinato** [comment]
Static commands like that are listed in `package.json` https://github.com/fabiospampinato/vscode-todo-plus/blob/2474fd7fdbcbc39a636c7252117856c9f2a20d76/package.json#L626-L772
