### ISSUE TITLE
@created tag - not working after enabled

### ISSUE THREAD

**Issue by spmartin42** [fabiospampinato/vscode-todo-plus#291]
Hello!

I've enabled "@created" in extension settings, but I can't seem to get it to work as intended (adding timestamp). I'm also wondering if there's a keyboard shortcut for "@created," (as there is for "@started").

Thanks, and really appreciate your work on the extension!

**Comment by fabiospampinato** [comment]
Sharing reproduction steps alongside your configuration for the extension would help me help you.

**Comment by spmartin42** [comment]
My bad - discovered @created and timestamp is appended to new todo items after it is enabled in settings. Will close this issue. 

Could I suggest adding some documentation (maybe in settings) that describes how @created works after it's enabled? Thanks again!
