### ISSUE TITLE
Publish to OpenVSX

### ISSUE THREAD

**Issue by ItsDrike** [fabiospampinato/vscode-todo-plus#296]
Arch Linux (Linux based operating system distribution) has decided to switch the marketplace for extensions from the [MS Visual Studio Marketplace](https://marketplace.visualstudio.com) to [OpenVSX](https://open-vsx.org/) in [this commit](https://git.archlinux.org/svntogit/community.git/commit/trunk?id=b62a02ec645f16528c0269faf12e362a55efda75).

[Here](https://www.gitpod.io/blog/open-vsx/) are some more details about OpenVSX, its goal, and why it was created

For that reason, I can't use your extension anymore, could you publish on OpenVSX too?
(It's typically just a matter of running `npx ovsx publish` you can also check the [full guide for publishing](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions))

**Comment by fabiospampinato** [comment]
I don't have time for third-party marketplaces, feel free to reupload my extensions there yourself.

**Comment by ItsDrike** [comment]
It shouldn't be hard to upload there you might even be able to set up an automated action to do that for you on release and I'm asking for this because as of `code 1.49.1-1` Arch Linux decided to stop supporting the MS Visual Studio Marketplace.

This means no one who's using Arch Linux or any other Linux distribution based on Arch Linux (such as the popular Manjaro distribution) won't be able to have access to your extension at all since the version of the official repository of visual studio code is now the one with Open VSX. The only other option for arch users would be to use old version of vscode which realistically won't happen.

I think it might be worth it for you to support it there too since I'm pretty sure there are more users than just me who are using arch based Linux and you'll just be losing potential new users if you don't upload it there too. Not only that but OpenVFX is also the biggest library for a more open sourced vscode since while vscode core is open, the editor itself isn't, and almost all of the alternatives built on the open core of vs-code will be using OpenVFX.

The upload process is really not at all complicated and shouldn't take you too long, all you need is the access token from OpenVSX, then just issue `npx ovsx create-namespace <authorname> -p <token>` after which you can easily upload `npx ovsx publish <file> -p <token>` where `file` is your `.vsix`  extension, if you don't have it built yet, you can just build it from the source using the common `npm install` and run `npx ovsx publish -p <token>` in the projects root.

While I could upload it there myself, I don't like the idea of stealing your project like this and since this really is a very easy process I think it's worth it for you to upload it yourself.

I really like your extension and i would like to be able to continue using it even on arch based distributions, so I'd be really glad if you changed your mind and decided to upload it.

**Comment by fabiospampinato** [comment]
> you'll just be losing potential new users if you don't upload it there too

It's not like that matters much to me anyway, like as far as I know I can't pay rent with potential users or github stars or installation counters.

> While I could upload it there myself, I don't like the idea of stealing your project like this and since this really is a very easy process I think it's worth it for you to upload it yourself.

It's not stealing, all my extensions are released under the MIT license, you are 100% free, and I encourage you, to upload all my extensions elsewhere.

In fact something automated like that that works for all open-source vscode extensions would probably be of great value to OpenVSX I guess. I have no interest nor the time currently to generalize the release of my extensions to support every alternative marketplace out there.
