### ISSUE TITLE
Making project VCS ignore the TODO files created/modified by the extension

### ISSUE THREAD

**Issue by saurabhsuniljain** [fabiospampinato/vscode-todo-plus#299]
Objective: 

For any version-controlled repositories, it would be better if the extension finds a way such that all the created/modified files (TODO files) by the extension by default are ignored by the underlying VCS (git, svn, etc)

For Git: 

- Adding to the `.gitignore` file didn't seem to correct way to me because extensions are personal preferences and for that, any project resource shouldn't be modified and checked in to origin / upstream repo.
- So after searching for some time and I found a [way](https://stackoverflow.com/a/653489) which makes Git ignore a file and at the same time this is limited to the user's local clone of the repository: Add the file path/pattern to `.git/info/exclude`.
- There is one more way (`core.excludesfile` setting) suggested in the above StackOverflow link but I didn't explore this as `.git/info/exclude` seemed to satisfy my needs.

I guess for other VCS as well there should be ways like these (I haven't used anything apart from Git).

Obviously, extension directly modifying .git or any VCS resource isn't correct, but this should be allowed to be done with the user's consent and can be under a feature flag/extension setting.

**Comment by fabiospampinato** [comment]
Out of scope.
