### ISSUE TITLE
How can I copy the styles?

### ISSUE THREAD

**Issue by felocru** [fabiospampinato/vscode-todo-plus#3]
Hello, I'm not sure if it's possible; But I used an extension very similar to yours (by the way, excellent extension) that could copy all styles of the document. That is, the color.
Is it possible to do this too?

For example, I want to copy these tasks to the inbox of gmail.

Thank you.

**Comment by fabiospampinato** [comment]
Can you link me the other extension you were using?

I guess I might implement the same functionality, if it doesn't require too much work.

**Comment by felocru** [comment]
Hi, thanks for your prompt reply.
The extension I used is:
[https://marketplace.visualstudio.com/items?itemName=sandy081.todotasks](url)

**Comment by fabiospampinato** [comment]
I see, I was using that extension as well before making my own.

I made some tests, and this is what the style of a sample todo file looks inside VSC and Gmail when using todotasks:

<img width="358" alt="screen shot 2017-09-03 at 15 35 32" src="https://user-images.githubusercontent.com/1812093/30003499-2efa445a-90be-11e7-9ff3-8cd7c8da39d9.png">

<img width="448" alt="screen shot 2017-09-03 at 15 35 42" src="https://user-images.githubusercontent.com/1812093/30003501-3169e2e0-90be-11e7-8dd4-e882b61f29bb.png">

And here it's the same but with Todo+:

<img width="359" alt="screen shot 2017-09-03 at 15 36 13" src="https://user-images.githubusercontent.com/1812093/30003502-33c16dce-90be-11e7-9e2a-7bf6b295e1c7.png">

<img width="449" alt="screen shot 2017-09-03 at 15 36 44" src="https://user-images.githubusercontent.com/1812093/30003503-369629ae-90be-11e7-841e-01069c4a7863.png">

todotasks doesn't work perfectly, but it definitely still looks better. There's a difference in the way this two extensions are implemented, todotasks is way more strict (no custom symbols, tags or colors) but this makes it easy for VSC to copy some of the style as well, Todo+ is more customizable, in a way that VSC can't currently automatically copy the style as well with the text.

I think it's possible to add a `Todo: Copy with Style" command that copies the style as well, but it looks like it requires a fair amount of time to implement it, therefor I'm not going to implement it in the immediate future. I'll be happy to accept a well-done PR or to implement it at some later point in the future though. 

Thanks for the suggestion.

**Comment by fabiospampinato** [comment]
I've opened an [issue](https://github.com/Microsoft/vscode/issues/33747) in VSC's repository about this. Let's see what they think about it.

**Comment by felocru** [comment]
I understand, I hope this feature will soon be applied. Since it would be very easy to share the tasks.
Thanks for your time.
