### ISSUE TITLE
Feature request: Add new special tags (or documentation about how to do it)

### ISSUE THREAD

**Issue by TheTechOddBug** [fabiospampinato/vscode-todo-plus#302]
I would like to have the ability to create new special tags with its corresponding configuration for colors or, if this is already implemented, i want to have some documentation about how to do it.

Thank you very much in advance.

**Comment by House-of-Leaves** [comment]
It can be done by adding to the todo.tags.names, todo.colors.tags.background, and todo.colors.tags.foreground arrays in Settings or your settings.json - just add to the arrays in the right order and restart VSC and it works great.

**Comment by fabiospampinato** [comment]
Closing as @House-of-Leaves addressed it.
