### ISSUE TITLE
Todo box string is replaced by ? every time I reopen the todo file

### ISSUE THREAD

**Issue by spfeifer222** [fabiospampinato/vscode-todo-plus#305]
Writing a toto file works fine including changing the status of the tasks by keyboard shortcuts Alt+[Enter, D, C] etc., but if I save the file with content
```
Helpdesk:
	
	☐ IUCLID Beschreibung MIM
	
	Internetinhalte FG32 veröffentlichen:
		☐ deutsche Version beenden
		☐ englische Übersetzung 
```

and reopen, all todobox strings are replaced by ?

```
Helpdesk:
	
	? IUCLID Beschreibung MIM
	
	Internetinhalte FG32 veröffentlichen:
		? deutsche Version beenden
		? englische Übersetzung 
```
This seems to be an encoding problem. My standard encoding is `iso88591`.

**Comment by fabiospampinato** [comment]
It looks like that box character isn't supported properly by your encoding, try setting a different character for that, the supported ones are listed in the readme.
