### ISSUE TITLE
Add support for @9:30-10:00 notation for (manual) timekeeping

### ISSUE THREAD

**Issue by Holo-Viktor** [fabiospampinato/vscode-todo-plus#307]
```
today: (sum)
  ☐ work @900-1700 (sum)
    break
  ☐ party @1930-200 (sum)
  ☐ sleep @200-800 (sum)
```
Possibly with support for the following syntax alternatives:
`@900-1930` (my preference), `@9:00-19:30`, `@900am-730pm`, `@9:00am-7:30pm`

The `(sum)`s would be replaced by the actual sums the way it is currently done for elapsed timers/`@lasted`

The reasons why I want this is that I prefer to round the time to 15min, the date creates a lot of noise which is distracting, and I simply don't need it and I don't want to do the extra work of counting the times together myself, I just append the current time and start the next task.

**Comment by Holo-Viktor** [comment]
It would be also super cool if this worked as well:
```
today: (sum)
  ☐ @ 900-1700 work (sum)
    break
  ☐ @1930- 200 party (sum)
  ☐ @ 200- 800 sleep (sum)
```

**Comment by fabiospampinato** [comment]
🤔 I don't know I guess that's a bit handier than doing the sum yourself and inserting that in an "elapsed" tag manually. It seems too specific though, the extension has already some built-in features for timekeeping, I'd rather make them more powerful than adding a second way to keep track of time.
