### ISSUE TITLE
"Open symbol by name" not fuzzy matching

### ISSUE THREAD

**Issue by michaelmagistro** [fabiospampinato/vscode-todo-plus#309]
If I have a project in my tasks for example:

```
Taxes 2021:
    [ ] export data
    [ ] aggregate data
```

and search by symbol `Ctrl + R`, I can find the project within my tasks only if I write the search in order (for instance `tax 21` will locate the project, but `21 tax` will not)

Implementing fuzzy search for project names (symbol names) for Todo+ would be immensely useful as this is the method used in Plaintasks for Sublimetext (which is the spiritual successor for Todo+ as I understand it).

Furthermore, it seems the fuzzy search behavior needs to be resolved at the extension level:
https://github.com/Microsoft/vscode/issues/33746
https://github.com/microsoft/python-language-server/issues/697

**Comment by fabiospampinato** [comment]
Unfortunately that's a stupid decision on vscode's end, it doesn't make sense to reimplement fuzzy searching for each extension, complain with them about it.
