### ISSUE TITLE
On hold status

### ISSUE THREAD

**Issue by maliur** [fabiospampinato/vscode-todo-plus#31]
I often find myself the need to put some task on hold as I'm waiting for someone else to do something before I can proceed on that task. As for know i just put a comment below to remind myself but it would be great if you could put another status with colouring to distinguis it from other tasks that I haven't done yet.

**Comment by fabiospampinato** [comment]
You mean adding another special tag like `@critical` or `@high`?

**Comment by maliur** [comment]
No I meant more like the done and cancel effect where to whole text gets a new color, maybe yellow? and maybe "blocked" is a better wording then "on hold".

**Comment by fabiospampinato** [comment]
I like this idea, but it's not a feature I personally would use and I currently don't have the time for implementing it. I'll be happy to merge a PR that implements it though :)

**Comment by fabiospampinato** [comment]
I'm closing this in favor of https://github.com/fabiospampinato/vscode-todo-plus/issues/59, which is more general.
