### ISSUE TITLE
For the TODO's with @started tag, move all to a new section called INPROGRESS

### ISSUE THREAD

**Issue by sharoha** [fabiospampinato/vscode-todo-plus#310]
Similar to archive functionality where upon pressing `ctrl+shift+A` all the @done categories moves to Archive, we move to a new category called INPROGRESS for the todo's with category @started upon pressing 'ctrl+shift+P'.    
I have explored that this feature is not available currently. Can this be added as a new feature?
Happy to raise a PR.

**Comment by fabiospampinato** [comment]
I think it would be better to highlight started tasks better instead. The problem with this suggestion is that that's basically a second archive, with the difference that once tasks are moved to the archive usually there's no need to move them back, but I'd expect tasks to be moved in and out from "inprogress" fairly frequently, and that can't be implemented automatically, like you can't put an in progress task back exactly where it was before.
