### ISSUE TITLE
TODO format

### ISSUE THREAD

**Issue by sad2project** [fabiospampinato/vscode-todo-plus#312]
You don't mention how to format the TODOs in the TODO file. I'm especially curious about nested TODOs

**Comment by fabiospampinato** [comment]
Checkout the readme in this repo, it should make things clearer. Feel free to open a separate issue about writing a formal spec for the language.

**Comment by sad2project** [comment]
I HAD looked at. I figured the special symbols used for the checkboxes and such weren't what was literally in the file, that the application was making it look that way. Therefore, maybe there was also something special to designating nesting. But after clicking on and looking at the actual demo file, I see now you're just using the special characters.
