### ISSUE TITLE
Moving lines messes up indentation

### ISSUE THREAD

**Issue by JacksonKearl** [fabiospampinato/vscode-todo-plus#315]
Issue Type: <b>Bug</b>

Text: 

```
Week of Apr 12:
	Monday:
		☐ MD Powered Item contributions
		☐ Refine Details page layout

	Tuesday:
		☐ Start menu items contribution
		☐ Fix async behaviour of content overrides
	Wednesday:
	Thursday:
	Friday:
```

Use Cmd+down to move the "Refine details page layout" entry from monday to tuesday, see that both it and tuesday gain an indentation level.

Extension version: 4.18.3
VS Code version: Code - Insiders 1.56.0-insider (48387dfc3d691558404cff1ea2582e3862a40080, 2021-04-13T05:14:30.947Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (2.80GB free)|
|Process Argv|--crash-reporter-id b3a99796-4b23-4fc2-82cf-c02cd1d9b936|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
wslfolderdoccf:30278406
vspre833cf:30267465
pythonptprofiler:30281269
vshan820:30276952
pythondataviewer:30285072
vscus158cf:30286554
vscgsv2:30286872

```

</details>

**Comment by fabiospampinato** [comment]
Duplciate of https://github.com/fabiospampinato/vscode-todo-plus/issues/113
