### ISSUE TITLE
How do I customize the TODO type?

### ISSUE THREAD

**Issue by SparkElf** [fabiospampinato/vscode-todo-plus#319]
![image](https://user-images.githubusercontent.com/58362707/115357854-a2789800-a1ef-11eb-8c08-a7dc7b3f6652.png)
it does't work
![image](https://user-images.githubusercontent.com/58362707/115357903-b02e1d80-a1ef-11eb-8fb1-6601e726dcdd.png)

**Comment by fabiospampinato** [comment]
This extension don't highlight comments, you should probably use this other one for that: https://github.com/fabiospampinato/vscode-highlight
