### ISSUE TITLE
I can't find the way of changing the color of normal text in a todo

### ISSUE THREAD

**Issue by albu77** [fabiospampinato/vscode-todo-plus#32]
I Can't find the way of mofifying the color othe normal text (the yellow arrow is showing). Is there a way in the user setting of Visual Code?
![todocolor](https://user-images.githubusercontent.com/624802/36218294-28525c38-11b4-11e8-9b85-b58291a6fc90.png)

**Comment by shvfn** [comment]
Hey, it's in the VSCode settings:

"todo.colors.comment": "#aa0000",

You need to replace this in your user settings and then restart VS Code so that the changes apply.

**Comment by fabiospampinato** [comment]
As @shvfn correctly points out you can change the color of comments with `"todo.colors.comment": "#aa0000"`. 

Your title mentions "normal text" and in your screenshot I see an orange box around a normal todo, that color comes from the syntax theme you're using -- maybe there's an option for customizing that, I'm not sure, you should check out [this page](https://code.visualstudio.com/docs/getstarted/theme-color-reference).

**Comment by mpgn** [comment]
Looks like the setting `"todo.colors.comment"` doesn't change anything on my side

![image](https://user-images.githubusercontent.com/5891788/62958091-4e03ff00-bdf6-11e9-81fe-8952ce7ff657.png)

Did something change ?
