### ISSUE TITLE
Doesn't work with  extension vscode-highlight

### ISSUE THREAD

**Issue by ussu99** [fabiospampinato/vscode-todo-plus#320]
I'm using vscode-todo-plus and vscode-highlight. 

But highlighting from vscode-highlight is not working for .todo-files.

Im trying to highlight e.g. Numbers in Text or .todo files. Highlighting works on Textfiles perfectly.

But with a .todo file a number are highlighted not as expected:
![image](https://user-images.githubusercontent.com/6134967/115907973-dbbc3c80-a469-11eb-8b15-da0f9acb6c7f.png)

On a textfile the highlight is as expected:
![image](https://user-images.githubusercontent.com/6134967/115908030-eaa2ef00-a469-11eb-94f7-5b63036a8c69.png)

Am i missing a toggle?

im Using following Settings:
```json
// number
      "([0-9]+)": {

      "decorations": [
      {
        "backgroundColor": "#292A0A",
        "color": "#6fe74c",
        "fontWeight": "bold"
      }
    ]
```

**Comment by fabiospampinato** [comment]
Both extensions are highlighting things in a similar way so they conflict with each other, it's not currently possible to have those extensions working at the same time on the same file.
