### ISSUE TITLE
[shortcut] typing `c` and pressing `tab` creates a `@critical` tag

### ISSUE THREAD

**Issue by dnlw07** [fabiospampinato/vscode-todo-plus#322]
Hello,
would it be possible to implement shortcut allowing to create a `@critical` tag (and other) by typing 'c' and pressing `tab`?
This trick is possible in analogical extension PlainTasks in Sublime Text.

**Comment by fabiospampinato** [comment]
I think it would be better to implement this on top of some other extension, this should be doable already.
