### ISSUE TITLE
Additional `question` status (analogical to `done` and `cancelled`)

### ISSUE THREAD

**Issue by dnlw07** [fabiospampinato/vscode-todo-plus#323]
Hello,
could you please implement additional status like `pending` or `question`.

So far there are three states: 
☐ `active`, 
✔`done` 
✘ `cancelled`.

It would be awesome if status `question` also exist:
`?` question

**Comment by fabiospampinato** [comment]
What's the difference between `pending` and `active`?

A question/indeterminate state could maybe get implemented, what would be the usefulness of that though?

**Comment by dnlw07** [comment]
There is no need to have active/pending tag.  I only want to have additional tag `@question` cuz sometimes some task needs to be discussed with more ppl to gather aditional information.

**Comment by fabiospampinato** [comment]
I see, tags are already fully customizable, check the readme.
