### ISSUE TITLE
Tag Padding

### ISSUE THREAD

**Issue by WilRoberts** [fabiospampinato/vscode-todo-plus#326]
**[Question]**
Is there a way to pad tags, via configuration, with a leading space and trailing space, such that these padded spaces are also highlighted?

The reasoning behind me asking this is that when the text is small, and in my case using darkmode and you create a tag that has highlighting the first and last characters of the tag seem to almost bleed into the background, which isn't as visually appealing as possibly one that is more padded, having a fuller block of highlighting containing the tag.

**Comment by arkadianriver** [comment]
Not in the exposed settings.

And even if you wanted to code it in, it looks like VS Code allows only certain styles for [this object](https://code.visualstudio.com/api/references/vscode-api#DecorationRenderOptions). An outline could be applied, but it expands vertically as well, and the background is already at the max row height vertically. Here is what it looks like with just a 4px outline ...

![image](https://user-images.githubusercontent.com/6054194/119210809-35ad2380-ba63-11eb-9d93-fba96e1bb17f.png)

Another not-so-ideal solution would be to add a period or some small character to the end of your custom tag names: `"todo.tags.names": ["critical.", "high.", "low.", "today."],`

![image](https://user-images.githubusercontent.com/6054194/119210990-6d689b00-ba64-11eb-9821-687a7080852b.png)

**Comment by WilRoberts** [comment]
Got something working along the lines of what I was envisioning. Required code changes as expected but I think it could be configurable / togglable through the exposed settings with a few additions.

**Padding & Borders**
![image](https://user-images.githubusercontent.com/15734898/120883825-6a65c280-c5ad-11eb-9d1d-705bc6159e24.png)

**Padding & No Borders**
![image](https://user-images.githubusercontent.com/15734898/120883876-bca6e380-c5ad-11eb-8b0f-d0ef9672fcc1.png)

**Current**
![image](https://user-images.githubusercontent.com/15734898/120884144-24a9f980-c5af-11eb-944d-db348d360ed7.png)


**Note:** _I also tried to remove the @ from the tag but couldn't get that working without either breaking the decorating or completion functionality._
