### ISSUE TITLE
Heads-up: "workbench.editor.languageDetection" hijacks (changes) language for TODO file

### ISSUE THREAD

**Issue by vfonic** [fabiospampinato/vscode-todo-plus#332]
Basically (since VS Code 1.60.0) what happened is that I opened my `TODO` file as usual and the language got switched to Markdown and my autoformatting on save kicked in and changed the layout of my TODO file.

I finally found a way to prevent this auto language switching like this:

```json
  "[todo]": {
    "workbench.editor.languageDetection": false
  },
```

I also reported this in the VS Code repo: https://github.com/microsoft/vscode/issues/132571

**Comment by fabiospampinato** [comment]
It looks like that got fixed upstream.
