### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by sveins12** [fabiospampinato/vscode-todo-plus#333]
Suddenly today I discovered that the keyboard shortcuts in Todo+ is not working. I have tried Ctrl-ENTER (create new todo) Alt-D (mark as done). I can't get them to work.

Running on Windows 10

**Comment by frimmy** [comment]
same problem, using macOS Catalina

**Comment by frimmy** [comment]
looks related to https://github.com/fabiospampinato/vscode-todo-plus/issues/331#issuecomment-913090460

Fixed it by setting the language mode of the file to `Todo`
