### ISSUE TITLE
Embedded todos from project root

### ISSUE THREAD

**Issue by brainz80** [fabiospampinato/vscode-todo-plus#345]
Would be nice if one wouldn't have to give the entire path of the file for the embedded todo to work.

Now:

```ruby
@file:///Users/User/Documents/Projects/Docker/project1/src/deep/in/path/File.php#510
```

Instead:

```ruby
@file://src/deep/in/path/File.php#510
```

or maybe lend from vscode `settings.json`

```ruby
@file://${workspaceFolder}/src/deep/in/path/File.php#510
```

**Comment by fabiospampinato** [comment]
The extension has not special support for `file://` urls, they are handled by vscode itself, so this issue should be opened there.
