### ISSUE TITLE
Is there a way of having multilines todo

### ISSUE THREAD

**Issue by albu77** [fabiospampinato/vscode-todo-plus#35]
If I have a very long toto description, it will be better to have multilines todo, is is optional?

**Comment by fabiospampinato** [comment]
Real multiline todos are not supported, one of the reasons for this is that in some cases it will be impossible to decide if those 2 lines are just 1 todo or they actually represent 1 todo and 1 description.

But you can decide to have long todos displayed in multiple lines to you, effectively enabling multi-line todos even though they are actually a single line. It's all about line wrapping, you can enable/disable this with `alt+z` (at least that's the shortcut for macOS), this is what it would look like:

<img width="832" alt="screen shot 2018-03-01 at 14 10 56" src="https://user-images.githubusercontent.com/1812093/36846394-b5b694ac-1d5a-11e8-9748-4e8b31c7e50b.png">

**Comment by albu77** [comment]
Great, just what I need.... 
really nice tool and great job.

**Comment by fabiospampinato** [comment]
Thank you :)

**Comment by fabiospampinato** [comment]
@LeninZapata I don't understand your question, you should probably read VSC's docs.

**Comment by LeninZapata** [comment]
I want to have mulitilinea in TODO, but when pressing ATL + Z nothing happens, that's what I mean.

**Comment by fabiospampinato** [comment]
That's not related to any extension, check out vscode docs.

**Comment by LeninZapata** [comment]
But you yourself are saying that this is achieved with the combination of `ALT + Z` keys in this same topic
![image](https://user-images.githubusercontent.com/42600954/64864517-e4e1f800-d5fc-11e9-8c0b-df62a37c7006.png)

**Comment by sonatypeJimB** [comment]
I think this is what you want.

[How do I turn on word wrap?](https://code.visualstudio.com/docs/editor/codebasics#_how-do-i-turn-on-word-wrap)

**Comment by LeninZapata** [comment]
Now I understand, multiline can not, what they suggest is the word wrap, thanks.
