### ISSUE TITLE
Automatic moving of tasks by status change

### ISSUE THREAD

**Issue by immertroll** [fabiospampinato/vscode-todo-plus#350]
Process:
I change the status of a task from new to done (ALT+D)

Expected behavior:
The task will be marked as done and moved to category done.

Observed behavior:
The task remains in category new.

Plugin version: v4.18.4

**Comment by fabiospampinato** [comment]
The extension has no context of done/new categories. At most done task will be moved to the archive, there's a command for that, "Todo: Archive".

**Comment by immertroll** [comment]
Okay than I turn my request into a question. What is the background of "Done" then? Should I copy paste my done tasks into "Done:" manually? That seems not really useful to my mind.
![grafik](https://user-images.githubusercontent.com/13539454/154261827-82cc79a8-c35f-4b64-a9bc-c0f821f454be.png)

Archive is also just a category, right?

**Comment by fabiospampinato** [comment]
The archive is a special project that the extension understands about.

The extension just doesn't support moving tasks to arbitrary categories according to arbitrary logics.
