### ISSUE TITLE
Creation date presentation

### ISSUE THREAD

**Issue by sparrowek** [fabiospampinato/vscode-todo-plus#353]
It would be useful to have an add date presented next to the todo. When I press Alt+Enter it could be added automatically to the current date.

☐ water plants @added(22-04-21 11:01)
✔ water plants @added(22-04-21 11:01) @done(22-04-21 12:01)

PS: it is not the same as the start date.

**Comment by Rollyjoger85** [comment]
This is as far as I know already possible, except it's called created.
todo.timekeeping.created.time

![image](https://user-images.githubusercontent.com/40987871/168798008-1ed601fe-4ce5-4fc7-8928-fefa7a850b69.png)
