### ISSUE TITLE
embedded view without file level list, just comment on that todo

### ISSUE THREAD

**Issue by BizShuk** [fabiospampinato/vscode-todo-plus#359]
It's too messy with file level list.

// group: comment

Just list by
group1
- comment1
- comment2
group2
- comment3
- comment4

![image](https://user-images.githubusercontent.com/12511875/183362712-aa7913f7-6f68-416e-8f5d-60dae5ffc27e.png)

**Comment by fabiospampinato** [comment]
I'm not sure what you mean, isn't the list already pretty flat? I'm not sure what you are proposing exactly.

**Comment by fabiospampinato** [comment]
Closing for lack of more info.
