### ISSUE TITLE
Change Box Symbol Color

### ISSUE THREAD

**Issue by ghaschel** [fabiospampinato/vscode-todo-plus#360]
Is there an option to change only the box symbol color?

![image](https://user-images.githubusercontent.com/5878866/187798282-e9640298-3e8f-47cc-94ad-a0faa36f9e1d.png)

I would like my initial symbols to be colored in a different color than the todo text, is there such a thing?

For example:
- Having the "→" as orange, but the text that comes after it in white
- Having the "✔" as green, but the text after it, in a darker green
- Having the "✘" as red, but the text after it, in a darker red

**Comment by fabiospampinato** [comment]
It's not supported, and I don't think it will be supported.
