### ISSUE TITLE
Archive task's comments with parent task

### ISSUE THREAD

**Issue by kuhnerdm** [fabiospampinato/vscode-todo-plus#37]
Hi, I've noticed that, when I embed non-task text into a task, complete the task, and archive, the embedded text stays where it is, and becomes embedded under the task above the archived one. Any chance we could change the behavior from:

![ex1](https://user-images.githubusercontent.com/14303088/37690758-84df54c6-2c83-11e8-9998-b3d6693ae656.png)

to:

![ex2](https://user-images.githubusercontent.com/14303088/37690764-8d2cafde-2c83-11e8-9f61-41655c334bbe.png)

or at least have an option? Thanks, and thanks for the great plugin!

**Comment by fabiospampinato** [comment]
You're right, I'll be happy to consider a PR for this.

**Comment by fabiospampinato** [comment]
Implemented in v.1.14.0. Nested comments will get collapsed though.

<img width="576" alt="screen shot 2018-05-20 at 21 49 15" src="https://user-images.githubusercontent.com/1812093/40283017-249f370a-5c78-11e8-9c26-faa7b3aa0030.png">
<img width="576" alt="screen shot 2018-05-20 at 21 49 32" src="https://user-images.githubusercontent.com/1812093/40283018-24bd102c-5c78-11e8-98e2-da8cf2b542bb.png">
