### ISSUE TITLE
Multiline Active Text (not greyed out)

### ISSUE THREAD

**Issue by shanesaravia** [fabiospampinato/vscode-todo-plus#378]
I'm not sure if i'm the only one, and i'm sorry if this is the wrong place for it but i'm looking to have multiline text chunks in my .TODO files as active(not greyed out). I use this for todos and notes so sometimes i just have a chunk of code that falls under some type of project and would like the text to show up white. Is there an easy way to do this? I tried some things like wrapping it in ``` triple quotes and a few others. I know i can highlight it all and hit cmd+enter to assign them all checkboxes, but id rather avoid this as its a bit messier to read + when i come back here to copy that text, i have to undo the boxes first. Any help/suggestions are appreciated!

**Comment by fabiospampinato** [comment]
An older version of the extension had multiline support for some things, including code blocks I believe. However it made the extension harder to manage, and most importantly some optimizations harder to do, so I stopped support it. I don't have intention to add support for this again, you could try an older version if you really need this.
