### ISSUE TITLE
Disable "Donate" prompt after donating.

### ISSUE THREAD

**Issue by phyllisstein** [fabiospampinato/vscode-todo-plus#379]
I've donated to Todo+ and Highlight. I use them a lot, and like them a lot, and I'm that I could show my gratitude. However, there's no way to tell that to the extensions. And after installing VSCode in a new environment, I get nag notifications for both. This has become a headache as I've begun using Codespaces. Settings and state are ephemeral, scoped to each container; rebuilding a container or moving to a fresh codespace brings back the request toasts.

It's a minor quality-of-life whinge, but would you be in favor of adding a "disable donate prompt" setting?

**Comment by fabiospampinato** [comment]
Thank you for your donations! I didn't account for those kind of unconventional environments when writing the logic for this 🤦 In the meantime you should be able to disable the prompts by adding `"donations.disablePrompt": true` to your settings.

**Comment by phyllisstein** [comment]
Thank you! Microsoft throws a new and exciting un-convention at plugin authors every release, don't they?
