### ISSUE TITLE
file link for embedded TODOs doesn't work on Windows

### ISSUE THREAD

**Issue by jannkiepert** [fabiospampinato/vscode-todo-plus#38]
When embedding tasks in vscode on Windows the file-link only contains two slashes in
`file://path-to-doc` like this:

![grafik](https://user-images.githubusercontent.com/35337482/37998615-77fa7fd2-321f-11e8-890f-18635c708d2b.png)  
while it should be `file:///path-to-doc`

![grafik](https://user-images.githubusercontent.com/35337482/37998681-d5da05d2-321f-11e8-9429-89109b0a9b7f.png)

**Comment by fabiospampinato** [comment]
Thanks for reporting the problem, this should be fixed in v1.10.1.
