### ISSUE TITLE
User snippets seem to not work in *.todo files

### ISSUE THREAD

**Issue by Lightborne** [fabiospampinato/vscode-todo-plus#381]
Hello,
I am trying to create a snippet to inserts the week within my `*.todo` files.  Here is what I have in my `*.code-snippets` file:

    "header":{
        "prefix": "header",
        "body": [
            "// ----------------------------------------------------------------------",
            "// Week of $CURRENT_YEAR-$CURRENT_MONTH-$CURRENT_DATE",
            "// ----------------------------------------------------------------------",
        ],
        "description": "Add a header for the current week"
    },

However, no matter what I try I can't get this snippet to work within my `*.todo` files.  

I guess I don't fully understand how this extension messes with VSCode's built-in snippet functionality, and if this behavior is intentional or not.  Anyone have any suggestions?

**Comment by henrikvilhelmberglund** [comment]
Try going Command palette - Snippets: Configure User Snippets - todo (todo.json)
then paste it there inside the curly braces.
I think you will need to press `ctrl+space` to actually insert the snippet.

**Comment by dht** [comment]
I've tried to add your exact snippet and it seems to be working for me, great snippet by the way.

**Comment by fabiospampinato** [comment]
Closing as the issues seems to not be with the extension itself (?).
