### ISSUE TITLE
Feature: Could you add full support for the @file tag please?

### ISSUE THREAD

**Issue by cavariux** [fabiospampinato/vscode-todo-plus#39]
Hi, I was looking at how you implemented the @file tag in the open embedded, but I can't make it work without putting the entire file path, which doesn't really works for different computers.
If it already exists could you please add some documentation on how to use it. Thanks 👍

**Comment by fabiospampinato** [comment]
This extension only provides syntax highlighting for tags.

Texts such as `file:///path/to/file` are treated as links by Visual Studio Code, in fact you can even visit them with a browser.

I'm not sure I can implement this in a cross-computer way, but even if I could, this file is generated on demand, so I don't really see the need of saving it for sharing with another computer, that other computer should just regenerate it on its own.
