### ISSUE TITLE
[Feature Request] auto save when change todo status

### ISSUE THREAD

**Issue by maple-leaf** [fabiospampinato/vscode-todo-plus#41]
I thinks it's fair feature that when I change todo status, like `start`, `done`, `TODO` file should be saved automatically. :-)

**Comment by fabiospampinato** [comment]
You could enable something similar to this at the editor level: https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save.

I don't think this should be implemented in an extension 🤔 

I'm going to keep this open though, if this gets requested a lot I might add it.

**Comment by GlutenBoy** [comment]
It's true that you can activate it at the editor level, but this affects all files. I think a better solution at editor level would be to be able to specify which type of files would auto-save. Then we could say "Alexa auto-save .todo type files please" :)

**Comment by fabiospampinato** [comment]
@GlutenBoy That sounds like a good idea to me, maybe you should open an issue about this in VSC's repo.

**Comment by GlutenBoy** [comment]
FYI I found an extension that does that, it's called: Save Typing by Michel Betancourt . Just make sure you set the setting: "save-typing.languages": ["todo"]

This will auto-save only your .todo files.

**Comment by fabiospampinato** [comment]
Closing in favor for more general extensions that let you autosave specific file types.
