### ISSUE TITLE
Same symbols for normal/done/cancelled tasks

### ISSUE THREAD

**Issue by sahil48** [fabiospampinato/vscode-todo-plus#43]
I wanted the symbol used for the every tasks, and done and cancelled tasks to be a - instead of ☐, ✔, and ✘.

I tried modifying "todo.symbols.done", "todo.symbols.cancel", and "todo.symbols.box", but it doesn't seem to be having any effect.

**Comment by fabiospampinato** [comment]
> I wanted the symbol used for the every tasks, and done and cancelled tasks to be a - instead of ☐, ✔, and ✘.

As I understand it this would be a requirement for [taskpaper compatibility](https://github.com/fabiospampinato/vscode-todo-plus/issues/26), which is not a goal of this project. I'd consider a PR for this.

> I tried modifying "todo.symbols.done", "todo.symbols.cancel", and "todo.symbols.box", but it doesn't seem to be having any effect.

This doesn't change existing todos, but if you create a new one, or toggle the box on an existing one, you'll see that the new symbols are being used.

**Comment by fabiospampinato** [comment]
Implemented in v1.18.0.
