### ISSUE TITLE
Consider any todo with the tag @done or @cancelled completed

### ISSUE THREAD

**Issue by sahil48** [fabiospampinato/vscode-todo-plus#44]
I would like to have any line with the @done tag and @cancelled tag highlighted green and red, respectively.

**Comment by fabiospampinato** [comment]
I think this is a requirement for  [taskpaper compatibility](https://github.com/fabiospampinato/vscode-todo-plus/issues/26).

I'll be happy to consider a PR for this.

**Comment by fabiospampinato** [comment]
Implemented in v1.18.0.

**Comment by sahil48** [comment]
Thank you very much!
