### ISSUE TITLE
[Feature Request] add option to specify timekeeping color

### ISSUE THREAD

**Issue by maple-leaf** [fabiospampinato/vscode-todo-plus#45]
![image](https://user-images.githubusercontent.com/3980995/38488678-c7531142-3c16-11e8-84f2-2c77f71d6568.png)

I use `solarized-light` theme, and timekeeping color not very clear on light background

**Comment by fabiospampinato** [comment]
Those are colored like any other tag, just change the `todo.colors.tag` option.
