### ISSUE TITLE
Extra Boxes Generated on Completed/Cancelled toggle

### ISSUE THREAD

**Issue by tvanyo** [fabiospampinato/vscode-todo-plus#46]
Just installed v1.10.3 and evaluating. I'm seeing unexpected behavior when I toggle a task completed or cancelled; instead of modifying the original box, it is adding boxes.

The settings I've modified are as follows:
``` 
…
    "todo.symbols.box": "[]",
    "todo.symbols.cancel": "[-]",
    "todo.symbols.done": "[x]",
    "todo.timekeeping.finished.format": "DD.MM.YY",
… 
```

If I start with this:
    `[] Some task` 
and hit `ALT+D` to "Complete" the task, I'm left with this:
    `[x] [] Some task @done(15.4.18)`
Hitting `ALT+D` to "undo" the completion leaves me with:
    `[] [] Some task`

I can repeat this ad nauseum. Seem like it is not checking for the existence of boxes.

**Comment by fabiospampinato** [comment]
`[]` is not a valid box, `[ ]` is. Basically you have to have a space between the brackets.

Do this:

```diff
- "todo.symbols.box": "[]",
+ "todo.symbols.box": "[ ]",
```

And it should work.

**Comment by tvanyo** [comment]
First, thanks for getting back so quickly.
Second, that did fix it.
Third, this space/no-space thing has killed me on several extensions. PlainTasks for SublimeText doesn't have the space, but it isn't clear in the documentation. You might consider a comment in the readme to clarify that.

**Comment by fabiospampinato** [comment]
Thanks for the suggestion, I'll consider that.

I was thinking maybe the extension should just support `[]` too, the space is there mostly for alignment purposes anyway.

**Comment by tvanyo** [comment]
I may try to make that change. I have some other things I'd like to see, but I see you have a number of feature requests that you'd like to see PRs for, so I'll oblige.
