### ISSUE TITLE
Add @created(18-05-07 12:40) on new tasks

### ISSUE THREAD

**Issue by jasonarden** [fabiospampinato/vscode-todo-plus#48]
<img width="829" alt="screenshot 2018-05-07 12 51 30" src="https://user-images.githubusercontent.com/1065222/39713636-7937968c-51f5-11e8-8026-9a032611087b.png">

**Comment by fabiospampinato** [comment]
It seems like a nice addition, I won't personally use this so I'd rather consider a PR for this.

Thanks for the suggestion.

**Comment by fabiospampinato** [comment]
Implemented in v1.11.0 (thank you @FabysGames!), although the cursor gets moved past the `@created` tag, which is not optimal, we'll tackle that at a later time.
