### ISSUE TITLE
Box does not get removed in 1.11.0 for intended tasks

### ISSUE THREAD

**Issue by fabysdev** [fabiospampinato/vscode-todo-plus#52]
Hi,

For Example:

```
☐ Archiving 
  ☐ Sort entries by finished time if possible @created(2018-05-20 06:13)
  ☐ Setting for adding the project as suffix to entries
  ☐ Move also entries' comments
```

After setting an intended ToDo (e.g. Sort entries...) to done, the box stays in place.
You get following output:

![image](https://user-images.githubusercontent.com/2088490/40275617-335d97a6-5bf5-11e8-9352-f44aba0e3032.png)

If you set it to Done again (removing it) you get an extra box at the beginning:
![image](https://user-images.githubusercontent.com/2088490/40275626-ade68d7a-5bf5-11e8-8df5-429c19ddd6e3.png)

I think it is caused by 565b42e0819d940199da48c30d701317f9c36dde (Reverting it fixes it for me).

**Comment by fabiospampinato** [comment]
Fixed in v1.11.1. Thanks a lot for reporting the issue!
