### ISSUE TITLE
Question about (0) after each project

### ISSUE THREAD

**Issue by sahil48** [fabiospampinato/vscode-todo-plus#55]
After the latest todo-plus update, I notice a (0) after every project. What does this do, and what causes the counter to up?

![image](https://user-images.githubusercontent.com/6100774/40363556-e4f1e770-5d9d-11e8-93e6-b645f4920753.png)

**Comment by fabiospampinato** [comment]
Those are project-level statistics, a recent addition. That's the number of pending todos inside that project basically, but this is customizable, you can read more about them in the readme.

**Comment by sahil48** [comment]
Okay. When using taskpaper syntax, it seems to be working on some projects, but on most of them, the count is staying zero.

**Comment by fabiospampinato** [comment]
@sahil48 You're probably indenting your todos with something other than what's set in `todo.indentation`, am I right? If not, can you paste here the content of your todo file so that I can try to reproduce the problem?

**Comment by sahil48** [comment]
You were right. My taskpaper file was using tabs instead of spaces. Once I converted the tabs to spaces, project statistics are working perfectly. Thanks a lot.

**Comment by fabiospampinato** [comment]
No problem. Maybe this extension should support both tabs and spaces by default 🤔 Ideally there shouldn't be a need for the `todo.indentation` setting at all.
