### ISSUE TITLE
Only show project-level statistics when tasks are in project

### ISSUE THREAD

**Issue by sahil48** [fabiospampinato/vscode-todo-plus#56]
Please show status of a project (ex. Project1: (1/3)) when there are tasks in the project. Sometimes, I use it the project as a heading for notes.

**Comment by fabiospampinato** [comment]
This is tricky to do, you might want to hide project-level statistics when there are no todos inside them, somebody else might want to hide them if there are no _pending_ todos, or something else.

I'll think about it!

**Comment by fabiospampinato** [comment]
Now a JS expression can be used as the `enabled` condition, by default for project it's `"global.projects < 100 && project.pending > 0"`.
