### ISSUE TITLE
You have to open a project before being able to open its todo file

### ISSUE THREAD

**Issue by Michael-0** [fabiospampinato/vscode-todo-plus#6]
When I execute the todo: open command, I get the following error : "You have to open a project before being able to open its todo file". I do have a folder opened, what am I missing ?

Thank you.

**Comment by fabiospampinato** [comment]
Perhaps you were running the `Todo: Open` command while the focused editor was about a file stored outside the currently opened folders, like for instance VSC's settings file?

**Comment by fabiospampinato** [comment]
Should be fixed on v1.5.0. Closing as duplicate of #7.
