### ISSUE TITLE
[Enchancement] Set done a group of selected Todo Task

### ISSUE THREAD

**Issue by samael205** [fabiospampinato/vscode-todo-plus#60]
Hi,

My idea is the next,

You have a couple of todo task done, like... 7

`☐ Task 1 @created(18-05-25 15:27)`
`☐ Task 2 @created(18-05-25 15:27)`
`☐ Task 3 @created(18-05-25 15:27)`

And I have completed all three tasks,

It could be implemented that you could select all three, and hitting the combination Alt + d the three tasks would be set to done.

I do not think it is very difficult, I have an idea, and I think it would be easy to go through the selected lines and pass them to the function that you use to establish the tasks to be done.

And I have completed all three tasks,

It could be implemented that you could select all three, and hitting the combination Alt + d the three tasks would be set to done.

I do not think it is very difficult, I have an idea, and I think it would be easy to go through the selected lines and pass them to the function that you use to establish the tasks to be done

I would like to help, but the extension is not compiled to work in VSCode

**Comment by fabiospampinato** [comment]
> I would like to help, but the extension is not compiled to work in VSCode

What do you mean? You can't start debugging?

> It could be implemented that you could select all three, and hitting the combination Alt + d the three tasks would be set to done.

I don't like this. The solution to this problem is multi cursors. Put a cursor in every task and mark all of them as done with a single `alt+d`.

**Comment by samael205** [comment]
You're right, in both parts.

I did not know that you could do that with the multi-cursor, `I have not seen it anywhere that explains it.`

And now, I have tried to compile the application, and I needed to install node and the vscode modules. I still do not know much about this node

**Comment by fabiospampinato** [comment]
> And now, I have tried to compile the application, and I needed to install node and the vscode modules. I still do not know much about this node

There's a bit of a learning curve, but don't worry, I've all been through that :)
