### ISSUE TITLE
How do I show percentage completion on subtasks?

### ISSUE THREAD

**Issue by hearsay1423** [fabiospampinato/vscode-todo-plus#61]
I would like to see the percentage of completion on subtasks projects. Could you please explain how I can do this? I apologize, I didn't understand the documentation to enable this option. Thank you.

**Comment by hearsay1423** [comment]
Also, is it possible to change the tag colors e.g. @thistagisblue @thistagisyellow

**Comment by fabiospampinato** [comment]
> I would like to see the percentage of completion on subtasks projects. Could you please explain how I can do this?

The default template for project-level statistics (it works only for projects, not for tasks, but you can also run `Todo: Toggle Done` on a project) is: `"todo.statistics.project.text": "([pending]) [est]"`, you have to write the `[percentage]` token in it if you want percentages to show up, so you could set it to:   `"[percentage]%"` maybe.

> Also, is it possible to change the tag colors e.g. @thistagisblue @thistagisyellow

Yes, some customizable tags are colored, you just have to edit this settings:

```json
  "todo.tags.names": ["critical", "high", "low", "today"], // Special tags' names
  "todo.tags.backgroundColors": ["#e54545", "#e59f45", "#e5d145", "#ae81ff"], // Special tags' background colors
  "todo.tags.foregroundColors": ["#000000", "#000000", "#000000", "#000000"], // Special tags' foreground colors
```
