### ISSUE TITLE
Autosuggest tags in same document

### ISSUE THREAD

**Issue by sahil48** [fabiospampinato/vscode-todo-plus#62]
I know you can change the default tags. I think it would be useful if todo-plus could suggest tags the user has used in the current document or current folder.

**Comment by fabiospampinato** [comment]
I like this. We should also take into account special tags and avoid suggesting them: `@created/started/done/cancelled/lasted/wasted/est`.

If anyone wants to submit a PR I'll be happy to consider it.

**Comment by rbenson** [comment]
I don't know if autosuggest is the right word, but if i did `some task @high @callback` the next time I hit @ `callback` appears with high/low/etc. Sandy081's todo's ext has this, and I believe you used his as a basis for todo-plus. It has to do with implementing typings, which I have zero idea how to make work.

**Comment by fabiospampinato** [comment]
@rbenson I can't reproduce what you're saying in [vscode-todotasks](https://github.com/sandy081/vscode-todotasks):

<img width="639" alt="screen shot 2018-06-06 at 22 37 25 1" src="https://user-images.githubusercontent.com/1812093/41063913-4c5a7e48-69da-11e8-849f-c0cd909c6883.png">

**Comment by rbenson** [comment]
@fabiospampinato sorry, i think  it broke a few versions ago. The ext is no longer maintained, but over a year ago it worked. Somewhere I remember [typings](https://github.com/typings/typings) were used to make the file "aware". I remember wanting to implement it into a thing I was building, but was over my head.

**Comment by fabiospampinato** [comment]
@rbenson I don't think typings had anything to do with it, after all the code does get compiled to untyped javascript. 🤔

**Comment by fabiospampinato** [comment]
Implemented in v4.3.0. Can be disabled via the `todo.tags.namesInference` setting.
