### ISSUE TITLE
[Suggestion] Project color change when all todos set done

### ISSUE THREAD

**Issue by samael205** [fabiospampinato/vscode-todo-plus#63]
It could be a good idea if the projects change color to green or to the color that the user chooses when all the tasks are done.

I know that at the end of all these tasks, the counter disappears after ':', but if you have a large project title, you must scroll horizontally

**Comment by fabiospampinato** [comment]
I don't like this, it would create confusion as a green line might be a todo or a project. If you want to mark a project as "done" just execute "Todo: Toggle Done" on it and make it a done todo.
