### ISSUE TITLE
how to find all todo lines begined with %%

### ISSUE THREAD

**Issue by TheKiteRunning** [fabiospampinato/vscode-todo-plus#64]
Hi, thanks for your work, I really like the design.

I just wonder how to make todo+ work with documents like: `% todo: task1` or `%% todo: task2`

By the way, I cannot create new tasks with ctrl + enter, when I use this command, it just turns to plain text.

**Comment by fabiospampinato** [comment]
> Hi, thanks for your work, I really like the design.

Thank you :)

> I just wonder how to make todo+ work with documents like: % todo: task1 or %% todo: task2

Do you basically want to have todos starting with `%` instead of `☐` or any of the other supported symbols?

> By the way, I cannot create new tasks with ctrl + enter, when I use this command, it just turns to plain text.

What do you mean with "it just turns to plain text"? 

Are you on Windows?

**Comment by TheKiteRunning** [comment]
Thanks for your reply.

> Do you basically want to have todos starting with % instead of ☐ or any of the other supported symbols?

my todos are always in the comments started with `%` or `%%`

> What do you mean with "it just turns to plain text"?
![dashborad](https://user-images.githubusercontent.com/24802332/40692974-84444bd4-63e7-11e8-9a5a-3fad1e75d881.gif)

> Are you on Windows?

yes, windows 8.1 64bit

Thanks again!

**Comment by fabiospampinato** [comment]
> my todos are always in the comments started with % or %%

Is that a yes? Do you want to write todo files that look like this or not?:

```
Foo:
  % my todo
```

> By the way, I cannot create new tasks with ctrl + enter, when I use this command, it just turns to plain text.

Read the readme, ctrl+enter triggers the `Todo: Toggle Box` command, and that's exactly what's happening, the box is getting toggled. I'll have to run it on an empty line to create a new todo there.

**Comment by TheKiteRunning** [comment]
Hi, sorry for not expressing my idea clearly.
1. my script file is like the image below,and I what to extract all the Todos|Fixmes begin with % or %% by using the command `Todo: open embeded`
![image](https://user-images.githubusercontent.com/24802332/40826817-60d0d5dc-65ae-11e8-81e8-e60c3d920ab3.png)
2. I get it, it seems a little complex since we have to click `enter` and `ctrl + enter` for a new todo.

Thanks for your help!

**Comment by fabiospampinato** [comment]
> my script file is like the image below,and I what to extract all the Todos|Fixmes begin with % or %% by using the command Todo: open embeded

You'll have to replace the default `"todo.embedded.regex"` setting with something else, maybe this? (I haven't tested it):

```
"(?:<!-- *)?(?:#|%%|%|//|/\\*+|<!--) *(TODO|FIXME|FIX|BUG|UGLY|HACK|NOTE|IDEA|REVIEW|DEBUG|OPTIMIZE)(?: |:|\"|'|`|-->|$)"
```

> I get it, it seems a little complex since we have to click enter and ctrl + enter for a new todo.

I think it's just a matter of getting used to it. After all you're just making a new line and executing a shortcut. You can also use `-` as your box symbol, maybe this will simplify the process a bit.
