### ISSUE TITLE
Contributing to todo+

### ISSUE THREAD

**Issue by Hexadelic** [fabiospampinato/vscode-todo-plus#66]
Hi
Im coming from sublime to vscode, but im pretty dependant on my customised plaintasks.

Specifically my custom tags, and id like to keep my formatting (strikethrough for done tasks etc)

I can contribute to #59 as i require this also.

Iv not worked with vscode before, but i checked the source and i don't see it being much trouble to do.

But when i clone and try to run the extension (F5) i get the error:

> Activating extension 'fabiospampinato.vscode-todo-plus' failed: Cannot find module '....vscode-todo-plus/out/src/extension.js'.

**Comment by fabiospampinato** [comment]
@Hexadelic did you installed the necessary dependencies first? (basically running `npm install` at the root of the project)

**Comment by Hexadelic** [comment]
I knew it would be something simple, that did the trick.

> As far as I know in PlainTasks you can't have custom tags that look different from any other tag, am I wrong?

Your right, but i customised the plain tasks to hard code my custom tags into the plugin. 
I seen that it would be much easier to do with todo+, as you already have the tags customisable.

**Comment by Hexadelic** [comment]
Any ideas why this is happening:

I figured to just check if the tag is special, then just change to range to start at the start of the line rather than start of tag:

decorators/tag.ts:
`return this.TYPES.map((type, index) => {
      //Because isSpecial doesnt work for some reason...?
      var test = Consts.regexes.tagSpecial.test(tag.text);

      if(test) {
        return tag.match[index + 1] && tag.rangeLine;

      } else {
        return tag.match[index + 1] && tag.range;

      }
    } );`

<img width="539" alt="screen shot 2018-05-31 at 10 36 09" src="https://user-images.githubusercontent.com/39024645/40774821-85cbd026-64be-11e8-9b72-bb84b99039f6.png">

As you can see, the behaviour is as expected. But only for some tags and not others. They have the foreground colours set in settings (as you can see the tag changes colour).
I noticed that if i log the regex test. Its called multiple times per tag. Sometimes true, sometimes false.

**Comment by fabiospampinato** [comment]
You didn't understand how my code works, in `getItemRanges` we are kind of trying to put the range into the right bucket (the right "type"). `getItemRanges` is written weirdly for tags, but that's a performance optimization, note how `Tag#TYPES` has the same order as `Consts.regexes.tagSpecialNormal`'s capturing groups, I'm avoiding using extra regexes, this would be a problem for very large files.

Besides there's a problem with VSC APIs:

- You can't provide multiple contrasting decorations to the same range (i.e. setting different colors in the same range) and expect it to just work.

And there are a few problems with your approach:

- What if I have both `@today` and `@critical` on the same line?
- What if a todo with `@today` gets completed?
- There might be code blocks or other tags in the same line, you can't just override their decorations
- Where does that `rangeLine` come from?
- Are you sure `Tag#isSpecial` doesn't work?
- Executing another regex for each tag is too slow, in this case you can check if the tag is "special" just by looking at the index of the matched group

You chose to tackle a tricky problem, I personally have no idea how to properly tackle this.

**Comment by Hexadelic** [comment]
Hmm i see, i guess il have to make do with just having coloured tags.

I probably could of made do without some of the features, but having it not change when completed is too much of an inconvenience. Thanks for your help though

**Comment by Hexadelic** [comment]
Ok a workaround, i just removed the tags when completed / cancelled. 
Maybe not ideal for production but should satisfy my requirements.

**Comment by fabiospampinato** [comment]
There's an option for that, without needing to modify the code.

Anyway I'm closing this, feel free to open a new one if needed.

**Comment by mrdc** [comment]
@fabiospampinato 

Hi, 
Can we have `strikethrough for done tasks` as was mentioned earlier?

**Comment by fabiospampinato** [comment]
@mrdc open a new issue about that if there isn't one already.
