### ISSUE TITLE
Syntax renders whitespace character as part of the sentence

### ISSUE THREAD

**Issue by einaralex** [fabiospampinato/vscode-todo-plus#67]
When using the setting  `editor.renderWhitespace": "all"` the syntax colors the whitespace character as a part of the sentence.

Like so:
 ✔ This·is·a·sentence

**Comment by fabiospampinato** [comment]
Why are you rending the whitespace characters? :D 

Anyway there's an issue about this in VSC https://github.com/Microsoft/vscode/issues/49462. I could fix this without a special option but it would complicate the code quite a bit and affect performance considerably I think.

**Comment by einaralex** [comment]
I like having them visible to see my indenting and trailing whitespaces :)
Changing the editor.renderWhitespace value to "boundary" instead of "all" does the job.
Great extension btw, use it every day! Thanks :D

**Comment by fabiospampinato** [comment]
Thank you :)
