### ISSUE TITLE
Remove tags when completed

### ISSUE THREAD

**Issue by Hexadelic** [fabiospampinato/vscode-todo-plus#68]
You mentioned on my other issue about there is already an option to remove the tags when completed, without modifying the code.
I can't seem to find it within the settings anywhere?

**Comment by fabiospampinato** [comment]
@Hexadelic Sorry for the delay, I must have missed this issue.

Yes you can tell Todo+ to not write the `@done` and `@cancelled` tags, this is the option you're looking for:

```
  "todo.timekeeping.finished.enabled": true, // Enable the @done/cancelled tag. It's always enabled if you explicitly start a todo or if you use only 1 symbol
```
