### ISSUE TITLE
Change folder.uri.path to folder.uri.fsPath

### ISSUE THREAD

**Issue by Cl3r1k** [fabiospampinato/vscode-todo-plus#7]
https://github.com/fabiospampinato/vscode-todo-plus/blob/53ce80852f020891c0bb38f851a6c426dac8b350/src/utils.ts#L170

I've got the same problem as in #6 and #5
But wanted to test the extension)
I'm not quite good enough in TS and JS but after some searching and debugging, found, that in the line https://github.com/fabiospampinato/vscode-todo-plus/blob/53ce80852f020891c0bb38f851a6c426dac8b350/src/utils.ts#L173 the result of basePath.startsWith ( rootPath ) is false.
For example if argument is basePath = c:\Users\User\Projects\ProjectName\README.md
then after sorting:
https://github.com/fabiospampinato/vscode-todo-plus/blob/53ce80852f020891c0bb38f851a6c426dac8b350/src/utils.ts#L171
the sortedRootPaths contains rootPath = /c:/Users/User/Projects/ProjectName, so startsWith returns false.
I don't know what was the cause to use uri.path instead uri.fsPath (maybe it case sensetive in other OS?) but when I changed path to fsPath it worked fine)

Dear, fabiospampinato, can you review and fix the issue, or improve it some other way?

**Comment by fabiospampinato** [comment]
Thanks a lot for this information. Those damn Windows paths are always a reliable source of bugs.

I'm already working on a few commits, I'll fix this right after those.

**Comment by fabiospampinato** [comment]
This should be fixed on v1.5.0.
