### ISSUE TITLE
Problem with paths on folders with white spaces in folder name

### ISSUE THREAD

**Issue by gsabater** [fabiospampinato/vscode-todo-plus#72]
Hello,

First of all, nice extension.
I have found an issue though, when I open embedded todos in my whole project, the @file link is broken due to white spaces in the folder name, thus breaking the alt+click option to open the file.

Other extensions solve this by urlencoding paths.

Thanks for your time

**Comment by fabiospampinato** [comment]
Oh right, I don't use folders with spaces in their names for my projects so I never encountered this problem.

I guess I'll have to update a few of my extensions then.

Thanks for reporting the issue! 😄

**Comment by fabiospampinato** [comment]
Fixed in v.2.1.4. Thanks again!
