### ISSUE TITLE
Shortcut for inserting Date

### ISSUE THREAD

**Issue by CodeRevver** [fabiospampinato/vscode-todo-plus#75]
Would be great to add a shortcut that could insert a date to save people typing it out.  

I often create a todo list each day and type it out manually like so:

![image](https://user-images.githubusercontent.com/5285928/41475462-c3fbdbf8-70b6-11e8-91c1-be3fd34cf6bf.png)

A keyboard shortcut that could insert it for me would be awesome.  

Submitting this here to see if anyone doesn't want it in the extension/wouldn't accept it into the codebase.  

If willing to accept the feature I might write the code for it.

**Comment by fabiospampinato** [comment]
This doesn't seem general enough to me to be integrated in the extension itself.

You should write another extension for inserting those, or just a little snippet using this extension: https://marketplace.visualstudio.com/items?itemName=mkloubert.vs-script-commands.
