### ISSUE TITLE
[Customization Request] Symbol color customizations

### ISSUE THREAD

**Issue by ihccdeveloper** [fabiospampinato/vscode-todo-plus#77]
Firstly, this is a great plugin. I love the counters and percentages and all the tags that set this one apart from the others. Great job, thank you. This was a nice easy transition from Atom's version I used. 

There is once slight difference that I wish I could change, the symbol markers color. 

![capture](https://user-images.githubusercontent.com/40176702/41684577-70e6e426-74a3-11e8-86df-7cfc1b1bcd4a.PNG)

If you have time, or find it to be something similar to another item in your roadmap, can you add the option to customize these depending on the item state. 

Thanks again for all the work you put into this

**Comment by fabiospampinato** [comment]
VSC added a commit that broke this, before on Windows the symbols were actually colored as the rest of the todo. They reverted the change and I think everything should go back to normal with the next release. 

Read https://github.com/fabiospampinato/vscode-todo-plus/issues/69 and the upstream issue for more details.
