### ISSUE TITLE
Global todo files

### ISSUE THREAD

**Issue by Jayphen** [fabiospampinato/vscode-todo-plus#78]
I keep all of my todos in a .txt file that is stored in Dropbox (so I can use it with Taskpaper as well as VSCode).

Currently it's only possible to access a todo file that is in a path relative to the project root. Would it be possible to instead reference any path on your machine, or is this not possible with VSCode? I'm currently using a symlink in every project, but would be nice if this could be transparent.

**Comment by fabiospampinato** [comment]
I actually made a standalone app for this use case, you might find it useful: https://github.com/fabiospampinato/noty

I like the idea of global todo files, but I'm not sure if what you suggest is general enough :thinking:

I think you should just make an extension for VSC that adds a command to the command palette or the statusbar for opening that file. Maybe one of those extensions that add favorites/bookmarks can be used for this. 

Certainly symlinking it all over the place is not great.

**Comment by fabiospampinato** [comment]
I'm closing this as I think this is beyond the scope of the extension.

**Comment by fabiospampinato** [comment]
Actually this is already somewhat supported, you can do what @nealot is doing [here](https://github.com/fabiospampinato/vscode-todo-plus/issues/140)
