### ISSUE TITLE
[QUESTION] Why the TODO+ doesn't index PHP

### ISSUE THREAD

**Issue by benyaminl** [fabiospampinato/vscode-todo-plus#79]
Hello, I've TODO on php files, but when open embeded TODO, it doesn't being indexed. Is there maybe settings that I miss? Thanks

my todo is in 
`
/**
* TODO : DO SOMETHING 
*/
`

**Comment by fabiospampinato** [comment]
That kind of todos aren't found by this extension.

We have a setting for customizing the regex used for finding todos, maybe you can customize it to fit your needs.

**Comment by benyaminl** [comment]
Okay.. thanks.
I've edit the regex.



Sent from My Asus Pegasus X005



Pada tanggal Sab, 30 Jun 2018 14.36, Fabio Spampinato <
notifications@github.com> menulis:
