### ISSUE TITLE
Todos counter next to folded project

### ISSUE THREAD

**Issue by PixelT** [fabiospampinato/vscode-todo-plus#8]
Possibility to (un)folding todos by project name
When project is folding, maybe display next to project name number of todos?

**Comment by fabiospampinato** [comment]
I like the idea, but I'm afraid implementing it wouldn't be easy.

I'll ponder on it, thanks for the suggestion!

**Comment by fabiospampinato** [comment]
I'll probably add support for this tomorrow.

**Comment by fabiospampinato** [comment]
> Possibility to (un)folding todos by project name

I'm not exactly sure what you meant there, feel free to open a separate issue if that hasn't been addressed.

> When project is folding, maybe display next to project name number of todos?

I've added project-level statistics in v1.16.0, there are quite powerful, I'm pleased with the result, hopefully you'll be too:

<img width="576" alt="Project Statistics" src="https://user-images.githubusercontent.com/1812093/40304712-0d9fdd7c-5cf8-11e8-8060-4867890cc531.png">

![Project Statistics](https://user-images.githubusercontent.com/1812093/40304710-0d836368-5cf8-11e8-9f7a-d8daf0c447f4.gif)

**Comment by PixelT** [comment]
>I'm not exactly sure what you meant there, feel free to open a separate issue if that hasn't been addressed.

I meant this:
https://code.visualstudio.com/assets/updates/1_17/region-folding.gif
