### ISSUE TITLE
Adding negation '!' in "exclude" glob array returns "No embedded todos found"

### ISSUE THREAD

**Issue by quantos-unios** [fabiospampinato/vscode-todo-plus#83]
Hi, Thank you for creating this awesome extension. You guys are doing great. I really like this extension. Currently I am facing an issue

My exclude settings are as follows:

``` 
"todo.embedded.exclude": [
        "**/.git",
        "**/.svn",
        "**/.hg",
        "**/.vscode",
        "**/.github",
        "**/.next",
        "**/node_modules",
        "**/bower_components",
        "**/dist",
        "**/build",
        "**/out",
        "**/output",
        "**/_output",
        "**/third_party",
        "**/*.min.*",
        "**/*.map",
        "local/vendor/**",
        "local/storage/**",
        "js",
        "!js/main.js"
    ]
```
What I expect for todo-plus is to ignore all files in **"js"** folder except **"js/main.js"** but adding **'!'** in front of **"js/main.js"** doesn't generate TODOs list and shows notifications **"No embedded todos found"**.

 If I remove **'!'** from **"!js/main.js"** then it works correctly but I want todo-plus to not ignore **"js/main.js"**. Am I missing something? Help me please

**Comment by fabiospampinato** [comment]
> Hi, Thank you for creating this awesome extension. You guys are doing great. I really like this extension. 

Thank you :)

> What I expect for todo-plus is to ignore all files in "js" folder except "js/main.js" but adding '!' in front of "js/main.js" doesn't generate TODOs list and shows notifications "No embedded todos found".

It feels a bit weird to have negative globs for "exclusion", but I think it actually makes sense. 

Anyway this is an upstream issue, the globs are handled by [globby](https://github.com/sindresorhus/globby) which in turns uses [fast-glob](https://github.com/mrmlnc/fast-glob) under the hood, that seems to be to source of this problem (https://github.com/mrmlnc/fast-glob/issues/86 https://github.com/mrmlnc/fast-glob/pull/103)

**Comment by quantos-unios** [comment]
@fabiospampinato Thank you for quick reply,

> Anyway this is an upstream issue, the globs are handled by globby which in turns uses fast-glob under the hood, that seems to be to source of this problem (mrmlnc/fast-glob#86 mrmlnc/fast-glob#103)

Yeah it definitely isn't an issue with vscode-todo-plus then, from linked issues to fast-glob, it looks like lot of people are expecting this functionality in fast-glob. My hopes are high, may be we get this functionality in fast-glob soon. :) 

Anyway I tried adding **"js"** in **exclude glob** and **"js/main.js"** in **include glob** and it worked, it ignored all files in **"js"** except **"js/main.js"**

Again, Thank you for helping me :)

**Comment by fabiospampinato** [comment]
> Anyway I tried adding "js" in exclude glob and "js/main.js" in include glob and it worked, it ignored all files in "js" except "js/main.js"

Nice, I'm glad you found a solution to this.
