### ISSUE TITLE
Use the entire range for titles for symbol provider

### ISSUE THREAD

**Issue by usernamehw** [fabiospampinato/vscode-todo-plus#87]
Issue Type: <b>Feature</b>

There is a new available feature (at least in insiders) - breadcrumbs. It still matters though even without that feature.

Currently symbol provider highlights only 1 line (without any nested (children) lines):
![todo_demo](https://user-images.githubusercontent.com/9638156/43223275-414efb76-905b-11e8-9bad-8534a63a630f.png)

More useful providers (like js) highlight the entire zone:
![js_demo](https://user-images.githubusercontent.com/9638156/43223296-5392a800-905b-11e8-9b10-76539e0912c2.png)

On top of that, breadcrumbs is used to track your position in document and a really useful feature:
![js-moving](https://user-images.githubusercontent.com/9638156/43223485-eb78cde8-905b-11e8-84ef-24267901e7e7.gif)

Todo file is not doing so good there:
![todo_moving](https://user-images.githubusercontent.com/9638156/43223501-fc69a1c2-905b-11e8-95f6-82ed1c8da902.gif)

Extension version: 2.2.1
VS Code version: Code - Insiders 1.26.0-insider (5fae91d61f12726e149fe5baed342eac2fbf8f88, 2018-07-25T02:04:01.629Z)
OS version: Windows_NT x64 10.0.17134

**Comment by fabiospampinato** [comment]
Thanks for the suggestion, I'll investigate this.

Feel free to submit a PR for this if you want.

**Comment by fabiospampinato** [comment]
Fixed in v.2.3.0.
