### ISSUE TITLE
todo.colors.* dont work with todo.tags.*

### ISSUE THREAD

**Issue by PixelT** [fabiospampinato/vscode-todo-plus#9]
If I have custom tag or tags in my todos, then todo.colors.* doesn't work:

![todo-colors](https://i.imgur.com/zEdN2dJ.png)

**Comment by fabiospampinato** [comment]
Something doesn't look right here, why is `[ ]` yellow? 

Currently anything after a tag, except other tags, is not styled, that's a limitation of the current implementation. Tags are expected at the end of a todo.

Is something else broken?

Can you post your exact settings?

**Comment by fabiospampinato** [comment]
With v1.5.0 is possible to put tags inside todos and comments.

I'm still interested in your settings though, those `[ ]` don't look right.

**Comment by PixelT** [comment]
Those `[  ]` are look different than default because I have extension to [color brackets](https://github.com/CoenraadS/BracketPair).

My settings:
```
"todo.file": "todo.todo",
"todo.defaultContent": "",
"todo.symbols.box": "[ ]",
"todo.symbols.done": "[+]",
"todo.symbols.cancel": "[-]",
"todo.colors.tag": "#ffffff",
"todo.colors.done": "#27AE60",
"todo.colors.cancel": "#E74C3C",
"todo.colors.comment": "#2980B9",
"todo.formatting.enabled": false,
"todo.tags.names": [
    "critical",
    "bug",
    "feature",
    "improvement",
    "low",
    "high"
],
"todo.tags.backgroundColors": [
    "#000000",
    "#E74C3C",
    "#27AE60",
    "#2980B9",
    "#F1C40F",
    "#F1C40F"
],
"todo.tags.foregroundColors": [
    "#E74C3C",
    "#ffffff",
    "#ffffff",
    "#ffffff",
    "#ffffff",
    "#000000",
    "#000000"
]
```

**Comment by fabiospampinato** [comment]
Alright then, thanks!
