### ISSUE TITLE
Cannot find my embedded files

### ISSUE THREAD

**Issue by pochka15** [fabiospampinato/vscode-todo-plus#90]
![image](https://user-images.githubusercontent.com/24525928/43927718-18b2f77a-9c37-11e8-95f7-23b470694cdb.png)
Didn't change my settings, but after updating to 3.0.0 it throws error while looking for embedded todos.

**Comment by fabiospampinato** [comment]
Can you share your settings?

**Comment by fabiospampinato** [comment]
> Didn't change my settings

You might have to, v3 and v4 feature breaking changes, read the changelog.

**Comment by pochka15** [comment]
> You might have to, v3 and v4 feature breaking changes, read the changelog.

Thanks, v4 fixed bug!
