### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by PixelT** [fabiospampinato/vscode-todo-plus#91]
I updated extension to version 4.0
Now when I open it on activity bar and click refresh on File / Embeded bar, I get an error:
`command 'todo.viewEmbeddedRefresh' not found`
`command 'todo.viewFileOpen' not found`
also both panels are empty (even if I have todo.todo file or if I write inline TODO: in file)

**Comment by fabiospampinato** [comment]
Are you seeing any other errors? I think the extension isn't activating properly, otherwise those commands should get registered.

**Comment by PixelT** [comment]
Ok I found what was wrong:
I had `todo.file` instead of new `todo.file.name`

Now I set:

`"todo.file.name": "todo.todo"` 

and I created a file `todo.todo`, but when I open TODO in activity bar, I still have info in File tab:

`No todo file found`

Refresh button didn't help, after click on Open option I get an error:

`You have to open a project before being able to open its todo file`

I'm using https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager extension for project management

**Comment by fabiospampinato** [comment]
> You have to open a project before being able to open its todo file

This should mean that you didn't have any folder open in VSC, therefore no place where to find/create your `todo.todo` file.

Do you see this happening also when you have at least a folder open in VSC?

**Comment by PixelT** [comment]
But I normally have files when I open explorer tab, and there is `todo.todo` file...

**Comment by fabiospampinato** [comment]
There's no API for detecting the currently open file, you have to open a folder for this to work.

**Comment by fabiospampinato** [comment]
As of v4.0.6 it now checks if the configuration is invalid and it shows a descriptive error if that's the case.

This feature might be removed in the future, but for now it's useful given that I've pushed a few breaking changes.
