### ISSUE TITLE
Option to only show filename for embedded todos view

### ISSUE THREAD

**Issue by fabysdev** [fabiospampinato/vscode-todo-plus#95]
Hi,

Great updates, thank you.

It would be nice if one could change the embedded views todos  to only show the filename without the full path. Or maybe to remove the directory path from the name.

Because of the long path I am not seeing the actual filename.
![image](https://user-images.githubusercontent.com/2088490/43942074-ec44e08c-9c76-11e8-8622-7c053454e961.png)

Thanks.

**Comment by fabiospampinato** [comment]
That's how it's supposed to work, but for some reason it's not working on windows 🤔

**Comment by fabiospampinato** [comment]
Should be fixed in v4.0.5.
