### ISSUE TITLE
Commands broke?

### ISSUE THREAD

**Issue by johnRivs** [fabiospampinato/vscode-todo-plus#97]
I just started getting these.
![](https://i.imgur.com/xnj7ouD.png)

**Comment by fabiospampinato** [comment]
Read the messages, we renamed some settings, you have to update your settings accordingly.

**Comment by johnRivs** [comment]
![](https://i.imgur.com/jW7JAbi.png)
![](https://i.imgur.com/I7fsNJ0.png)
![](https://i.imgur.com/59daqbL.png)

What settings do I need to update? Default keybindings? Personal keybindings? Default user settings? User settings?

**Comment by fabiospampinato** [comment]
Read the other messages, it tells you exactly what to change.

**Comment by johnRivs** [comment]
Oh, it seems like the command wasn't getting registered. Thanks!

**Comment by fabiospampinato** [comment]
It wasn't getting registered because the extension threw an error because the configuration was invalid.
