### ISSUE TITLE
Add a debug option

### ISSUE THREAD

**Issue by muuvmuuv** [fabiospampinato/vscode-todo-plus#99]
Would be nice to see what todo+ is actually doing; which regex is running on which file if there is any error/warning, show excluded regex and included regex, ...

This would help to maintain problems.

**Comment by fabiospampinato** [comment]
> which regex is running

There's only one regex, the one defined in `todo.embedded.regex`

> on which file

Outputting which files are being searched for will slow down things in some cases, just keep in mind that include and exclude patterns are only supported by the `javascript` provider so far.

> if there is any error/warning

If there's an error when running `ag` or `rg` it should output that to VSC's console. If there's an error while reading a file it will fail silently, but I don't think that's much of a problem, it should basically never happen.

> show excluded regex and included regex, ...

There are no included and excluded regexes. Just include and exclude patterns (globs), which are currently only used by the javascript provider.
